import { ensureAuthSchema, requirePortalSession } from "../../../portal-auth";
import { createDatabase, type PostgresDatabase } from "../../../../db/postgres";
import { canViewEmployeeProfile, profileFieldPolicy } from "../../../employees/profile-access";

type Viewer={id:number;role_id:number;role_name:string;employee_id:number|null};
type Row=Record<string,unknown>;
async function permission(db:PostgresDatabase,user:Viewer,module:string,action:string){if(user.role_name==="Super Admin")return true;const row=await db.prepare("SELECT allowed FROM permissions WHERE role_id=? AND module=? AND action=?").bind(user.role_id,module,action).first<{allowed:number}>();return Boolean(row?.allowed);}
async function canAccess(db:PostgresDatabase,user:Viewer,employeeId:number){
  const managed=user.role_name==="Department Manager"&&Boolean(user.employee_id)&&Boolean(await db.prepare("WITH RECURSIVE managed AS (SELECT id FROM departments WHERE manager_employee_id=? AND status!='deleted' UNION ALL SELECT d.id FROM departments d JOIN managed m ON d.parent_id=m.id WHERE d.status!='deleted') SELECT e.id FROM employees e WHERE e.id=? AND e.department_id IN (SELECT id FROM managed)").bind(user.employee_id,employeeId).first<Row>());
  return canViewEmployeeProfile({roleName:user.role_name,isSelf:Number(user.employee_id)===employeeId,isInManagedScope:managed});
}
const failure=async(error:unknown)=>error instanceof Response?Response.json({error:await error.text()},{status:error.status}):(console.error(error),Response.json({error:"Unable to load employee profile"},{status:500}));

export async function GET(request:Request,context:{params:Promise<{id:string}>}){
  const db=createDatabase();
  try{
    await ensureAuthSchema(db);const session=await requirePortalSession(request,db),{id}=await context.params,employeeId=Number(id);if(!employeeId)throw new Response("Employee not found",{status:404});
    const user=await db.prepare("SELECT u.id,u.role_id,u.employee_id,r.name AS role_name FROM users u JOIN roles r ON r.id=u.role_id WHERE u.id=? AND u.status='active'").bind(session.userId).first<Viewer>();if(!user)throw new Response("Account disabled",{status:403});
    if(!(await canAccess(db,user,employeeId)))throw new Response("Employee is outside your access scope",{status:403});
    const employee=await db.prepare("SELECT e.id,e.employee_code,e.name_en,e.name_ar,e.work_email,e.work_phone,e.department_id,e.job_title_id,e.manager_id,e.organizational_level,e.start_date,e.end_date,e.employment_status,e.country,e.work_location,e.employment_type,e.schedule_type,e.work_days,e.check_in_time,e.check_out_time,e.grace_minutes,e.required_daily_minutes,e.avatar_url,e.created_at,e.updated_at,d.name_en AS department_name,d.name_ar AS department_name_ar,j.name_en AS job_title_name,j.name_ar AS job_title_name_ar,m.name_en AS manager_name,m.name_ar AS manager_name_ar FROM employees e LEFT JOIN departments d ON d.id=e.department_id LEFT JOIN job_titles j ON j.id=e.job_title_id LEFT JOIN employees m ON m.id=e.manager_id WHERE e.id=? AND e.employment_status!='deleted'").bind(employeeId).first<Row>();if(!employee)throw new Response("Employee not found",{status:404});
    const url=new URL(request.url),tab=url.searchParams.get("tab")||"overview",year=new Date().getUTCFullYear(),month=new Date().toISOString().slice(0,7),page=Math.max(1,Number(url.searchParams.get("page"))||1),limit=Math.min(50,Math.max(10,Number(url.searchParams.get("limit"))||25)),offset=(page-1)*limit;
    const [attendanceSummary,leaveBalances,requestCounts,exceptions,corrections,pendingRequests,account,documentAlerts,missingDocuments]=await Promise.all([
      db.prepare("SELECT COUNT(*) FILTER (WHERE status IN ('present','late','remote'))::integer AS present,COUNT(*) FILTER (WHERE late_minutes>0)::integer AS late,COUNT(*) FILTER (WHERE status='absent')::integer AS absent,COUNT(*) FILTER (WHERE attendance_type='remote')::integer AS remote,COUNT(*) FILTER (WHERE status='leave')::integer AS on_leave FROM daily_attendance WHERE employee_id=? AND work_date LIKE ?").bind(employeeId,`${month}%`).first<Row>(),
      db.prepare("SELECT lb.id,lb.year,lb.entitlement,lb.used,lb.pending,(lb.entitlement-lb.used-lb.pending) AS available,lt.code,lt.name_en,lt.name_ar,lp.carry_forward,lp.max_carry_forward FROM leave_balances lb JOIN leave_types lt ON lt.id=lb.leave_type_id LEFT JOIN leave_policies lp ON lp.leave_type_id=lb.leave_type_id AND lp.country IN ((SELECT country FROM employees WHERE id=?),'Both','KSA & Egypt') AND lp.status='active' WHERE lb.employee_id=? AND lb.year=? ORDER BY lt.id LIMIT 20").bind(employeeId,employeeId,year).all(),
      db.prepare("SELECT COUNT(*)::integer AS total,COUNT(*) FILTER (WHERE status IN ('pending_manager','pending_hr'))::integer AS pending,COUNT(*) FILTER (WHERE status IN ('hr_approved','approved'))::integer AS approved,COUNT(*) FILTER (WHERE status LIKE '%rejected%' OR status='rejected')::integer AS rejected FROM requests WHERE employee_id=? AND EXTRACT(YEAR FROM created_at)=?").bind(employeeId,year).first<Row>(),
      db.prepare("SELECT id,attendance_date,exception_type,status,correction_id FROM attendance_exceptions WHERE employee_id=? AND status IN ('open','correction_requested','pending_manager','pending_hr') ORDER BY attendance_date DESC LIMIT 10").bind(employeeId).all(),
      db.prepare("SELECT id,attendance_date,correction_type,status,current_stage,created_at FROM attendance_corrections WHERE employee_id=? AND status IN ('pending_manager','pending_hr') ORDER BY created_at DESC LIMIT 10").bind(employeeId).all(),
      db.prepare("SELECT id,request_code,type,status,current_stage,from_date,to_date,created_at FROM requests WHERE employee_id=? AND status IN ('pending_manager','pending_hr') ORDER BY created_at DESC LIMIT 10").bind(employeeId).all(),
      ["Super Admin","HR Manager"].includes(user.role_name)&&await permission(db,user,"users","view")?db.prepare("SELECT u.id,u.email,u.status,u.must_change_password,u.last_login_at,u.created_at,r.name AS role_name FROM users u JOIN roles r ON r.id=u.role_id WHERE u.employee_id=?").bind(employeeId).first<Row>():Promise.resolve(null),
      db.prepare("SELECT id,category,expiry_date,CASE WHEN expiry_date<CURRENT_DATE::text THEN 'expired' ELSE 'expiring_soon' END AS status FROM documents WHERE employee_id=? AND status='active' AND expiry_date<=(CURRENT_DATE+30)::text ORDER BY expiry_date LIMIT 10").bind(employeeId).all(),
      db.prepare("SELECT c.code,c.name_en,c.name_ar FROM document_categories c JOIN employees e ON e.id=? WHERE c.status='active' AND c.required_document=1 AND (c.country IS NULL OR c.country=e.country) AND (c.employment_type IS NULL OR c.employment_type=e.employment_type) AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.employee_id=e.id AND d.category=c.code AND d.status='active') ORDER BY c.id LIMIT 10").bind(employeeId).all(),
    ]);
    const policy=profileFieldPolicy({roleName:user.role_name,canEditEmployee:await permission(db,user,"employees","edit"),canViewUsers:await permission(db,user,"users","view"),canEditUsers:await permission(db,user,"users","edit")}),canEdit=policy.canEdit,canViewAccount=policy.canViewAccount&&Boolean(account),canManageAccount=policy.canManageAccount&&Boolean(account);
    const alertRows=[...(exceptions.results as Row[]).map(row=>({kind:"attendance_exception",...row})),...(corrections.results as Row[]).map(row=>({kind:"attendance_correction",...row})),...(pendingRequests.results as Row[]).map(row=>({kind:"pending_request",...row})),...(documentAlerts.results as Row[]).map(row=>({kind:"document_attention",...row})),...(missingDocuments.results as Row[]).map(row=>({kind:"missing_required_document",status:"missing",...row})),...(account&&Number(account.must_change_password)?[{kind:"password_change_required",status:"open"}]:[])];
    const [canViewPerformance,canViewOnboarding,canViewOffboarding,canViewAssets,canViewLearning]=await Promise.all([permission(db,user,"performance","view"),permission(db,user,"onboarding","view"),permission(db,user,"offboarding","view"),permission(db,user,"assets","view"),permission(db,user,"learning","view")]);
    const base={employee,summary:{attendance:{...attendanceSummary,needs_review:exceptions.results.length},leaveBalances:leaveBalances.results,requests:requestCounts},alerts:alertRows,permissions:{canEdit,canViewAccount,canManageAccount,canViewPrivate:policy.canViewPrivate,canViewPerformance,canViewLifecycle:canViewOnboarding||canViewOffboarding,canViewAssets,canViewLearning},account:canViewAccount?account:null,viewerRole:user.role_name,tab};
    if(tab==="overview"){
      const recent=(await db.prepare("SELECT 'request' AS source,id::text AS source_id,type AS action,status,created_at FROM requests WHERE employee_id=? UNION ALL SELECT 'attendance_correction',id::text,correction_type,status,created_at FROM attendance_corrections WHERE employee_id=? ORDER BY created_at DESC LIMIT 8").bind(employeeId,employeeId).all()).results;
      return Response.json({...base,recentActivity:recent});
    }
    if(tab==="attendance"){
      const [rows,logs,allExceptions,allCorrections,actions]=await Promise.all([
        db.prepare("SELECT * FROM daily_attendance WHERE employee_id=? ORDER BY work_date DESC LIMIT ? OFFSET ?").bind(employeeId,limit+1,offset).all(),
        db.prepare("SELECT id,event_at,event_type,source,device,location FROM attendance_logs WHERE employee_id=? ORDER BY event_at DESC LIMIT 200").bind(employeeId).all(),
        db.prepare("SELECT * FROM attendance_exceptions WHERE employee_id=? ORDER BY attendance_date DESC,id DESC LIMIT 100").bind(employeeId).all(),
        db.prepare("SELECT * FROM attendance_corrections WHERE employee_id=? ORDER BY attendance_date DESC,id DESC LIMIT 100").bind(employeeId).all(),
        db.prepare("SELECT a.* FROM attendance_correction_actions a JOIN attendance_corrections c ON c.id=a.correction_id WHERE c.employee_id=? ORDER BY a.created_at,a.id LIMIT 300").bind(employeeId).all(),
      ]);return Response.json({...base,attendance:rows.results.slice(0,limit),attendanceLogs:logs.results,attendanceExceptions:allExceptions.results,attendanceCorrections:allCorrections.results,attendanceCorrectionActions:actions.results,pagination:{page,limit,hasMore:rows.results.length>limit}});
    }
    if(tab==="leave"){
      const [requests,approvals]=await Promise.all([db.prepare("SELECT q.id,q.request_code,q.type,q.from_date,q.to_date,q.requested_days,q.status,q.current_stage,q.reason,q.notes,q.created_at,lt.name_en AS leave_type_name,lt.name_ar AS leave_type_name_ar FROM requests q JOIN leave_types lt ON lt.id=q.leave_type_id WHERE q.employee_id=? ORDER BY q.created_at DESC LIMIT ? OFFSET ?").bind(employeeId,limit+1,offset).all(),db.prepare("SELECT a.* FROM approvals a JOIN requests q ON q.id=a.request_id WHERE q.employee_id=? AND q.leave_type_id IS NOT NULL ORDER BY a.created_at,a.id LIMIT 300").bind(employeeId).all()]);return Response.json({...base,leaveRequests:requests.results.slice(0,limit),requestApprovals:approvals.results,pagination:{page,limit,hasMore:requests.results.length>limit}});
    }
    if(tab==="requests"){
      const [requests,approvals,attendanceRequests,attendanceActions]=await Promise.all([db.prepare("SELECT * FROM requests WHERE employee_id=? ORDER BY created_at DESC LIMIT ? OFFSET ?").bind(employeeId,limit+1,offset).all(),db.prepare("SELECT a.* FROM approvals a JOIN requests q ON q.id=a.request_id WHERE q.employee_id=? ORDER BY a.created_at,a.id LIMIT 300").bind(employeeId).all(),db.prepare("SELECT * FROM attendance_corrections WHERE employee_id=? ORDER BY created_at DESC LIMIT ? OFFSET ?").bind(employeeId,limit+1,offset).all(),db.prepare("SELECT a.* FROM attendance_correction_actions a JOIN attendance_corrections c ON c.id=a.correction_id WHERE c.employee_id=? ORDER BY a.created_at,a.id LIMIT 300").bind(employeeId).all()]);return Response.json({...base,requests:requests.results.slice(0,limit),requestApprovals:approvals.results,attendanceCorrections:attendanceRequests.results.slice(0,limit),attendanceCorrectionActions:attendanceActions.results,pagination:{page,limit,hasMore:requests.results.length>limit||attendanceRequests.results.length>limit}});
    }
    if(tab==="performance"){if(!(await permission(db,user,"performance","view")))throw new Response("Performance access denied",{status:403});const [reviews,goals]=await Promise.all([db.prepare("SELECT r.*,c.name AS cycle_name,c.cycle_type,c.start_date,c.end_date FROM performance_reviews r JOIN performance_cycles c ON c.id=r.cycle_id WHERE r.employee_id=? ORDER BY c.start_date DESC LIMIT ? OFFSET ?").bind(employeeId,limit+1,offset).all(),db.prepare("SELECT g.* FROM performance_goals g JOIN performance_reviews r ON r.id=g.review_id WHERE r.employee_id=? ORDER BY g.review_id,g.id LIMIT 500").bind(employeeId).all()]);return Response.json({...base,performanceReviews:reviews.results.slice(0,limit),performanceGoals:goals.results,pagination:{page,limit,hasMore:reviews.results.length>limit}});}
    if(tab==="lifecycle"){if(!(await permission(db,user,"onboarding","view"))&&!(await permission(db,user,"offboarding","view")))throw new Response("Lifecycle access denied",{status:403});const [lifecycles,tasks]=await Promise.all([db.prepare("SELECT l.*,COUNT(t.id)::int AS task_count,COUNT(t.id) FILTER(WHERE t.status='completed')::int AS completed_tasks,CASE WHEN COUNT(t.id)=0 THEN 0 ELSE ROUND(100.0*COUNT(t.id) FILTER(WHERE t.status='completed')/COUNT(t.id))::int END AS progress FROM employee_lifecycles l LEFT JOIN lifecycle_tasks t ON t.lifecycle_id=l.id WHERE l.employee_id=? GROUP BY l.id ORDER BY l.id DESC LIMIT ? OFFSET ?").bind(employeeId,limit+1,offset).all(),db.prepare("SELECT t.* FROM lifecycle_tasks t JOIN employee_lifecycles l ON l.id=t.lifecycle_id WHERE l.employee_id=? ORDER BY t.due_date,t.id LIMIT 500").bind(employeeId).all()]);return Response.json({...base,lifecycles:lifecycles.results.slice(0,limit),lifecycleTasks:tasks.results,pagination:{page,limit,hasMore:lifecycles.results.length>limit}});}
    if(tab==="assets"){if(!(await permission(db,user,"assets","view")))throw new Response("Asset access denied",{status:403});const rows=await db.prepare("SELECT x.*,a.asset_code,a.category,a.name AS asset_name,a.brand_model,a.serial_number,a.status AS asset_status FROM asset_assignments x JOIN assets a ON a.id=x.asset_id WHERE x.employee_id=? ORDER BY x.assigned_at DESC LIMIT ? OFFSET ?").bind(employeeId,limit+1,offset).all();return Response.json({...base,assetAssignments:rows.results.slice(0,limit),pagination:{page,limit,hasMore:rows.results.length>limit}});}
    if(tab==="learning"){if(!(await permission(db,user,"learning","view")))throw new Response("Learning access denied",{status:403});const rows=await db.prepare("SELECT x.*,c.title AS course_title,c.provider,c.course_type,c.mandatory FROM training_enrollments x JOIN training_courses c ON c.id=x.course_id WHERE x.employee_id=? ORDER BY x.id DESC LIMIT ? OFFSET ?").bind(employeeId,limit+1,offset).all();return Response.json({...base,trainingEnrollments:rows.results.slice(0,limit),pagination:{page,limit,hasMore:rows.results.length>limit}});}
    if(tab==="activity"){
      const domain=(await db.prepare("SELECT 'request' AS source,q.id::text AS source_id,q.type AS action,q.status,q.created_at,NULL::text AS actor FROM requests q WHERE q.employee_id=? UNION ALL SELECT 'attendance_correction',c.id::text,c.correction_type,c.status,c.created_at,NULL FROM attendance_corrections c WHERE c.employee_id=? UNION ALL SELECT 'approval',a.request_id::text,a.action,q.status,a.created_at,u.email FROM approvals a JOIN requests q ON q.id=a.request_id LEFT JOIN users u ON u.id=a.actor_user_id WHERE q.employee_id=? UNION ALL SELECT 'attendance_action',a.correction_id::text,a.action,c.status,a.created_at,u.email FROM attendance_correction_actions a JOIN attendance_corrections c ON c.id=a.correction_id LEFT JOIN users u ON u.id=a.actor_user_id WHERE c.employee_id=? ORDER BY created_at DESC LIMIT ? OFFSET ?").bind(employeeId,employeeId,employeeId,employeeId,limit+1,offset).all()).results;
      const audits=["Super Admin","HR Manager"].includes(user.role_name)?(await db.prepare("SELECT action,module,record_type,record_id,created_at FROM audit_logs WHERE (record_type='employee' AND record_id=?) OR (module='users' AND record_id=(SELECT id::text FROM users WHERE employee_id=? LIMIT 1)) ORDER BY created_at DESC LIMIT 25").bind(String(employeeId),employeeId).all()).results:[];
      return Response.json({...base,activity:[...domain.slice(0,limit),...audits].sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).slice(0,limit),pagination:{page,limit,hasMore:domain.length>limit}});
    }
    if(tab==="account"){if(!canViewAccount)throw new Response("Account details are restricted",{status:403});return Response.json(base);}
    if(tab==="employment")return Response.json(base);
    throw new Response("Unsupported profile tab",{status:400});
  }catch(error){return failure(error);}finally{await db.close();}
}
