import { createDatabase } from "../../../db/postgres";
import { apiFailure, canAccessEmployee, enforceRateLimit, enforceWriteOrigin, requireActor } from "../api-security";
import { audit, body, nextOwner, notifyEmployee, number, required, requireEmployeeScope, requireModule, text } from "../../talent/talent-service";

export async function GET(request:Request){
  const db=createDatabase();
  try{
    const actor=await requireActor(request,db),url=new URL(request.url),employeeId=number(url.searchParams.get("employeeId")),type=text(url.searchParams.get("type"));
    if(employeeId)await requireEmployeeScope(db,actor,employeeId);if(type)await requireModule(db,actor,type,"view");
    const args:unknown[]=[],where:string[]=[];if(employeeId){where.push("l.employee_id=?");args.push(employeeId);}if(type){where.push("l.lifecycle_type=?");args.push(type);}if(actor.roleName==="Employee"){where.push("l.employee_id=?");args.push(actor.employeeId);}const clause=where.length?`WHERE ${where.join(" AND ")}`:"";
    const [templates,lifecycles,tasks,templateTasks,assetAssignments,companySetting,hrApprover]=await Promise.all([
      db.prepare("SELECT t.*,COUNT(x.id)::int AS task_count FROM lifecycle_templates t LEFT JOIN lifecycle_template_tasks x ON x.template_id=t.id WHERE t.status='active' GROUP BY t.id ORDER BY t.lifecycle_type,t.id").all(),
      db.prepare(`SELECT l.*,e.employee_code,e.name_en AS employee_name,e.name_ar AS employee_name_ar,e.work_email,e.start_date AS employment_start_date,e.end_date AS employment_end_date,e.country,e.employment_type,d.name_en AS department_name,d.name_ar AS department_name_ar,(SELECT j.name_en FROM job_titles j WHERE j.id=e.job_title_id) AS job_title_name,(SELECT j.name_ar FROM job_titles j WHERE j.id=e.job_title_id) AS job_title_name_ar,(SELECT m.name_en FROM employees m WHERE m.id=e.manager_id) AS manager_name,(SELECT m.name_ar FROM employees m WHERE m.id=e.manager_id) AS manager_name_ar,(SELECT COALESCE(ce.name_en,cu.email) FROM users cu LEFT JOIN employees ce ON ce.id=cu.employee_id WHERE cu.id=l.completed_by_user_id) AS completed_by_name,(SELECT COALESCE(ce.name_ar,ce.name_en,cu.email) FROM users cu LEFT JOIN employees ce ON ce.id=cu.employee_id WHERE cu.id=l.completed_by_user_id) AS completed_by_name_ar,COUNT(t.id)::int AS task_count,COUNT(t.id) FILTER(WHERE t.status='completed')::int AS completed_tasks,COUNT(t.id) FILTER(WHERE t.status!='completed' AND t.due_date<CURRENT_DATE::text)::int AS overdue_tasks,COUNT(t.id) FILTER(WHERE t.status!='completed' AND t.due_date>=CURRENT_DATE::text AND t.due_date<=(CURRENT_DATE + INTERVAL '7 days')::date::text)::int AS due_soon_tasks,COUNT(t.id) FILTER(WHERE t.required=1 AND t.status!='completed')::int AS required_pending_tasks,(SELECT COUNT(*)::int FROM asset_assignments aa WHERE aa.employee_id=l.employee_id AND aa.returned_at IS NULL) AS unreturned_assets,CASE WHEN COUNT(t.id)=0 THEN 0 ELSE ROUND(100.0*COUNT(t.id) FILTER(WHERE t.status='completed')/COUNT(t.id))::int END AS progress,(SELECT COALESCE(oe.name_en,ou.email) FROM lifecycle_tasks rt LEFT JOIN users ou ON ou.id=rt.owner_user_id LEFT JOIN employees oe ON oe.id=ou.employee_id WHERE rt.lifecycle_id=l.id AND rt.status!='completed' ORDER BY rt.due_date NULLS LAST,rt.id LIMIT 1) AS responsible_name,(SELECT COALESCE(oe.name_ar,oe.name_en,ou.email) FROM lifecycle_tasks rt LEFT JOIN users ou ON ou.id=rt.owner_user_id LEFT JOIN employees oe ON oe.id=ou.employee_id WHERE rt.lifecycle_id=l.id AND rt.status!='completed' ORDER BY rt.due_date NULLS LAST,rt.id LIMIT 1) AS responsible_name_ar FROM employee_lifecycles l JOIN employees e ON e.id=l.employee_id LEFT JOIN departments d ON d.id=e.department_id LEFT JOIN lifecycle_tasks t ON t.lifecycle_id=l.id ${clause} GROUP BY l.id,e.id,d.id ORDER BY l.id DESC LIMIT 1000`).bind(...args).all(),
      db.prepare(`SELECT t.*,oe.name_en AS owner_name,oe.name_ar AS owner_name_ar,r.name AS owner_role_name FROM lifecycle_tasks t JOIN employee_lifecycles l ON l.id=t.lifecycle_id LEFT JOIN users u ON u.id=t.owner_user_id LEFT JOIN employees oe ON oe.id=u.employee_id LEFT JOIN roles r ON r.id=u.role_id ${clause} ORDER BY t.due_date,t.id LIMIT 5000`).bind(...args).all(),
      db.prepare("SELECT x.*,t.lifecycle_type,t.name AS template_name FROM lifecycle_template_tasks x JOIN lifecycle_templates t ON t.id=x.template_id WHERE t.status='active' ORDER BY t.lifecycle_type,t.id,x.sort_order,x.id").all(),
      db.prepare("SELECT x.id AS assignment_id,x.asset_id,x.employee_id,x.assigned_at,x.assigned_condition,x.assigned_notes,x.returned_at,x.return_condition,x.return_notes,a.asset_code,a.category,a.name AS asset_name,a.brand_model,a.serial_number,a.status AS asset_status,a.asset_condition FROM asset_assignments x JOIN assets a ON a.id=x.asset_id ORDER BY x.id DESC LIMIT 5000").all(),
      db.prepare("SELECT value_json FROM system_settings WHERE setting_key='company'").first<{value_json:string}>(),
      db.prepare("SELECT e.name_en,e.name_ar FROM employees e LEFT JOIN job_titles j ON j.id=e.job_title_id LEFT JOIN departments d ON d.id=e.department_id WHERE e.employment_status='active' AND (j.name_en='HR Manager' OR j.name_ar='مدير إدارة الموارد البشرية' OR d.name_en='Human Resources' OR d.name_ar='إدارة الموارد البشرية') ORDER BY CASE WHEN j.name_en='HR Manager' OR j.name_ar='مدير إدارة الموارد البشرية' THEN 0 ELSE 1 END,e.id LIMIT 1").first<{name_en:string;name_ar:string}>(),
    ]);
    const taskRows=tasks.results as Record<string,unknown>[];
    let visibleLifecycles=(lifecycles.results as Record<string,unknown>[]).map(lifecycle=>{
      const completedBy=String(lifecycle.completed_by_name||"");
      const responsible=String(lifecycle.responsible_name||"");
      const responsibleTask=taskRows.find(task=>Number(task.lifecycle_id)===Number(lifecycle.id)&&task.status!=="completed");
      const role=String(responsibleTask?.owner_role_name||"");
      const roleNames:Record<string,string>={"Super Admin":"System Administrator","HR Manager":"Human Resources","Department Manager":"Department Manager",Employee:"Employee"};
      const roleNamesAr:Record<string,string>={"Super Admin":"مسؤول النظام","HR Manager":"إدارة الموارد البشرية","Department Manager":"مدير الإدارة",Employee:"الموظف"};
      const roleName=roleNames[role]||"Not assigned",roleNameAr=roleNamesAr[role]||"غير محدد";
      const safeCompletedBy=completedBy&&!completedBy.includes("@")?{completed_by_name:lifecycle.completed_by_name,completed_by_name_ar:lifecycle.completed_by_name_ar}:{completed_by_name:hrApprover?.name_en||"Human Resources",completed_by_name_ar:hrApprover?.name_ar||hrApprover?.name_en||"إدارة الموارد البشرية"};
      const safeResponsible=responsible&&!responsible.includes("@")?{responsible_name:lifecycle.responsible_name,responsible_name_ar:lifecycle.responsible_name_ar}:{responsible_name:responsibleTask?.owner_name||(["Super Admin","HR Manager"].includes(role)&&hrApprover?.name_en)||roleName,responsible_name_ar:responsibleTask?.owner_name_ar||responsibleTask?.owner_name||(["Super Admin","HR Manager"].includes(role)&&(hrApprover?.name_ar||hrApprover?.name_en))||roleNameAr};
      return {...lifecycle,...safeCompletedBy,...safeResponsible};
    });
    if(!["Super Admin","HR Manager"].includes(actor.roleName)){const scoped=[] as Record<string,unknown>[];for(const lifecycle of visibleLifecycles)if(await canAccessEmployee(db,actor,Number(lifecycle.employee_id)))scoped.push(lifecycle);visibleLifecycles=scoped;}
    const visibleIds=new Set(visibleLifecycles.map(lifecycle=>Number(lifecycle.id))),visibleEmployeeIds=new Set(visibleLifecycles.map(lifecycle=>Number(lifecycle.employee_id)));
    const visibleTasks=taskRows.filter(task=>visibleIds.has(Number(task.lifecycle_id))).map(task=>{
      const ownerName=String(task.owner_name||"");
      if(ownerName&&!ownerName.includes("@"))return task;
      if(["Super Admin","HR Manager"].includes(String(task.owner_role_name))&&hrApprover)return {...task,owner_name:hrApprover.name_en,owner_name_ar:hrApprover.name_ar||hrApprover.name_en};
      return task;
    });
    const visibleAssets=(assetAssignments.results as Record<string,unknown>[]).filter(asset=>visibleEmployeeIds.has(Number(asset.employee_id)));let company:Record<string,unknown>={};try{company=JSON.parse(companySetting?.value_json||"{}");}catch{company={};}
    return Response.json({templates:templates.results,templateTasks:templateTasks.results,lifecycles:visibleLifecycles,tasks:visibleTasks,assetAssignments:visibleAssets,company,actor:{id:actor.id,roleName:actor.roleName,employeeId:actor.employeeId}});
  }catch(error){return apiFailure(error,"Unable to load employee lifecycle");}finally{await db.close();}
}

export async function POST(request:Request){const db=createDatabase();try{enforceWriteOrigin(request);const actor=await requireActor(request,db);await enforceRateLimit(db,request,"lifecycle-write",180,60,actor.id);const input=await body(request),action=required(input.action,"action");
  if(action==="create_template"){const type=required(input.lifecycleType,"lifecycle type");await requireModule(db,actor,type,"manage_settings");if(!["onboarding","offboarding"].includes(type))throw new Response("Invalid lifecycle type",{status:400});const row=await db.prepare("INSERT INTO lifecycle_templates(name,lifecycle_type,status,created_by_user_id,created_at,updated_at) VALUES (?,?,'active',?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) RETURNING id").bind(required(input.name,"name"),type,actor.id).first<{id:number}>();const tasks=Array.isArray(input.tasks)?input.tasks as Record<string,unknown>[]:[];for(let i=0;i<tasks.length;i++){const task=tasks[i];await db.prepare("INSERT INTO lifecycle_template_tasks(template_id,title,owner_type,due_offset_days,required,sort_order) VALUES (?,?,?,?,?,?)").bind(row!.id,required(task.title,"task title"),text(task.ownerType)||"hr",Number(task.dueOffsetDays)||0,task.required===false?0:1,i).run();}await audit(db,actor,"create",type,"lifecycle_template",row!.id,{name:text(input.name),taskCount:tasks.length});return Response.json({ok:true,id:row!.id},{status:201});}
  if(action==="save_template_task"){
    const taskId=number(input.taskId),templateId=number(input.templateId),template=await db.prepare("SELECT id,lifecycle_type FROM lifecycle_templates WHERE id=? AND status='active'").bind(templateId).first<{id:number;lifecycle_type:string}>();
    if(!template)throw new Response("Lifecycle template not found",{status:404});await requireModule(db,actor,template.lifecycle_type,"manage_settings");const title=required(input.title,"task title"),ownerType=text(input.ownerType)||"hr",dueOffsetDays=Math.max(-365,Math.min(365,Math.round(Number(input.dueOffsetDays)||0))),isRequired=input.required===false||input.required===0?0:1;if(!["hr","manager","employee"].includes(ownerType))throw new Response("Invalid task owner type",{status:400});
    if(taskId){const existing=await db.prepare("SELECT id FROM lifecycle_template_tasks WHERE id=? AND template_id=?").bind(taskId,templateId).first<{id:number}>();if(!existing)throw new Response("Template task not found",{status:404});await db.prepare("UPDATE lifecycle_template_tasks SET title=?,owner_type=?,due_offset_days=?,required=? WHERE id=?").bind(title,ownerType,dueOffsetDays,isRequired,taskId).run();await audit(db,actor,"update",template.lifecycle_type,"lifecycle_template_task",taskId,{templateId,title,ownerType,dueOffsetDays,required:Boolean(isRequired)});return Response.json({ok:true,id:taskId});}
    const order=await db.prepare("SELECT COALESCE(MAX(sort_order),-1)::int+1 AS value FROM lifecycle_template_tasks WHERE template_id=?").bind(templateId).first<{value:number}>(),row=await db.prepare("INSERT INTO lifecycle_template_tasks(template_id,title,owner_type,due_offset_days,required,sort_order) VALUES (?,?,?,?,?,?) RETURNING id").bind(templateId,title,ownerType,dueOffsetDays,isRequired,Number(order?.value)||0).first<{id:number}>();await audit(db,actor,"create",template.lifecycle_type,"lifecycle_template_task",row!.id,{templateId,title,ownerType,dueOffsetDays,required:Boolean(isRequired)});return Response.json({ok:true,id:row!.id},{status:201});
  }
  if(action==="delete_template_task"){
    const taskId=number(input.taskId),task=await db.prepare("SELECT x.id,x.template_id,t.lifecycle_type FROM lifecycle_template_tasks x JOIN lifecycle_templates t ON t.id=x.template_id WHERE x.id=? AND t.status='active'").bind(taskId).first<{id:number;template_id:number;lifecycle_type:string}>();if(!task)throw new Response("Template task not found",{status:404});await requireModule(db,actor,task.lifecycle_type,"manage_settings");await db.prepare("DELETE FROM lifecycle_template_tasks WHERE id=?").bind(taskId).run();await audit(db,actor,"delete",task.lifecycle_type,"lifecycle_template_task",taskId,{templateId:task.template_id});return Response.json({ok:true});
  }
  if(action==="start"){
    const type=required(input.lifecycleType,"lifecycle type");
    await requireModule(db,actor,type,"create");
    const employeeId=number(input.employeeId);
    await requireEmployeeScope(db,actor,employeeId);
    const templateId=number(input.templateId),template=await db.prepare("SELECT id FROM lifecycle_templates WHERE id=? AND lifecycle_type=? AND status='active'").bind(templateId,type).first();
    if(!template)throw new Response("Lifecycle template not found",{status:404});
    const existing=await db.prepare("SELECT id FROM employee_lifecycles WHERE employee_id=? AND lifecycle_type=? AND status IN ('pending','in_progress') ORDER BY id DESC LIMIT 1").bind(employeeId,type).first<{id:number}>();
    if(existing)return Response.json({error:"Active lifecycle already exists for this employee",code:"ACTIVE_LIFECYCLE_EXISTS",existingLifecycleId:existing.id},{status:409});
    const baseDate=type==="offboarding"?required(input.lastWorkingDate,"last working date"):(text(input.startDate)||new Date().toISOString().slice(0,10));
    const lifecycle=await db.transaction(async tx=>{
      const row=await tx.prepare("INSERT INTO employee_lifecycles(employee_id,lifecycle_type,template_id,status,reason_type,last_working_date,notes,deactivate_account_on_completion,started_by_user_id,created_at,updated_at) VALUES (?,?,?,'in_progress',?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT (employee_id,lifecycle_type) WHERE status IN ('pending','in_progress') DO NOTHING RETURNING id").bind(employeeId,type,templateId,text(input.reasonType)||null,type==="offboarding"?baseDate:null,text(input.notes)||null,input.deactivateAccountOnCompletion===false?0:1,actor.id).first<{id:number}>();
      if(!row)throw new Response("Active lifecycle already exists for this employee",{status:409});
      const tasks=(await tx.prepare("SELECT * FROM lifecycle_template_tasks WHERE template_id=? ORDER BY sort_order").bind(templateId).all()).results;
      for(const task of tasks){const owner=await nextOwner(tx,employeeId,String(task.owner_type));await tx.prepare("INSERT INTO lifecycle_tasks(lifecycle_id,title,owner_user_id,employee_id,due_date,status,required,created_at,updated_at) VALUES (?,?,?,?,(?::date + (? * INTERVAL '1 day'))::date::text,'pending',?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)").bind(row.id,task.title,owner?.id||null,employeeId,baseDate,task.due_offset_days,task.required).run();}
      return {id:row.id,tasks};
    });
    await notifyEmployee(db,employeeId,{type,title:`${type}_started`,entityType:"employee_lifecycle",entityId:lifecycle.id,path:"lifecycle",key:`${type}:${lifecycle.id}:started`});
    await audit(db,actor,"start",type,"employee_lifecycle",lifecycle.id,{employeeId,taskCount:lifecycle.tasks.length});
    return Response.json({ok:true,id:lifecycle.id,taskCount:lifecycle.tasks.length},{status:201});
  }
  if(action==="update_task"){const id=number(input.taskId),task=await db.prepare("SELECT t.*,l.lifecycle_type,l.status AS lifecycle_status FROM lifecycle_tasks t JOIN employee_lifecycles l ON l.id=t.lifecycle_id WHERE t.id=? FOR UPDATE OF t").bind(id).first<Record<string,unknown>>();if(!task)throw new Response("Task not found",{status:404});if(task.lifecycle_status!=="in_progress")throw new Response("Lifecycle is not active",{status:409});const isOwner=Number(task.owner_user_id)===actor.id;if(!isOwner){await requireModule(db,actor,String(task.lifecycle_type),"edit");await requireEmployeeScope(db,actor,Number(task.employee_id));}const status=required(input.status,"status");if(!["pending","in_progress","completed","blocked"].includes(status))throw new Response("Invalid task status",{status:400});await db.prepare("UPDATE lifecycle_tasks SET status=?,notes=?,completed_by_user_id=CASE WHEN ?='completed' THEN ?::integer ELSE NULL END,completed_at=CASE WHEN ?='completed' THEN CURRENT_TIMESTAMP ELSE NULL END,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(status,text(input.notes)||task.notes||null,status,actor.id,status,id).run();await audit(db,actor,"task_update",String(task.lifecycle_type),"lifecycle_task",id,{status});return Response.json({ok:true});}
  if(action==="return_asset"){
    const lifecycleId=number(input.lifecycleId),assetId=number(input.assetId);await requireModule(db,actor,"offboarding","edit");await requireModule(db,actor,"assets","edit");const lifecycle=await db.prepare("SELECT id,employee_id,status,lifecycle_type FROM employee_lifecycles WHERE id=? FOR UPDATE").bind(lifecycleId).first<{id:number;employee_id:number;status:string;lifecycle_type:string}>();if(!lifecycle)throw new Response("Lifecycle not found",{status:404});if(lifecycle.lifecycle_type!=="offboarding"||lifecycle.status!=="in_progress")throw new Response("Asset return is only available during active offboarding",{status:409});await requireEmployeeScope(db,actor,lifecycle.employee_id);const condition=text(input.condition)||"good",nextStatus=text(input.nextStatus)||"available";if(!["good","fair","damaged","lost"].includes(condition))throw new Response("Invalid return condition",{status:400});if(!["available","maintenance","lost","retired"].includes(nextStatus))throw new Response("Invalid returned asset status",{status:400});const assignment=await db.transaction(async tx=>{const row=await tx.prepare("SELECT x.id,x.employee_id FROM asset_assignments x WHERE x.asset_id=? AND x.employee_id=? AND x.returned_at IS NULL FOR UPDATE").bind(assetId,lifecycle.employee_id).first<{id:number;employee_id:number}>();if(!row)throw new Response("This asset is not currently assigned to the employee",{status:409});await tx.prepare("UPDATE asset_assignments SET returned_at=CURRENT_TIMESTAMP,returned_by_user_id=?,return_condition=?,return_notes=? WHERE id=? AND returned_at IS NULL").bind(actor.id,condition,text(input.notes)||null,row.id).run();await tx.prepare("UPDATE assets SET status=?,asset_condition=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(nextStatus,condition,assetId).run();return row;});await notifyEmployee(db,lifecycle.employee_id,{type:"assets",title:"asset_returned",entityType:"asset",entityId:assetId,path:"assets",key:`asset:${assetId}:returned:${assignment.id}`});await audit(db,actor,"return","assets","asset",assetId,{employeeId:lifecycle.employee_id,assignmentId:assignment.id,lifecycleId,condition,nextStatus});return Response.json({ok:true});
  }
  if(action==="complete"){const id=number(input.lifecycleId),row=await db.prepare("SELECT * FROM employee_lifecycles WHERE id=? FOR UPDATE").bind(id).first<Record<string,unknown>>();if(!row)throw new Response("Lifecycle not found",{status:404});await requireModule(db,actor,String(row.lifecycle_type),"approve");await requireEmployeeScope(db,actor,Number(row.employee_id));if(row.status==="completed")throw new Response("Lifecycle already completed",{status:409});const remaining=await db.prepare("SELECT COUNT(*)::int AS count FROM lifecycle_tasks WHERE lifecycle_id=? AND required=1 AND status!='completed'").bind(id).first<{count:number}>();if(Number(remaining?.count))throw new Response("Required lifecycle tasks remain incomplete",{status:409});if(row.lifecycle_type==="offboarding"){const assets=await db.prepare("SELECT COUNT(*)::int AS count FROM asset_assignments WHERE employee_id=? AND returned_at IS NULL").bind(row.employee_id).first<{count:number}>();if(Number(assets?.count))throw new Response("Employee has unreturned assets",{status:409});}await db.transaction(async tx=>{await tx.prepare("UPDATE employee_lifecycles SET status='completed',exit_interview=?,completed_by_user_id=?,completed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status!='completed'").bind(text(input.exitInterview)||row.exit_interview||null,actor.id,id).run();if(row.lifecycle_type==="offboarding"){await tx.prepare("UPDATE employees SET employment_status='inactive',end_date=COALESCE(?,end_date),updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(row.last_working_date,row.employee_id).run();if(Number(row.deactivate_account_on_completion))await tx.prepare("UPDATE users SET status='disabled',session_version=session_version+1,updated_at=CURRENT_TIMESTAMP WHERE employee_id=?").bind(row.employee_id).run();}});await audit(db,actor,"complete",String(row.lifecycle_type),"employee_lifecycle",id,{employeeId:row.employee_id,accountDeactivated:Boolean(row.deactivate_account_on_completion)});return Response.json({ok:true});}
  throw new Response("Unsupported lifecycle action",{status:400});
}catch(error){return apiFailure(error,"Lifecycle action failed");}finally{await db.close();}}
