import { createDatabase } from "../../../db/postgres";
import { apiFailure, enforceRateLimit, enforceWriteOrigin, requireActor } from "../api-security";
import { audit, body, notifyEmployee, number, required, requireEmployeeScope, requireModule, text, transition } from "../../talent/talent-service";

const moves:Record<string,string[]>={assigned:["in_progress","completed","failed","cancelled"],in_progress:["completed","failed","cancelled"],completed:[],failed:[],cancelled:[]};
export async function GET(request:Request){
  const db=createDatabase();
  try{
    const actor=await requireActor(request,db);await requireModule(db,actor,"learning","view");
    const url=new URL(request.url),employeeId=number(url.searchParams.get("employeeId"));if(employeeId)await requireEmployeeScope(db,actor,employeeId);
    let courseScope="",enrollmentScope="",scopeArgs:(number|null)[]=[];
    const exactEmployeeId=employeeId||(actor.roleName==="Employee"?actor.employeeId:0);
    if(exactEmployeeId){courseScope="AND e.employee_id=?";enrollmentScope="WHERE x.employee_id=?";scopeArgs=[exactEmployeeId];}
    else if(actor.roleName==="Department Manager"&&actor.employeeId){
      const managedScope="WITH RECURSIVE managed AS (SELECT id FROM departments WHERE manager_employee_id=? AND status!='deleted' UNION ALL SELECT d.id FROM departments d JOIN managed m ON d.parent_id=m.id WHERE d.status!='deleted') SELECT emp.id FROM employees emp WHERE emp.employment_status!='deleted' AND (emp.department_id IN (SELECT id FROM managed) OR emp.id=?)";
      courseScope=`AND e.employee_id IN (${managedScope})`;enrollmentScope=`WHERE x.employee_id IN (${managedScope})`;scopeArgs=[actor.employeeId,actor.employeeId];
    }
    const scoped=Boolean(courseScope);
    const courseSql=`SELECT c.*,COUNT(e.id)::int AS enrollment_count,COUNT(e.id) FILTER(WHERE e.status='assigned')::int AS assigned_count,COUNT(e.id) FILTER(WHERE e.status='in_progress')::int AS in_progress_count,COUNT(e.id) FILTER(WHERE e.status='completed')::int AS completion_count,COUNT(e.id) FILTER(WHERE e.status='failed')::int AS failed_count,COUNT(e.id) FILTER(WHERE e.status IN ('assigned','in_progress') AND e.due_date<CURRENT_DATE::text)::int AS overdue_count,CASE WHEN COUNT(e.id)=0 THEN 0 ELSE ROUND(100.0*COUNT(e.id) FILTER(WHERE e.status='completed')/COUNT(e.id))::int END AS completion_rate FROM training_courses c LEFT JOIN training_enrollments e ON e.course_id=c.id ${courseScope} GROUP BY c.id ${scoped?"HAVING COUNT(e.id)>0":""} ORDER BY CASE WHEN c.status='active' THEN 0 ELSE 1 END,c.start_date DESC NULLS LAST,c.id DESC LIMIT 1000`;
    const enrollmentSql=`SELECT x.*,c.title AS course_title,c.provider,c.course_type,c.mandatory,c.start_date AS course_start_date,c.end_date AS course_end_date,c.validity_months,e.employee_code,e.name_en AS employee_name,e.name_ar AS employee_name_ar,d.name_en AS department_name,d.name_ar AS department_name_ar FROM training_enrollments x JOIN training_courses c ON c.id=x.course_id JOIN employees e ON e.id=x.employee_id LEFT JOIN departments d ON d.id=e.department_id ${enrollmentScope} ORDER BY CASE WHEN x.status IN ('assigned','in_progress') AND x.due_date<CURRENT_DATE::text THEN 0 WHEN x.status IN ('assigned','in_progress') THEN 1 ELSE 2 END,x.due_date NULLS LAST,x.id DESC LIMIT 5000`;
    const [courses,enrollments]=await Promise.all([db.prepare(courseSql).bind(...scopeArgs).all(),db.prepare(enrollmentSql).bind(...scopeArgs).all()]);
    return Response.json({courses:courses.results,enrollments:enrollments.results,actor:{id:actor.id,roleName:actor.roleName,employeeId:actor.employeeId}});
  }catch(error){return apiFailure(error,"Unable to load learning");}finally{await db.close();}
}
export async function POST(request:Request){const db=createDatabase();try{enforceWriteOrigin(request);const actor=await requireActor(request,db);await enforceRateLimit(db,request,"learning-write",180,60,actor.id);const input=await body(request),action=required(input.action,"action");
  if(action==="create_course"){await requireModule(db,actor,"learning","create");const row=await db.prepare("INSERT INTO training_courses(title,provider,course_type,description,start_date,end_date,status,mandatory,validity_months,created_by_user_id,created_at,updated_at) VALUES (?,?,?,?,?,?,'active',?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) RETURNING id").bind(required(input.title,"title"),text(input.provider)||null,required(input.courseType,"course type"),text(input.description)||null,text(input.startDate)||null,text(input.endDate)||null,input.mandatory?1:0,number(input.validityMonths)||null,actor.id).first<{id:number}>();await audit(db,actor,"create","learning","course",row!.id,{title:text(input.title),mandatory:Boolean(input.mandatory)});return Response.json({ok:true,id:row!.id},{status:201});}
  if(action==="enroll"){await requireModule(db,actor,"learning","create");const employeeId=number(input.employeeId);await requireEmployeeScope(db,actor,employeeId);const courseId=number(input.courseId),course=await db.prepare("SELECT id FROM training_courses WHERE id=? AND status='active'").bind(courseId).first();if(!course)throw new Response("Active course not found",{status:404});const row=await db.prepare("INSERT INTO training_enrollments(course_id,employee_id,status,due_date,assigned_by_user_id,created_at,updated_at) VALUES (?,?,'assigned',?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT(course_id,employee_id) DO NOTHING RETURNING id").bind(courseId,employeeId,text(input.dueDate)||null,actor.id).first<{id:number}>();if(!row)throw new Response("Employee already enrolled",{status:409});await notifyEmployee(db,employeeId,{type:"learning",title:"training_assigned",message:text(input.dueDate),entityType:"training_enrollment",entityId:row.id,path:"learning",key:`training:${row.id}:assigned`});await audit(db,actor,"enroll","learning","training_enrollment",row.id,{courseId,employeeId});return Response.json({ok:true,id:row.id},{status:201});}
  if(action==="update_enrollment"){const id=number(input.enrollmentId),row=await db.prepare("SELECT * FROM training_enrollments WHERE id=? FOR UPDATE").bind(id).first<Record<string,unknown>>();if(!row)throw new Response("Enrollment not found",{status:404});await requireEmployeeScope(db,actor,Number(row.employee_id));const next=required(input.status,"status");transition(String(row.status),next,moves,"training transition");if(["completed","failed"].includes(next)&&actor.employeeId===Number(row.employee_id)&&actor.roleName==="Employee")throw new Response("Completion requires manager or HR verification",{status:403});const completion=next==="completed"?(text(input.completionDate)||new Date().toISOString().slice(0,10)):null;let expiry=text(input.certificateExpiry)||null;if(next==="completed"&&!expiry){const course=await db.prepare("SELECT validity_months FROM training_courses WHERE id=?").bind(row.course_id).first<{validity_months:number|null}>();if(Number(course?.validity_months))expiry=(await db.prepare("SELECT (?::date + (? * INTERVAL '1 month'))::date::text AS expiry").bind(completion,course!.validity_months).first<{expiry:string}>())?.expiry||null;}await db.prepare("UPDATE training_enrollments SET status=?,completion_date=?,score=?,certificate_document_id=?,certificate_expiry=?,completed_by_user_id=CASE WHEN ?='completed' THEN ?::integer ELSE NULL END,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(next,completion,Number(input.score)||null,number(input.certificateDocumentId)||null,expiry,next,actor.id,id).run();await notifyEmployee(db,Number(row.employee_id),{type:"learning",title:next==="completed"?"training_completed":"training_updated",message:next,entityType:"training_enrollment",entityId:id,path:"learning",key:`training:${id}:${next}`});await audit(db,actor,"status_change","learning","training_enrollment",id,{from:row.status,to:next,expiry});return Response.json({ok:true,certificateExpiry:expiry});}
  throw new Response("Unsupported learning action",{status:400});
}catch(error){return apiFailure(error,"Learning action failed");}finally{await db.close();}}
