DELETE FROM approvals WHERE request_id IN (SELECT id FROM requests WHERE employee_id IN (SELECT id FROM employees WHERE employee_code IN ('EMP-00001','EMP-00002','EMP-00003','EMP-00004')));
--> statement-breakpoint
DELETE FROM requests WHERE employee_id IN (SELECT id FROM employees WHERE employee_code IN ('EMP-00001','EMP-00002','EMP-00003','EMP-00004'));
--> statement-breakpoint
DELETE FROM attendance_logs WHERE employee_id IN (SELECT id FROM employees WHERE employee_code IN ('EMP-00001','EMP-00002','EMP-00003','EMP-00004'));
--> statement-breakpoint
DELETE FROM daily_attendance WHERE employee_id IN (SELECT id FROM employees WHERE employee_code IN ('EMP-00001','EMP-00002','EMP-00003','EMP-00004'));
--> statement-breakpoint
DELETE FROM leave_balances WHERE employee_id IN (SELECT id FROM employees WHERE employee_code IN ('EMP-00001','EMP-00002','EMP-00003','EMP-00004'));
--> statement-breakpoint
DELETE FROM documents WHERE employee_id IN (SELECT id FROM employees WHERE employee_code IN ('EMP-00001','EMP-00002','EMP-00003','EMP-00004'));
--> statement-breakpoint
DELETE FROM users WHERE employee_id IN (SELECT id FROM employees WHERE employee_code IN ('EMP-00001','EMP-00002','EMP-00003','EMP-00004'));
--> statement-breakpoint
DELETE FROM employees WHERE employee_code IN ('EMP-00001','EMP-00002','EMP-00003','EMP-00004');
--> statement-breakpoint
DELETE FROM job_titles WHERE name_en IN ('HR Specialist','Senior Frontend Engineer','CS Team Lead','Account Executive');
--> statement-breakpoint
DELETE FROM departments WHERE name_en IN ('People & Culture','Engineering','Customer Success','Sales') AND NOT EXISTS (SELECT 1 FROM employees WHERE employees.department_id=departments.id);
--> statement-breakpoint
INSERT OR IGNORE INTO roles (name,description,is_system,created_at,updated_at) VALUES ('Employee','Employee self-service role',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO leave_types (name_en,name_ar,paid,attachment_required,manager_approval,hr_approval,status,created_at,updated_at) VALUES ('Annual leave','إجازة سنوية',1,0,1,1,'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT INTO departments (name_en,name_ar,status,created_at,updated_at) SELECT 'Software Development','برمجة','active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM departments WHERE trim(name_ar)=trim('برمجة'));
--> statement-breakpoint
INSERT INTO departments (name_en,name_ar,status,created_at,updated_at) SELECT 'Sales','المبيعات','active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM departments WHERE trim(name_ar)=trim('المبيعات'));
--> statement-breakpoint
INSERT INTO departments (name_en,name_ar,status,created_at,updated_at) SELECT 'Human Resources','إدارة الموارد البشرية','active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM departments WHERE trim(name_ar)=trim('إدارة الموارد البشرية'));
--> statement-breakpoint
INSERT INTO departments (name_en,name_ar,status,created_at,updated_at) SELECT 'Business Development','تطوير الاعمال','active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM departments WHERE trim(name_ar)=trim('تطوير الاعمال'));
--> statement-breakpoint
INSERT INTO departments (name_en,name_ar,status,created_at,updated_at) SELECT 'Koon Agency','وكالة كون','active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM departments WHERE trim(name_ar)=trim('وكالة كون'));
--> statement-breakpoint
INSERT INTO departments (name_en,name_ar,status,created_at,updated_at) SELECT 'IT Systems','نظم','active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM departments WHERE trim(name_ar)=trim('نظم'));
--> statement-breakpoint
INSERT INTO departments (name_en,name_ar,status,created_at,updated_at) SELECT 'Data Analytics','محلل بيانات','active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM departments WHERE trim(name_ar)=trim('محلل بيانات'));
--> statement-breakpoint
INSERT INTO departments (name_en,name_ar,status,created_at,updated_at) SELECT 'Technology','التقنية','active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM departments WHERE trim(name_ar)=trim('التقنية'));
--> statement-breakpoint
INSERT INTO departments (name_en,name_ar,status,created_at,updated_at) SELECT 'Customer Service','خدمة عملاء','active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM departments WHERE trim(name_ar)=trim('خدمة عملاء'));
--> statement-breakpoint
INSERT INTO departments (name_en,name_ar,status,created_at,updated_at) SELECT 'Contracts','التعاقدات','active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM departments WHERE trim(name_ar)=trim('التعاقدات'));
--> statement-breakpoint
INSERT INTO departments (name_en,name_ar,status,created_at,updated_at) SELECT 'UX/UI','UX/UI','active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM departments WHERE trim(name_ar)=trim('UX/UI'));
--> statement-breakpoint
INSERT INTO departments (name_en,name_ar,status,created_at,updated_at) SELECT 'Accounting','الحسابات','active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM departments WHERE trim(name_ar)=trim('الحسابات'));
--> statement-breakpoint
INSERT INTO departments (name_en,name_ar,status,created_at,updated_at) SELECT 'Asus Merchants','أسس للتجار','active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM departments WHERE trim(name_ar)=trim('أسس للتجار'));
--> statement-breakpoint
INSERT INTO departments (name_en,name_ar,status,created_at,updated_at) SELECT 'Managing Director Office','العضو المنتدب','active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM departments WHERE trim(name_ar)=trim('العضو المنتدب'));
--> statement-breakpoint
INSERT INTO job_titles (name_en,name_ar,department_id,status,created_at,updated_at) SELECT 'Software Developer','مطور برامج',(SELECT id FROM departments WHERE trim(name_ar)=trim('برمجة') LIMIT 1),'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM job_titles WHERE trim(name_ar)=trim('مطور برامج') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('برمجة') LIMIT 1));
--> statement-breakpoint
INSERT INTO job_titles (name_en,name_ar,department_id,status,created_at,updated_at) SELECT 'Support and Sales Manager','مدير الدعم و المبيعات',(SELECT id FROM departments WHERE trim(name_ar)=trim('المبيعات') LIMIT 1),'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM job_titles WHERE trim(name_ar)=trim('مدير الدعم و المبيعات') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('المبيعات') LIMIT 1));
--> statement-breakpoint
INSERT INTO job_titles (name_en,name_ar,department_id,status,created_at,updated_at) SELECT 'HR Manager','مدير إدارة الموارد البشرية',(SELECT id FROM departments WHERE trim(name_ar)=trim('إدارة الموارد البشرية') LIMIT 1),'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM job_titles WHERE trim(name_ar)=trim('مدير إدارة الموارد البشرية') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('إدارة الموارد البشرية') LIMIT 1));
--> statement-breakpoint
INSERT INTO job_titles (name_en,name_ar,department_id,status,created_at,updated_at) SELECT 'marketing manager','marketing manager',(SELECT id FROM departments WHERE trim(name_ar)=trim('تطوير الاعمال') LIMIT 1),'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM job_titles WHERE trim(name_ar)=trim('marketing manager') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('تطوير الاعمال') LIMIT 1));
--> statement-breakpoint
INSERT INTO job_titles (name_en,name_ar,department_id,status,created_at,updated_at) SELECT 'Smart Line Manager','مدير سمارت لين',(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1),'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM job_titles WHERE trim(name_ar)=trim('مدير سمارت لين') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1));
--> statement-breakpoint
INSERT INTO job_titles (name_en,name_ar,department_id,status,created_at,updated_at) SELECT 'Technical Support','دعم التقنى',(SELECT id FROM departments WHERE trim(name_ar)=trim('نظم') LIMIT 1),'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM job_titles WHERE trim(name_ar)=trim('دعم التقنى') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('نظم') LIMIT 1));
--> statement-breakpoint
INSERT INTO job_titles (name_en,name_ar,department_id,status,created_at,updated_at) SELECT 'Digital Marketing Specialist','Digital Marketing Specialist',(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1),'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM job_titles WHERE trim(name_ar)=trim('Digital Marketing Specialist') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1));
--> statement-breakpoint
INSERT INTO job_titles (name_en,name_ar,department_id,status,created_at,updated_at) SELECT 'Data Analyst','محلل بيانات',(SELECT id FROM departments WHERE trim(name_ar)=trim('محلل بيانات') LIMIT 1),'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM job_titles WHERE trim(name_ar)=trim('محلل بيانات') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('محلل بيانات') LIMIT 1));
--> statement-breakpoint
INSERT INTO job_titles (name_en,name_ar,department_id,status,created_at,updated_at) SELECT 'Sales Representative','مندوب البيع',(SELECT id FROM departments WHERE trim(name_ar)=trim('المبيعات') LIMIT 1),'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM job_titles WHERE trim(name_ar)=trim('مندوب البيع') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('المبيعات') LIMIT 1));
--> statement-breakpoint
INSERT INTO job_titles (name_en,name_ar,department_id,status,created_at,updated_at) SELECT 'Office boy','Office boy',(SELECT id FROM departments WHERE trim(name_ar)=trim('إدارة الموارد البشرية') LIMIT 1),'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM job_titles WHERE trim(name_ar)=trim('Office boy') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('إدارة الموارد البشرية') LIMIT 1));
--> statement-breakpoint
INSERT INTO job_titles (name_en,name_ar,department_id,status,created_at,updated_at) SELECT 'IT Manager','مدير إدارة التكنولوجيا',(SELECT id FROM departments WHERE trim(name_ar)=trim('نظم') LIMIT 1),'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM job_titles WHERE trim(name_ar)=trim('مدير إدارة التكنولوجيا') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('نظم') LIMIT 1));
--> statement-breakpoint
INSERT INTO job_titles (name_en,name_ar,department_id,status,created_at,updated_at) SELECT 'Social Media Specialist','أخصائي برامج التواصل الأجتماعى',(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1),'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM job_titles WHERE trim(name_ar)=trim('أخصائي برامج التواصل الأجتماعى') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1));
--> statement-breakpoint
INSERT INTO job_titles (name_en,name_ar,department_id,status,created_at,updated_at) SELECT 'Designer','مصمم',(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1),'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM job_titles WHERE trim(name_ar)=trim('مصمم') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1));
--> statement-breakpoint
INSERT INTO job_titles (name_en,name_ar,department_id,status,created_at,updated_at) SELECT 'Technology Director','مدير قطاع التكنولوجيا',(SELECT id FROM departments WHERE trim(name_ar)=trim('التقنية') LIMIT 1),'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM job_titles WHERE trim(name_ar)=trim('مدير قطاع التكنولوجيا') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('التقنية') LIMIT 1));
--> statement-breakpoint
INSERT INTO job_titles (name_en,name_ar,department_id,status,created_at,updated_at) SELECT 'HR','HR',(SELECT id FROM departments WHERE trim(name_ar)=trim('إدارة الموارد البشرية') LIMIT 1),'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM job_titles WHERE trim(name_ar)=trim('HR') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('إدارة الموارد البشرية') LIMIT 1));
--> statement-breakpoint
INSERT INTO job_titles (name_en,name_ar,department_id,status,created_at,updated_at) SELECT 'Snr. sales representative','Snr. sales representative',(SELECT id FROM departments WHERE trim(name_ar)=trim('المبيعات') LIMIT 1),'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM job_titles WHERE trim(name_ar)=trim('Snr. sales representative') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('المبيعات') LIMIT 1));
--> statement-breakpoint
INSERT INTO job_titles (name_en,name_ar,department_id,status,created_at,updated_at) SELECT 'Data Entry','ادخال البيانات',(SELECT id FROM departments WHERE trim(name_ar)=trim('خدمة عملاء') LIMIT 1),'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM job_titles WHERE trim(name_ar)=trim('ادخال البيانات') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('خدمة عملاء') LIMIT 1));
--> statement-breakpoint
INSERT INTO job_titles (name_en,name_ar,department_id,status,created_at,updated_at) SELECT 'Contracts Specialist','التعاقدات',(SELECT id FROM departments WHERE trim(name_ar)=trim('التعاقدات') LIMIT 1),'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM job_titles WHERE trim(name_ar)=trim('التعاقدات') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('التعاقدات') LIMIT 1));
--> statement-breakpoint
INSERT INTO job_titles (name_en,name_ar,department_id,status,created_at,updated_at) SELECT 'UI/UX','UI/UX',(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1),'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM job_titles WHERE trim(name_ar)=trim('UI/UX') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1));
--> statement-breakpoint
INSERT INTO job_titles (name_en,name_ar,department_id,status,created_at,updated_at) SELECT 'Customer Support','دعم العملاء',(SELECT id FROM departments WHERE trim(name_ar)=trim('خدمة عملاء') LIMIT 1),'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM job_titles WHERE trim(name_ar)=trim('دعم العملاء') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('خدمة عملاء') LIMIT 1));
--> statement-breakpoint
INSERT INTO job_titles (name_en,name_ar,department_id,status,created_at,updated_at) SELECT 'UI/UX','UI/UX',(SELECT id FROM departments WHERE trim(name_ar)=trim('UX/UI') LIMIT 1),'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM job_titles WHERE trim(name_ar)=trim('UI/UX') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('UX/UI') LIMIT 1));
--> statement-breakpoint
INSERT INTO job_titles (name_en,name_ar,department_id,status,created_at,updated_at) SELECT 'Data Analyst','محلل بيانات',(SELECT id FROM departments WHERE trim(name_ar)=trim('الحسابات') LIMIT 1),'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM job_titles WHERE trim(name_ar)=trim('محلل بيانات') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('الحسابات') LIMIT 1));
--> statement-breakpoint
INSERT INTO job_titles (name_en,name_ar,department_id,status,created_at,updated_at) SELECT 'Asus Merchants Manager','مدير اسس للتجار',(SELECT id FROM departments WHERE trim(name_ar)=trim('أسس للتجار') LIMIT 1),'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM job_titles WHERE trim(name_ar)=trim('مدير اسس للتجار') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('أسس للتجار') LIMIT 1));
--> statement-breakpoint
INSERT INTO job_titles (name_en,name_ar,department_id,status,created_at,updated_at) SELECT 'Representative','مندوب',(SELECT id FROM departments WHERE trim(name_ar)=trim('إدارة الموارد البشرية') LIMIT 1),'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM job_titles WHERE trim(name_ar)=trim('مندوب') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('إدارة الموارد البشرية') LIMIT 1));
--> statement-breakpoint
INSERT INTO job_titles (name_en,name_ar,department_id,status,created_at,updated_at) SELECT 'Accountant','محاسب',(SELECT id FROM departments WHERE trim(name_ar)=trim('الحسابات') LIMIT 1),'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM job_titles WHERE trim(name_ar)=trim('محاسب') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('الحسابات') LIMIT 1));
--> statement-breakpoint
INSERT INTO job_titles (name_en,name_ar,department_id,status,created_at,updated_at) SELECT 'Chief Executive Officer','الرئيس التنفيذى',(SELECT id FROM departments WHERE trim(name_ar)=trim('العضو المنتدب') LIMIT 1),'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM job_titles WHERE trim(name_ar)=trim('الرئيس التنفيذى') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('العضو المنتدب') LIMIT 1));
--> statement-breakpoint
INSERT INTO job_titles (name_en,name_ar,department_id,status,created_at,updated_at) SELECT 'Digital Marketing Manager','Digital Marketing Manager',(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1),'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM job_titles WHERE trim(name_ar)=trim('Digital Marketing Manager') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1));
--> statement-breakpoint
INSERT INTO job_titles (name_en,name_ar,department_id,status,created_at,updated_at) SELECT 'Accounting Manager','مدير الحسابات',(SELECT id FROM departments WHERE trim(name_ar)=trim('الحسابات') LIMIT 1),'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM job_titles WHERE trim(name_ar)=trim('مدير الحسابات') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('الحسابات') LIMIT 1));
--> statement-breakpoint
INSERT INTO job_titles (name_en,name_ar,department_id,status,created_at,updated_at) SELECT 'Sales and Projects Manager','Sales and Projects Manager',(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1),'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM job_titles WHERE trim(name_ar)=trim('Sales and Projects Manager') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1));
--> statement-breakpoint
INSERT INTO job_titles (name_en,name_ar,department_id,status,created_at,updated_at) SELECT 'Design Manager','مدير المصممين',(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1),'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM job_titles WHERE trim(name_ar)=trim('مدير المصممين') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1));
--> statement-breakpoint
INSERT INTO job_titles (name_en,name_ar,department_id,status,created_at,updated_at) SELECT 'Sales specialist','Sales specialist',(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1),'active',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP WHERE NOT EXISTS (SELECT 1 FROM job_titles WHERE trim(name_ar)=trim('Sales specialist') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1));
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1767255602887','Abanoub Mamdouh','ابانوب ممدوح حنا يوسف','abanoub@koon.sa','19','01029009237','01022233277','Egypt','male','2001-03-03','30103032500518',(SELECT id FROM departments WHERE trim(name_ar)=trim('برمجة') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('مطور برامج') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('برمجة') LIMIT 1) LIMIT 1),'2025-12-01','2026-11-30','active',NULL,'EGP','Egypt','Egypt','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'abanoub@koon.sa',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1767255602887';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1767255602887';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1777963843386','Abdelrahman Bahaa','عبدالرحمن بهاء إبراهيم خليل','abdelrahman@koon.sa','22','01009606605','010400504843','Egypt','male','2001-10-06','30110068800433',(SELECT id FROM departments WHERE trim(name_ar)=trim('برمجة') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('مطور برامج') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('برمجة') LIMIT 1) LIMIT 1),'2026-05-01','2027-04-30','active',NULL,'EGP','Egypt','Egypt','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'abdelrahman@koon.sa',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1777963843386';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1777963843386';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1767255747751','AbdelRazik Ehab','عبدالرازق إيهاب كمال','abdelrazik@koon.sa','13','01156827483','01022233166','Egypt','male','2000-11-12','30011120103632',(SELECT id FROM departments WHERE trim(name_ar)=trim('برمجة') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('مطور برامج') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('برمجة') LIMIT 1) LIMIT 1),'2025-11-09','2026-11-08','active',NULL,'EGP','Egypt','Egypt','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'abdelrazik@koon.sa',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1767255747751';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1767255747751';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1767255763570','AbdulAziz Almutiry','عبدالعزيز المطيري','abdelaziz@asuscard.sa',NULL,'+966540910405',NULL,'Egypt','male',NULL,NULL,(SELECT id FROM departments WHERE trim(name_ar)=trim('المبيعات') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('مدير الدعم و المبيعات') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('المبيعات') LIMIT 1) LIMIT 1),'2026-01-01',NULL,'active',NULL,'EGP','Egypt','Egypt','full_time','shift','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'abdelaziz@asuscard.sa',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1767255763570';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1767255763570';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1767255737371','Abdulhamed Yassin','عبدالحميد حسن ابراهيم يسن','abdulhamed@asuscard.sa',NULL,'01507974455','01040400914','Egypt','male','1982-10-05',NULL,(SELECT id FROM departments WHERE trim(name_ar)=trim('إدارة الموارد البشرية') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('مدير إدارة الموارد البشرية') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('إدارة الموارد البشرية') LIMIT 1) LIMIT 1),'2025-01-01',NULL,'active',NULL,'EGP','Egypt','Egypt','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'abdulhamed@asuscard.sa',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1767255737371';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1767255737371';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP17791060979420','Abdullah Al Sharani','عبدالله الشهراني','a.alshahrani@koonagency.com',NULL,NULL,NULL,'Saudi Arabia','male',NULL,NULL,(SELECT id FROM departments WHERE trim(name_ar)=trim('تطوير الاعمال') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('marketing manager') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('تطوير الاعمال') LIMIT 1) LIMIT 1),'2026-05-18',NULL,'active',NULL,'SAR','Saudi Arabia','Saudi Arabia','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'a.alshahrani@koonagency.com',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP17791060979420';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP17791060979420';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1777905530845','Adel Magdy','عادل مجد مكانوتة ويصة','adel@koon.sa','21','01279792507','01000136805','Egypt','male','2001-02-12','30102122602038',(SELECT id FROM departments WHERE trim(name_ar)=trim('برمجة') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('مطور برامج') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('برمجة') LIMIT 1) LIMIT 1),'2026-05-03','2027-05-02','active',NULL,'EGP','Egypt','Egypt','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'adel@koon.sa',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1777905530845';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1777905530845';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1767255617022','Ahmed Wally','احمد والي','ahmed.waly@smartlines-sa.com','14','01062553083','01040400918','Egypt','male','1994-11-24','29411241201952',(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('مدير سمارت لين') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1) LIMIT 1),'2025-11-05','2026-06-30','terminated',NULL,'EGP','Egypt','Egypt','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'ahmed.waly@smartlines-sa.com',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1767255617022';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1767255617022';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1767255626255','Ahmed El Shewy','أحمد خالد الشيوى','ahmed.elshewy@koon.sa','11','01026061270','01040400916','Egypt','male','2002-12-03','30212031601837',(SELECT id FROM departments WHERE trim(name_ar)=trim('نظم') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('دعم التقنى') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('نظم') LIMIT 1) LIMIT 1),'2025-11-01','2026-10-30','active',NULL,'EGP','Egypt','Egypt','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'ahmed.elshewy@koon.sa',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1767255626255';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1767255626255';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1784465493038','Ahmed elrefai','احمد محمد الرفاعي','media.buyer@koonagency.com','27','01226235547',NULL,'Egypt','male','2001-03-15','30103151603872',(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('Digital Marketing Specialist') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1) LIMIT 1),'2026-07-19',NULL,'active',NULL,'EGP','Egypt','Egypt','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'media.buyer@koonagency.com',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1784465493038';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1784465493038';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1767255774947','Amr Zaki','عمرو زكي علام','amr@koon.sa','6','01013622100','01000136686','Egypt','male','2000-01-30','30001308800777',(SELECT id FROM departments WHERE trim(name_ar)=trim('محلل بيانات') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('محلل بيانات') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('محلل بيانات') LIMIT 1) LIMIT 1),'2025-11-11','2026-11-10','active',NULL,'EGP','Egypt','Egypt','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'amr@koon.sa',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1767255774947';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1767255774947';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1767255645581','Aya Hakm','ايه حكم محمد محمد متولي','aya.hakem@asuscard.sa',NULL,'01553282965',NULL,'Egypt','female','1999-01-01','29901011223385',(SELECT id FROM departments WHERE trim(name_ar)=trim('المبيعات') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('مندوب البيع') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('المبيعات') LIMIT 1) LIMIT 1),'2025-10-01','2026-09-30','active',NULL,'EGP','Egypt','Egypt','full_time','shift','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'aya.hakem@asuscard.sa',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1767255645581';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1767255645581';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1777964028898','Diaa Helmy','ضياء الدين حلمى محمد السيد','diaa@koon.sa','23','01120027490','01040050485','Egypt','male','2001-02-12','30102021201679',(SELECT id FROM departments WHERE trim(name_ar)=trim('برمجة') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('مطور برامج') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('برمجة') LIMIT 1) LIMIT 1),'2026-05-01','2027-04-30','active',NULL,'EGP','Egypt','Egypt','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'diaa@koon.sa',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1777964028898';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1777964028898';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1774854557687','Doaa Alian','دعاء عليان محمود','pending.emp1774854557687@invalid.koon.local','9','01128931483',NULL,'Egypt','female','1993-05-18','29305180103761',(SELECT id FROM departments WHERE trim(name_ar)=trim('إدارة الموارد البشرية') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('Office boy') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('إدارة الموارد البشرية') LIMIT 1) LIMIT 1),'2026-03-03','2027-03-02','active',NULL,'EGP','Egypt','Egypt','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1774854557687';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1767687066235','Fadi Mounir','فادي منير زغلول لنديوس','fady.mounir@koon.sa','4','01226800676','01000085946','Egypt','male','1990-10-17','29010170201251',(SELECT id FROM departments WHERE trim(name_ar)=trim('نظم') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('مدير إدارة التكنولوجيا') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('نظم') LIMIT 1) LIMIT 1),'2025-12-01','2026-11-30','active',NULL,'EGP','Egypt','Egypt','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'fady.mounir@koon.sa',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1767687066235';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1767687066235';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1767255685944','Goud El-Yami','جود اليامي','jood@koonagency.com',NULL,'+966550677076',NULL,'Saudi Arabia','female',NULL,NULL,(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('أخصائي برامج التواصل الأجتماعى') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1) LIMIT 1),'2026-01-01',NULL,'active',NULL,'SAR','Saudi Arabia','Saudi Arabia','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'jood@koonagency.com',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1767255685944';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1767255685944';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1784536141599','kareem elshafie','كريم الشافعي','pending.emp1784536141599@invalid.koon.local',NULL,NULL,NULL,'Egypt','male',NULL,NULL,(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('مصمم') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1) LIMIT 1),'2026-07-01',NULL,'active',NULL,'EGP','Egypt','Egypt','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1784536141599';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1783414422107','Maan mohammed','معن محمد جلال','maan@koon.sa','26','01024941663',NULL,'Egypt','male','2001-09-24','30109241303213',(SELECT id FROM departments WHERE trim(name_ar)=trim('برمجة') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('مطور برامج') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('برمجة') LIMIT 1) LIMIT 1),'2026-07-01','2027-06-30','active',NULL,'EGP','Egypt','Egypt','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'maan@koon.sa',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1783414422107';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1783414422107';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1767255793641','Maged Shawky','ماجد احمد شوقي','maged@koon.sa','1','01112115553','01000085894','Egypt','male','1972-10-26','27210260103594',(SELECT id FROM departments WHERE trim(name_ar)=trim('التقنية') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('مدير قطاع التكنولوجيا') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('التقنية') LIMIT 1) LIMIT 1),'2025-10-01','2026-09-30','active',NULL,'EGP','Egypt','Egypt','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'maged@koon.sa',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1767255793641';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,30,0,0 FROM employees WHERE employee_code='EMP1767255793641';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1781075830552','Maged Elenzy','ماجد العنزي','hr@ayedsteelsa.com',NULL,NULL,NULL,'Saudi Arabia','male',NULL,NULL,(SELECT id FROM departments WHERE trim(name_ar)=trim('إدارة الموارد البشرية') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('HR') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('إدارة الموارد البشرية') LIMIT 1) LIMIT 1),'2026-06-10',NULL,'active',NULL,'SAR','Saudi Arabia','Saudi Arabia','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'hr@ayedsteelsa.com',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1781075830552';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1781075830552';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1767255839413','Mai Samir','مي سمير عبدالمحسن','mai.samir@asuscard.sa','12','01280446680','01070300449','Egypt','female','1989-10-19','28909261603067',(SELECT id FROM departments WHERE trim(name_ar)=trim('المبيعات') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('Snr. sales representative') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('المبيعات') LIMIT 1) LIMIT 1),'2025-11-09','2026-11-08','active',NULL,'EGP','Egypt','Egypt','full_time','fixed','0,1,2,3,4','08:00','16:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'mai.samir@asuscard.sa',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1767255839413';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1767255839413';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1785659350206','Malak elasaly','ملك العسال','malak.elasaly@koon.sa','28',NULL,NULL,'Egypt','female',NULL,'30502111601747',(SELECT id FROM departments WHERE trim(name_ar)=trim('خدمة عملاء') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('ادخال البيانات') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('خدمة عملاء') LIMIT 1) LIMIT 1),'2026-08-02',NULL,'active',NULL,'EGP','Egypt','Egypt','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'malak.elasaly@koon.sa',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1785659350206';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1785659350206';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1781612598781','Maram alaqil','مرام العقيل','maram@koonagency.com',NULL,NULL,NULL,NULL,'female',NULL,NULL,(SELECT id FROM departments WHERE trim(name_ar)=trim('التعاقدات') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('التعاقدات') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('التعاقدات') LIMIT 1) LIMIT 1),'2026-06-16',NULL,'active',NULL,'EGP','Egypt','Egypt','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'maram@koonagency.com',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1781612598781';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1781612598781';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1780320584123','Mariam Abdelrahman','مريم عبدالرحمن','mariam@asuscards.com',NULL,NULL,NULL,'Saudi Arabia','female',NULL,NULL,(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('UI/UX') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1) LIMIT 1),'2026-06-01',NULL,'active',NULL,'SAR','Saudi Arabia','Saudi Arabia','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'mariam@asuscards.com',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1780320584123';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1780320584123';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1777986401322','Mawadaa Hussein','نهى عبد الحليم حسين مصطفى كامل','mwada.hussien@asuscard.sa',NULL,'01032762391',NULL,'Egypt','female','2001-06-28','30106280103303',(SELECT id FROM departments WHERE trim(name_ar)=trim('خدمة عملاء') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('دعم العملاء') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('خدمة عملاء') LIMIT 1) LIMIT 1),'2026-05-05','2027-05-04','active',NULL,'EGP','Egypt','Egypt','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'mwada.hussien@asuscard.sa',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1777986401322';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1777986401322';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1767255848818','Mimouna El-Salmy','ميمونه السالمي','maimona@koonagency.com',NULL,'+966 54 473 8938',NULL,'Saudi Arabia','female',NULL,NULL,(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('أخصائي برامج التواصل الأجتماعى') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1) LIMIT 1),'2026-01-01',NULL,'active',NULL,'SAR','Saudi Arabia','Saudi Arabia','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'maimona@koonagency.com',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1767255848818';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1767255848818';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1781513344462','Mireille matta','ميراي متي موسي','mireille@koon.sa','25','01032966026',NULL,'Egypt','female','2004-01-21','30401212100284',(SELECT id FROM departments WHERE trim(name_ar)=trim('UX/UI') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('UI/UX') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('UX/UI') LIMIT 1) LIMIT 1),'2026-06-15','2027-06-14','active',NULL,'EGP','Egypt','Egypt','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'mireille@koon.sa',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1781513344462';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1781513344462';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1767255801825','Mohamed Saad','محمد سعد عبدالسلام','mohamed.saad@asuscard.sa','5','01011817373','01099918852','Egypt','male','1996-10-01','29610011352458',(SELECT id FROM departments WHERE trim(name_ar)=trim('الحسابات') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('محلل بيانات') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('الحسابات') LIMIT 1) LIMIT 1),'2025-11-11','2026-11-10','active',NULL,'EGP','Egypt','Egypt','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'mohamed.saad@asuscard.sa',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1767255801825';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1767255801825';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP17675328733860','Mohamed Moustafa','محمد مصطفي','mohamed.mostafa@asuscard.sa',NULL,NULL,NULL,'Egypt',NULL,NULL,NULL,(SELECT id FROM departments WHERE trim(name_ar)=trim('أسس للتجار') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('مدير اسس للتجار') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('أسس للتجار') LIMIT 1) LIMIT 1),'2026-01-04',NULL,'active',NULL,'EGP','Egypt','Egypt','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'mohamed.mostafa@asuscard.sa',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP17675328733860';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP17675328733860';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1772689551215','Mohamed Saber','محمد صابر ابراهيم','pending.emp1772689551215@invalid.koon.local','8',NULL,'01000136689',NULL,'male','1975-05-02','27614102200419',(SELECT id FROM departments WHERE trim(name_ar)=trim('إدارة الموارد البشرية') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('مندوب') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('إدارة الموارد البشرية') LIMIT 1) LIMIT 1),'2026-01-01','2026-12-30','active',NULL,'EGP','Egypt','Egypt','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1772689551215';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1767255830092','Mostafa Mahmoud','مصطفي محمود ابراهيم','mostafa.mahmoud@asuscard.sa','10','01228379921','01099918744','Egypt','male','1997-07-07','29707011903971',(SELECT id FROM departments WHERE trim(name_ar)=trim('الحسابات') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('محاسب') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('الحسابات') LIMIT 1) LIMIT 1),'2026-05-01','2027-04-30','active',NULL,'EGP','Egypt','Egypt','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'mostafa.mahmoud@asuscard.sa',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1767255830092';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1767255830092';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1767255857814','Najd Abdallah','نجد عبدالله','najd@asuscard.sa',NULL,'+96655006 8197',NULL,'Saudi Arabia','female',NULL,NULL,(SELECT id FROM departments WHERE trim(name_ar)=trim('المبيعات') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('مندوب البيع') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('المبيعات') LIMIT 1) LIMIT 1),'2026-01-01',NULL,'active',NULL,'SAR','Saudi Arabia','Saudi Arabia','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'najd@asuscard.sa',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1767255857814';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1767255857814';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('E001','Nawaf AL Mutiry','نواف المطيرى','nawaf@asuscard.sa',NULL,NULL,'01000085949',NULL,'male',NULL,NULL,(SELECT id FROM departments WHERE trim(name_ar)=trim('العضو المنتدب') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('الرئيس التنفيذى') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('العضو المنتدب') LIMIT 1) LIMIT 1),'2023-01-01',NULL,'active',NULL,'EGP','Egypt','Egypt','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'nawaf@asuscard.sa',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='E001';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='E001';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1768909284137','osama ibrahiem','اسامه ابراهيم محمد','osama.ibrahim@koonagency.com','3','01023483668','01099918778','Egypt','male','1998-11-19','29811191402135',(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('Digital Marketing Manager') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1) LIMIT 1),'2026-01-18','2027-12-17','active',NULL,'EGP','Egypt','Egypt','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'osama.ibrahim@koonagency.com',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1768909284137';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1768909284137';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1767255705453','Rahaf El Sbaeey','رهف السبيعي','rahaf@asuscard.sa',NULL,'+966548619042',NULL,'Saudi Arabia','female',NULL,NULL,(SELECT id FROM departments WHERE trim(name_ar)=trim('خدمة عملاء') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('دعم العملاء') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('خدمة عملاء') LIMIT 1) LIMIT 1),'2026-01-01',NULL,'active',NULL,'SAR','Saudi Arabia','Saudi Arabia','full_time','shift','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'rahaf@asuscard.sa',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1767255705453';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1767255705453';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1767255696641','Ranna Khalifa','رنا خليفة محمد','rana@asuscard.sa','18','01501093031','01099918893','Egypt','female','2003-09-23','30310011214405',(SELECT id FROM departments WHERE trim(name_ar)=trim('المبيعات') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('مندوب البيع') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('المبيعات') LIMIT 1) LIMIT 1),'2025-12-01','2026-11-30','active',NULL,'EGP','Egypt','Egypt','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'rana@asuscard.sa',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1767255696641';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1767255696641';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP17675256340670','Sally Shalabi','سالي شلبي','sally.shalaby@asuscard.sa','20','01025791803','01099918772','Egypt','female','1990-01-09','29001091300481',(SELECT id FROM departments WHERE trim(name_ar)=trim('الحسابات') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('مدير الحسابات') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('الحسابات') LIMIT 1) LIMIT 1),'2026-01-01','2026-12-30','active',NULL,'EGP','Egypt','Egypt','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'sally.shalaby@asuscard.sa',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP17675256340670';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP17675256340670';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1778402798308','Sara Mohamed','ساره محمد','pending.emp1778402798308@invalid.koon.local',NULL,NULL,NULL,NULL,NULL,NULL,NULL,(SELECT id FROM departments WHERE trim(name_ar)=trim('خدمة عملاء') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('ادخال البيانات') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('خدمة عملاء') LIMIT 1) LIMIT 1),'2026-04-01','2026-06-30','terminated',NULL,'EGP','Egypt','Egypt','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1778402798308';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1779025936228','Tbarek Amjed','تبارك امجد','tabark.amjad@koon.sa',NULL,'+962 7 9714 6131',NULL,'Jordan','female',NULL,NULL,(SELECT id FROM departments WHERE trim(name_ar)=trim('UX/UI') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('UI/UX') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('UX/UI') LIMIT 1) LIMIT 1),'2026-05-01',NULL,'active',NULL,'EGP','Jordan','Egypt','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'tabark.amjad@koon.sa',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1779025936228';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1779025936228';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1786006144437','Turky Eletaby','تركي العتيبي','t.alotaibi@koonagency.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('Sales and Projects Manager') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1) LIMIT 1),'2026-08-06',NULL,'active',NULL,'EGP','Egypt','Egypt','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 't.alotaibi@koonagency.com',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1786006144437';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1786006144437';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1784720123699','ايمن -','ايمن -','ad.ayman@koonagency.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('مدير المصممين') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1) LIMIT 1),'2026-07-01',NULL,'active',NULL,'EGP','Egypt','Egypt','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'ad.ayman@koonagency.com',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1784720123699';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1784720123699';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1786006582511','حصه الزير','حصه الزير','pending.emp1786006582511@invalid.koon.local',NULL,NULL,NULL,NULL,NULL,NULL,NULL,(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('Sales specialist') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1) LIMIT 1),'2026-08-06',NULL,'active',NULL,'EGP','Egypt','Egypt','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1786006582511';
--> statement-breakpoint
INSERT OR IGNORE INTO employees (employee_code,name_en,name_ar,work_email,fingerprint_code,personal_phone,work_phone,nationality,gender,birth_date,identification_number,department_id,job_title_id,start_date,end_date,employment_status,salary,salary_currency,country,work_location,employment_type,schedule_type,work_days,check_in_time,check_out_time,grace_minutes,required_daily_minutes,created_at,updated_at) VALUES ('EMP1786006205511','مريم -','مريم -','mariam@koonagncy.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1),(SELECT id FROM job_titles WHERE trim(name_ar)=trim('UI/UX') AND department_id=(SELECT id FROM departments WHERE trim(name_ar)=trim('وكالة كون') LIMIT 1) LIMIT 1),'2026-08-06',NULL,'active',NULL,'EGP','Egypt','Egypt','full_time','fixed','0,1,2,3,4','09:00','17:00',15,480,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
--> statement-breakpoint
INSERT OR IGNORE INTO users (email,employee_id,role_id,status,must_change_password,created_at,updated_at) SELECT 'mariam@koonagncy.com',id,(SELECT id FROM roles WHERE name='Employee' LIMIT 1),'active',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP FROM employees WHERE employee_code='EMP1786006205511';
--> statement-breakpoint
INSERT OR IGNORE INTO leave_balances (employee_id,leave_type_id,year,entitlement,used,pending) SELECT id,(SELECT id FROM leave_types WHERE name_en='Annual leave' LIMIT 1),2026,0,0,0 FROM employees WHERE employee_code='EMP1786006205511';
--> statement-breakpoint
INSERT INTO audit_logs (user_id,action,module,record_type,record_id,previous_value,new_value,created_at) VALUES (NULL,'bulk_import','employees','workbook','employees.xlsx',NULL,'{"employees":43,"departments":14,"jobs":31}',CURRENT_TIMESTAMP);
--> statement-breakpoint
PRAGMA optimize;
