import assert from 'node:assert/strict';
import test from 'node:test';
import { assignmentFromPayload, validateAssignment, prefillPosition, resolveHrRule } from '../app/organization/assignment-policy.ts';
import { buildReportingForest, visibleReportingRows, filterChartEmployees, reportingMatchSet } from '../app/organization/reporting-tree.ts';

const active=(id,extra={})=>({id,status:'active',...extra});
const catalog={companies:[active(1),active(2)],branches:[active(1),active(2)],companyBranches:[{company_id:1,branch_id:1},{company_id:1,branch_id:2},{company_id:2,branch_id:2}],departments:[active(10,{company_id:1,organization_kind:'department',branch_scope:'all'}),active(11,{company_id:1,organization_kind:'department',branch_scope:'selected'}),active(12,{company_id:2,organization_kind:'department',branch_scope:'all'}),active(20,{company_id:1,organization_kind:'section',parent_id:10,branch_scope:'all'}),active(30,{company_id:1,organization_kind:'team',parent_id:10,branch_scope:'all'})],branchScopes:[{department_id:11,branch_id:2}],positions:[active(1,{company_id:1,department_id:10,grade_id:1})],grades:[active(1),active(2)],workLocations:[active(1,{branch_id:1})],hrRules:[active(1,{company_id:null,branch_id:1,hr_user_id:10}),active(2,{company_id:1,branch_id:1,hr_user_id:20})],jobTitles:[active(1,{department_id:10})]};
const assignment={company_id:1,branch_id:1,department_id:10,position_id:1,grade_id:1,section_id:null,team_id:null,job_title_id:1};
test('company branch membership supports many-to-many and rejects unrelated pairs',()=>{assert.doesNotThrow(()=>validateAssignment(catalog,{company_id:2,branch_id:2}));assert.throws(()=>validateAssignment(catalog,{company_id:2,branch_id:1}),/Branch/);});
test('department-position assignment requires neither section nor team',()=>assert.deepEqual(validateAssignment(catalog,assignment),assignment));
test('shared departments span both branches; restricted units only their configured branch',()=>{assert.doesNotThrow(()=>validateAssignment(catalog,{...assignment,branch_id:2}));assert.doesNotThrow(()=>validateAssignment(catalog,{company_id:1,branch_id:2,department_id:11}));assert.throws(()=>validateAssignment(catalog,{company_id:1,branch_id:1,department_id:11}),/scope/);});
test('cross company units and contradictory position fields are rejected',()=>{assert.throws(()=>validateAssignment(catalog,{...assignment,department_id:12}),/contradicts/);assert.throws(()=>validateAssignment(catalog,{...assignment,grade_id:2}),/contradicts/);assert.throws(()=>validateAssignment(catalog,{...assignment,company_id:2,branch_id:2}),/contradicts/);});
test('teams can belong directly to a department; sections enforce their parent',()=>{assert.doesNotThrow(()=>validateAssignment(catalog,{...assignment,team_id:30}));assert.throws(()=>validateAssignment(catalog,{company_id:1,branch_id:2,department_id:11,section_id:20}),/Section/);});
test('work locations remain separate and respect branch',()=>assert.throws(()=>validateAssignment(catalog,{...assignment,branch_id:2,work_location_id:1}),/location/));
test('position selection prefills defined values and clears obsolete optional units',()=>{const form=prefillPosition({sectionId:'99',teamId:'98'},catalog.positions[0]);assert.equal(form.departmentId,'10');assert.equal(form.gradeId,'1');assert.equal(form.sectionId,'');assert.equal(form.teamId,'');});
test('unchanged legacy assignments survive non-organizational edits',()=>{const old={id:99,company_id:null,department_id:999,job_title_id:888};assert.deepEqual(validateAssignment(catalog,old,old),old);assert.equal(assignmentFromPayload({nameEn:'New'},old).department_id,999);});
test('HR company-branch rule precedes branch fallback without replacing employee override',()=>{assert.equal(resolveHrRule(catalog,assignment).hr_user_id,20);assert.equal(resolveHrRule(catalog,{company_id:2,branch_id:1}).hr_user_id,10);assert.equal(assignmentFromPayload({}, {hr_user_id:99}).hr_user_id,99);});
test('reporting forest retains cross-branch reports, multiple roots and missing managers',()=>{const rows=[{id:1,company_id:1,branch_id:1},{id:2,company_id:1,branch_id:2,manager_id:1},{id:3,company_id:1,manager_id:999},{id:4,company_id:2}];const roots=buildReportingForest(rows);assert.deepEqual(roots.map(n=>n.employee.id),[1,3,4]);assert.equal(roots[0].children[0].employee.id,2);});
test('cycles and duplicates cannot hide employees or recurse forever',()=>{const roots=buildReportingForest([{id:1,manager_id:2},{id:2,manager_id:1},{id:1,manager_id:2}]);assert.equal(visibleReportingRows(roots,new Set()).length,2);});
test('profile manager and branch changes relocate employee without chart-specific data',()=>{const rows=[{id:1,company_id:1},{id:2,company_id:1},{id:3,company_id:1,branch_id:1,manager_id:1}];assert.equal(buildReportingForest(rows)[0].children[0].employee.id,3);rows[2]={...rows[2],manager_id:2,branch_id:2};const forest=buildReportingForest(rows);assert.equal(forest[0].children.length,0);assert.equal(forest[1].children[0].employee.branch_id,2);});
test('filtered or inaccessible managers are never synthesized into the forest',()=>{const root=buildReportingForest([{id:2,manager_id:1}]);assert.equal(root.length,1);assert.equal(root[0].employee.id,2);assert.equal(visibleReportingRows(root,new Set()).length,1);});
test('deep 1000-employee tree uses iterative traversal and collapse',()=>{const rows=Array.from({length:1000},(_,i)=>({id:i+1,manager_id:i||null})),roots=buildReportingForest(rows);assert.equal(visibleReportingRows(roots,new Set()).length,1000);assert.equal(visibleReportingRows(roots,new Set([1])).length,1);});

test('inactive managers are hidden by default without hiding their active reports',()=>{const rows=[{id:1,employment_status:'inactive'},{id:2,manager_id:1,employment_status:'active',branch_id:2,department_id:10}];const shown=filterChartEmployees(rows,{});assert.equal(shown.length,1);assert.equal(buildReportingForest(shown)[0].employee.id,2);assert.equal(filterChartEmployees(rows,{includeInactive:true}).length,2);assert.equal(filterChartEmployees(rows,{branch:'1'}).length,0);assert.equal(filterChartEmployees(rows,{branch:'2',department:'10'}).length,1);});
test('search keeps matches with their managers and drops unrelated branches',()=>{const rows=[{id:1,name:'boss'},{id:2,manager_id:1,name:'lead'},{id:3,manager_id:2,name:'target'},{id:4,manager_id:1,name:'other'},{id:5,name:'solo'}],roots=buildReportingForest(rows),shown=reportingMatchSet(roots,e=>e.name==='target');assert.deepEqual([...shown].map(n=>n.employee.id).sort(),[1,2,3]);assert.equal(reportingMatchSet(roots,()=>false).size,0);});
