"use client";

import { useCallback, useEffect, useState } from "react";
import { CalendarDays, ChevronRight, Clock3, FileText, Home, Plus, ReceiptText, Stethoscope, TimerReset, Wallet, X } from "lucide-react";
import { AttendanceCorrectionDrawer, CorrectionDetail } from "./attendance-workspace";

// Bootstrap rows are intentionally heterogeneous projections from the shared HR endpoint.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Row = Record<string, any>;
type PortalData = {
  currentUser?:Row;employees:Row[];attendance:Row[];requests:Row[];requestApprovals:Row[];
  leaveBalances:Row[];leaveTypes:Row[];holidays:Row[];attendanceCorrections?:Row[];attendanceCorrectionActions?:Row[];
};

const locale=(rtl:boolean)=>rtl?"ar-SA-u-nu-arab":"en-GB";
const number=(value:number,rtl:boolean)=>new Intl.NumberFormat(locale(rtl),{maximumFractionDigits:2}).format(value);
const date=(value:string,rtl:boolean,options:Intl.DateTimeFormatOptions={day:"numeric",month:"short",year:"numeric"})=>new Intl.DateTimeFormat(locale(rtl),options).format(new Date(`${value.slice(0,10)}T12:00:00`));
const requestName=(value:string,rtl:boolean)=>rtl?({"Annual Leave":"إجازة سنوية","Sick Leave":"إجازة مرضية","Work from home":"عمل من المنزل","Late arrival":"طلب تأخير","Early departure":"انصراف مبكر","Expense reimbursement":"استرداد مصروفات","Experience certificate":"شهادة خبرة"}[value]||value):value;
const statusLabel=(value:string,rtl:boolean)=>{
  const labels:Record<string,[string,string]>={pending_manager:["Waiting for Manager","بانتظار المدير"],pending_hr:["Waiting for HR","بانتظار الموارد البشرية"],hr_approved:["Approved","معتمد"],manager_rejected:["Rejected by Manager","مرفوض من المدير"],hr_rejected:["Rejected by HR","مرفوض من الموارد البشرية"],cancelled:["Cancelled","ملغي"]};
  return labels[value]?.[rtl?1:0]||value.replaceAll("_"," ");
};
const tone=(value:string)=>value==="hr_approved"?"green":value.includes("rejected")||value==="cancelled"?"rose":"amber";

async function api(payload?:Row){
  const response=await fetch("/api/hr",payload?{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}:{cache:"no-store"});
  const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||`Request failed (${response.status})`);return body;
}

function Badge({value,rtl}:{value:string;rtl:boolean}){return <span className={`portal-status ${tone(value)}`}>{statusLabel(value,rtl)}</span>}

export function EmployeePortalWorkspace({rtl,openRequest,openPayslips,notify}:{rtl:boolean;openRequest:(preset:string)=>void;openPayslips:()=>void;notify:(message:string)=>void}){
  const [data,setData]=useState<PortalData|null>(null),[error,setError]=useState(""),[selected,setSelected]=useState<Row|null>(null),[selectedCorrection,setSelectedCorrection]=useState<Row|null>(null),[correctionRow,setCorrectionRow]=useState<Row|null|undefined>(undefined),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{try{setData(await api());setError("");}catch{setError(rtl?"تعذر تحميل مساحة العمل. حاول مرة أخرى.":"Unable to load your workspace. Please try again.");}},[rtl]);
  useEffect(()=>{const refresh=()=>void load();const timer=window.setTimeout(refresh,0);window.addEventListener("hr-data-changed",refresh);return()=>{window.clearTimeout(timer);window.removeEventListener("hr-data-changed",refresh);};},[load]);
  const employeeId=Number(data?.currentUser?.employee_id)||0;
  const employee=data?.employees?.find(row=>Number(row.id)===employeeId);
  const today=new Date().toISOString().slice(0,10),year=Number(today.slice(0,4));
  const ownRequests=(data?.requests??[]).filter(row=>Number(row.employee_id)===employeeId);
  const approvals=data?.requestApprovals??[];
  const balances=(data?.leaveBalances??[]).filter(row=>Number(row.employee_id)===employeeId&&Number(row.year)===year);
  const attendance=(data?.attendance??[]).filter(row=>Number(row.employee_id)===employeeId);
  const corrections=(data?.attendanceCorrections??[]).filter(row=>Number(row.employee_id)===employeeId);
  const todayAttendance=attendance.find(row=>String(row.work_date).slice(0,10)===today);
  const approvedToday=ownRequests.find(row=>row.status==="hr_approved"&&row.leave_type_id&&String(row.from_date)<=today&&String(row.to_date)>=today);
  const holidayToday=(data?.holidays??[]).find(row=>row.status!=="deleted"&&(row.country===employee?.country||["Both","KSA & Egypt"].includes(row.country))&&(String(row.holiday_date)===today||(row.recurrence_type==="annual"&&String(row.holiday_date).slice(5)===today.slice(5))));
  const checkedIn=Boolean(todayAttendance?.actual_in)&&!todayAttendance?.actual_out;
  const checkedOut=Boolean(todayAttendance?.actual_out);
  const attendanceState=holidayToday?"holiday":approvedToday?"leave":checkedOut?"checked_out":checkedIn?"checked_in":todayAttendance?.status||"not_checked_in";
  const attendanceText:Record<string,[string,string]>={holiday:["Official holiday","عطلة رسمية"],leave:["On approved leave","في إجازة معتمدة"],checked_out:["Checked out","تم تسجيل الانصراف"],checked_in:["Checked in","تم تسجيل الحضور"],late:["Late","متأخر"],remote:["Remote","عن بُعد"],not_checked_in:["Not checked in","لم تسجل الحضور"]};
  const pending=ownRequests.filter(row=>String(row.status).startsWith("pending"));
  const recent=ownRequests.slice(0,5);
  const upcoming=ownRequests.filter(row=>row.leave_type_id&&row.status==="hr_approved"&&String(row.from_date)>today).sort((a,b)=>String(a.from_date).localeCompare(String(b.from_date)))[0];
  const nextHoliday=(data?.holidays??[]).filter(row=>row.status!=="deleted"&&(row.country===employee?.country||["Both","KSA & Egypt"].includes(row.country))&&String(row.holiday_date)>=today).sort((a,b)=>String(a.holiday_date).localeCompare(String(b.holiday_date)))[0];
  const leaveChoices=(data?.leaveTypes??[]).filter(row=>row.status==="active"&&row.code!=="OFFICIAL");
  const annual=leaveChoices.find(row=>String(row.code).startsWith("ANNUAL"))||leaveChoices[0];
  const sick=leaveChoices.find(row=>row.code==="SICK");
  const reload=async()=>{await load();window.dispatchEvent(new Event("hr-data-changed"));};
  const record=async()=>{try{setBusy(true);await api({action:"attendance_event",eventType:checkedIn?"check_out":"check_in"});await reload();notify(checkedIn?(rtl?"تم تسجيل الانصراف":"Check-out recorded"):(rtl?"تم تسجيل الحضور":"Check-in recorded"));}catch(reason){notify(reason instanceof Error?reason.message:(rtl?"تعذر تحديث الحضور":"Attendance action failed"));}finally{setBusy(false);}};
  const cancel=async(row:Row)=>{if(!window.confirm(rtl?"هل تريد إلغاء طلب الإجازة وإعادة الرصيد؟":"Cancel this leave request and restore its balance?"))return;try{setBusy(true);await api({action:"cancel_leave_request",requestId:row.id,reason:"Employee cancellation"});setSelected(null);await reload();notify(rtl?"تم إلغاء الطلب وإعادة الرصيد":"Request cancelled and balance restored");}catch(reason){notify(reason instanceof Error?reason.message:"Cancellation failed");}finally{setBusy(false);}};
  const canCancel=(row:Row)=>Boolean(row.leave_type_id)&&(["pending_manager","pending_hr"].includes(row.status)||(row.status==="hr_approved"&&String(row.from_date)>today));

  if(!data&&!error)return <div className="portal-loading"><Clock3/><span>{rtl?"جارٍ تجهيز مساحة عملك...":"Preparing your workspace..."}</span></div>;
  return <section className="employee-workspace">
    <header className="portal-welcome"><div><h1>{rtl?"بوابة الموظف":"Employee portal"}</h1></div><button className="primary" onClick={()=>openRequest("")}><Plus size={17}/>{rtl?"طلب جديد":"New request"}</button></header>
    {error&&<div className="error-banner">{error}<button onClick={()=>void load()}>{rtl?"إعادة المحاولة":"Retry"}</button></div>}
    <div className="portal-priority-grid">
      <article className="panel portal-attendance"><div className="portal-card-head"><span className="portal-icon"><Clock3/></span><div><small>{rtl?"حضور اليوم":"TODAY'S ATTENDANCE"}</small><h2>{attendanceText[attendanceState]?.[rtl?1:0]||attendanceState}</h2></div><span className="portal-live-dot"/></div><dl><div><dt>{rtl?"المقرر":"Scheduled"}</dt><dd>{todayAttendance?.scheduled_in||employee?.check_in_time||"—"} – {todayAttendance?.scheduled_out||employee?.check_out_time||"—"}</dd></div><div><dt>{rtl?"الدخول":"Check-in"}</dt><dd>{todayAttendance?.actual_in||"—"}</dd></div><div><dt>{rtl?"الخروج":"Check-out"}</dt><dd>{todayAttendance?.actual_out||"—"}</dd></div><div><dt>{rtl?"المدة":"Worked"}</dt><dd>{number(Number(todayAttendance?.worked_minutes)||0,rtl)} {rtl?"دقيقة":"min"}</dd></div></dl><div className="portal-attendance-actions">{!holidayToday&&!approvedToday&&!checkedOut&&<button className={checkedIn?"outline":"primary"} disabled={!employeeId||busy} onClick={()=>void record()}>{checkedIn?(rtl?"تسجيل الانصراف":"Check out"):(rtl?"تسجيل الحضور":"Check in")}</button>}<button className="outline" disabled={!employeeId} onClick={()=>setCorrectionRow(todayAttendance??null)}>{rtl?"مشكلة في الحضور":"Attendance issue"}</button></div>{Number(todayAttendance?.late_minutes)>0&&<p className="portal-alert"><TimerReset size={15}/>{rtl?`تأخير ${number(Number(todayAttendance?.late_minutes),rtl)} دقيقة`:`${Number(todayAttendance?.late_minutes)} minutes late`}</p>}{corrections.find(row=>["pending_manager","pending_hr"].includes(row.status))&&<p className="portal-alert correction-status"><FileText size={15}/>{rtl?"لديك تصحيح بانتظار الاعتماد":"A correction is awaiting approval"}</p>}</article>
      <article className="panel portal-actions"><div className="portal-card-head"><span className="portal-icon violet"><Plus/></span><div><small>{rtl?"إجراءات سريعة":"QUICK ACTIONS"}</small><h2>{rtl?"ماذا تحتاج اليوم؟":"What do you need today?"}</h2></div></div><div className="portal-action-grid">{annual&&<button onClick={()=>openRequest(`leave:${annual.id}`)}><CalendarDays/><span>{rtl?"طلب إجازة":"Request leave"}</span></button>}{sick&&<button onClick={()=>openRequest(`leave:${sick.id}`)}><Stethoscope/><span>{rtl?"إجازة مرضية":"Sick leave"}</span></button>}<button onClick={()=>openRequest("request:Work from home")}><Home/><span>{rtl?"عمل من المنزل":"Work from home"}</span></button><button onClick={()=>setCorrectionRow(todayAttendance??null)}><TimerReset/><span>{rtl?"تصحيح الحضور":"Attendance correction"}</span></button><button onClick={()=>openRequest("request:Expense reimbursement")}><ReceiptText/><span>{rtl?"استرداد مصروف":"Expense"}</span></button><button onClick={()=>openRequest("")}><Plus/><span>{rtl?"طلب آخر":"Other request"}</span></button></div></article>
    </div>
    <article className="panel portal-balances"><div className="portal-section-head"><div><small>{rtl?"رصيد الإجازات":"LEAVE BALANCE"}</small><h2>{rtl?"أرصدتك لهذا العام":"Your balances this year"}</h2></div><span>{year}</span></div>{balances.length?<div className="balance-strip">{balances.map(balance=>{const entitlement=Number(balance.entitlement)||0,used=Number(balance.used)||0,pendingDays=Number(balance.pending)||0,available=Number(balance.available??entitlement-used-pendingDays);return <div className="balance-item" key={balance.id}><div><b>{rtl?balance.leave_type_name_ar:balance.leave_type_name_en}</b><strong>{number(available,rtl)} <small>{rtl?"يوم متاح":"days available"}</small></strong></div><div className="balance-meter"><i style={{width:`${entitlement?Math.min(100,((used+pendingDays)/entitlement)*100):0}%`}}/></div><footer><span>{rtl?"المستحق":"Entitled"} <b>{number(entitlement,rtl)}</b></span><span>{rtl?"المستخدم":"Used"} <b>{number(used,rtl)}</b></span><span>{rtl?"المعلق":"Pending"} <b>{number(pendingDays,rtl)}</b></span></footer></div>})}</div>:<div className="portal-empty"><CalendarDays/><p>{rtl?"لا يوجد رصيد مرتبط بسياسة نشطة حتى الآن.":"No balance is linked to an active policy yet."}</p></div>}</article>
    {corrections.length>0&&<article className="panel portal-requests"><div className="portal-section-head"><div><small>{rtl?"تصحيحات الحضور":"ATTENDANCE CORRECTIONS"}</small><h2>{rtl?"الحالة ومسار الاعتماد":"Status and approval timeline"}</h2></div><span className="portal-count">{number(corrections.length,rtl)}</span></div><div className="portal-request-list">{corrections.slice(0,4).map(row=><button key={row.id} onClick={()=>setSelectedCorrection(row)}><span className="request-symbol"><TimerReset/></span><span><b>{rtl?"طلب تصحيح حضور":"Attendance correction"}</b><small>{date(row.attendance_date,rtl)} · {String(row.correction_type).replaceAll("_"," ")}</small></span><Badge value={String(row.status)} rtl={rtl}/><ChevronRight/></button>)}</div></article>}
    <div className="portal-content-grid">
      <article className="panel portal-requests"><div className="portal-section-head"><div><small>{rtl?"طلباتي":"MY REQUESTS"}</small><h2>{rtl?"الأحدث وحالتها":"Recent activity"}</h2></div><span className="portal-count">{number(pending.length,rtl)} {rtl?"معلق":"pending"}</span></div>{recent.length?<div className="portal-request-list">{recent.map(row=><button key={row.id} onClick={()=>setSelected(row)}><span className="request-symbol"><FileText/></span><span><b>{requestName(row.type,rtl)}</b><small>{row.request_code} · {date(String(row.created_at),rtl)}</small></span>{row.requested_days&&<em>{number(Number(row.requested_days),rtl)} {rtl?"يوم":"d"}</em>}<Badge value={String(row.status)} rtl={rtl}/><ChevronRight/></button>)}</div>:<div className="portal-empty"><FileText/><p>{rtl?"لم تقدم أي طلبات بعد.":"You have not submitted any requests yet."}</p></div>}</article>
      <aside className="portal-side-stack"><article className="panel portal-next"><span className="portal-icon green"><CalendarDays/></span><small>{rtl?"الإجازة القادمة":"UPCOMING LEAVE"}</small>{upcoming?<><h3>{requestName(upcoming.type,rtl)}</h3><p>{date(upcoming.from_date,rtl)} – {date(upcoming.to_date,rtl)}</p><b>{number(Number(upcoming.requested_days)||0,rtl)} {rtl?"يوم":"days"}</b></>:<p>{rtl?"لا توجد إجازة معتمدة قادمة.":"No approved upcoming leave."}</p>}</article><article className="panel portal-next"><span className="portal-icon amber"><CalendarDays/></span><small>{rtl?"العطلة الرسمية القادمة":"NEXT HOLIDAY"}</small>{nextHoliday?<><h3>{rtl?nextHoliday.name_ar:nextHoliday.name_en}</h3><p>{date(nextHoliday.holiday_date,rtl,{weekday:"long",day:"numeric",month:"long"})}</p></>:<p>{rtl?"لا توجد عطلات قادمة.":"No upcoming holidays."}</p>}</article><button className="panel portal-payslip-link" onClick={openPayslips}><Wallet/><span><b>{rtl?"قسائم الراتب":"My payslips"}</b><small>{rtl?"فتح العرض الحالي للقسائم":"Open the existing payslip view"}</small></span><ChevronRight/></button></aside>
    </div>
    {selected&&<div className="modal-layer"><button className="modal-scrim" onClick={()=>setSelected(null)} aria-label={rtl?"إغلاق":"Close"}/><aside className="drawer portal-request-drawer" role="dialog" aria-modal="true"><header><div><small>{selected.request_code}</small><h2>{requestName(selected.type,rtl)}</h2><Badge value={String(selected.status)} rtl={rtl}/></div><button className="icon-btn" onClick={()=>setSelected(null)} aria-label={rtl?"إغلاق":"Close"}><X/></button></header><div className="request-facts"><span><small>{rtl?"الفترة":"Period"}</small><b>{selected.from_date?`${date(selected.from_date,rtl)} – ${date(selected.to_date,rtl)}`:"—"}</b></span><span><small>{rtl?"الأيام المحتسبة":"Chargeable days"}</small><b>{selected.requested_days?number(Number(selected.requested_days),rtl):"—"}</b></span><span><small>{rtl?"المرحلة الحالية":"Current stage"}</small><b>{statusLabel(selected.status,rtl)}</b></span></div><section><h3>{rtl?"سبب الطلب":"Reason"}</h3><p>{selected.reason}</p></section><section><h3>{rtl?"سجل الطلب":"Request timeline"}</h3><ol className="request-timeline"><li><i/><div><b>{rtl?"تم تقديم الطلب":"Request submitted"}</b><time>{date(String(selected.created_at),rtl,{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"})}</time></div></li>{approvals.filter(item=>Number(item.request_id)===Number(selected.id)).map(item=><li key={item.id}><i/><div><b>{item.action==="approve"?(rtl?`اعتماد — ${item.actor_name_ar||item.actor_name||item.actor_email}`:`Approved — ${item.actor_name||item.actor_email}`):item.action==="cancel"?(rtl?"تم إلغاء الطلب":"Request cancelled"):(rtl?`رفض — ${item.actor_name_ar||item.actor_name||item.actor_email}`:`Rejected — ${item.actor_name||item.actor_email}`)}</b><time>{date(String(item.created_at),rtl,{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"})}</time>{item.reason&&<p>{rtl?"السبب: ":"Reason: "}{item.reason}</p>}</div></li>)}</ol></section>{canCancel(selected)&&<button className="danger-action" disabled={busy} onClick={()=>void cancel(selected)}>{rtl?"إلغاء الطلب وإعادة الرصيد":"Cancel request and restore balance"}</button>}</aside></div>}
    {correctionRow!==undefined&&<AttendanceCorrectionDrawer rtl={rtl} row={correctionRow} employeeId={employeeId} close={()=>setCorrectionRow(undefined)} done={()=>{void reload();notify(rtl?"تم إرسال طلب التصحيح":"Correction request submitted");}}/>}
    {selectedCorrection&&<CorrectionDetail rtl={rtl} row={selectedCorrection} data={data!} close={()=>setSelectedCorrection(null)} reload={load} notify={notify}/>}
  </section>;
}
