"use client";

import { useState } from "react";
import { CalendarDays, Check, ChevronRight, CircleUserRound, KeyRound, X } from "lucide-react";

type Row = Record<string, any>;
type Form = Record<string, any>;

export function EmployeeDrawer({rtl,data,close,submit}:{rtl:boolean;data:{employees:Row[];departments:Row[];jobTitles:Row[]}|null;close:()=>void;submit:(form:Form)=>Promise<void>}){
  const [step,setStep]=useState(1), [saving,setSaving]=useState(false), [error,setError]=useState("");
  const [form,setForm]=useState<Form>({nameAr:"",nameEn:"",workEmail:"",fingerprintCode:"",personalPhone:"",workPhone:"",nationality:"Saudi",gender:"male",birthDate:"",identificationNumber:"",address:"",departmentId:"",jobTitleId:"",managerId:"",startDate:new Date().toISOString().slice(0,10),endDate:"",employmentStatus:"active",salary:"",salaryCurrency:"SAR",country:"Saudi Arabia",workLocation:"Riyadh, KSA",employmentType:"full_time",scheduleType:"fixed",workDays:"0,1,2,3,4",checkInTime:"09:00",checkOutTime:"17:00",graceMinutes:15,requiredDailyMinutes:480});
  const update=(key:string,value:any)=>setForm(v=>({...v,[key]:value}));
  const next=()=>{setError("");if(step===1&&(!form.nameAr||!form.nameEn||!form.workEmail)){setError(rtl?"الاسم العربي والإنجليزي وبريد العمل حقول مطلوبة":"Arabic name, English name and work email are required");return;}if(step===2&&(!form.departmentId||!form.jobTitleId||!form.startDate)){setError(rtl?"القسم والمسمى وتاريخ البداية مطلوبة":"Department, job title and start date are required");return;}setStep(Math.min(4,step+1));};
  const finish=async()=>{try{setSaving(true);setError("");await submit(form);}catch(e){setError(e instanceof Error?e.message:"Unable to create employee");setSaving(false);}};
  return <div className="modal-layer"><button className="modal-scrim" onClick={close} aria-label="Close"/><aside className="drawer employee-drawer"><div className="drawer-head"><div><span className="eyebrow">{rtl?"سجل الموظف":"EMPLOYEE RECORD"}</span><h2>{rtl?"إضافة موظف جديد":"Add new employee"}</h2><p>{rtl?"سيُنشأ رقم موظف وحساب مستخدم تلقائياً بعد الحفظ.":"An employee ID and linked user account will be created automatically."}</p></div><button className="icon-btn" onClick={close}><X size={20}/></button></div>
  <div className="employee-steps">{[{n:1,e:"Basic",a:"البيانات الأساسية"},{n:2,e:"Employment",a:"التوظيف"},{n:3,e:"Attendance & leave",a:"الحضور والإجازات"},{n:4,e:"Review",a:"المراجعة"}].map(s=><span className={step===s.n?"active":step>s.n?"done":""} key={s.n}><b>{step>s.n?<Check size={13}/>:s.n}</b>{rtl?s.a:s.e}</span>)}</div>
  <div className="form-body">{error&&<div className="form-error">{error}</div>}
  {step===1&&<><div className="photo-upload"><CircleUserRound size={31}/><div><b>{rtl?"صورة الموظف":"Employee photo"}</b><small>{rtl?"يمكن إضافتها لاحقاً من الملف الشخصي":"Can be added later from the profile"}</small></div><button className="outline" type="button">{rtl?"رفع صورة":"Upload photo"}</button></div><div className="form-row"><Field label={rtl?"الاسم الكامل بالعربية *":"Arabic full name *"}><input value={form.nameAr} onChange={e=>update("nameAr",e.target.value)} dir="rtl"/></Field><Field label={rtl?"الاسم الكامل بالإنجليزية *":"English full name *"}><input value={form.nameEn} onChange={e=>update("nameEn",e.target.value)}/></Field></div><Field label={rtl?"البريد الإلكتروني للعمل *":"Work email *"}><input type="email" value={form.workEmail} onChange={e=>update("workEmail",e.target.value)} placeholder="name@koon.sa"/></Field><div className="form-row"><Field label={rtl?"كود جهاز البصمة":"Fingerprint device code"}><input value={form.fingerprintCode} onChange={e=>update("fingerprintCode",e.target.value)}/></Field><Field label={rtl?"الجنسية":"Nationality"}><input value={form.nationality} onChange={e=>update("nationality",e.target.value)}/></Field></div><div className="form-row"><Field label={rtl?"رقم الجوال الشخصي":"Personal mobile"}><input value={form.personalPhone} onChange={e=>update("personalPhone",e.target.value)}/></Field><Field label={rtl?"رقم جوال العمل":"Work mobile"}><input value={form.workPhone} onChange={e=>update("workPhone",e.target.value)}/></Field></div><div className="form-row"><Field label={rtl?"الجنس":"Gender"}><select value={form.gender} onChange={e=>update("gender",e.target.value)}><option value="male">{rtl?"ذكر":"Male"}</option><option value="female">{rtl?"أنثى":"Female"}</option></select></Field><Field label={rtl?"تاريخ الميلاد":"Date of birth"}><input type="date" value={form.birthDate} onChange={e=>update("birthDate",e.target.value)}/></Field></div><Field label={rtl?"رقم الهوية / الإقامة":"National ID / Iqama"}><input value={form.identificationNumber} onChange={e=>update("identificationNumber",e.target.value)}/></Field><Field label={rtl?"العنوان":"Address"}><textarea value={form.address} onChange={e=>update("address",e.target.value)}/></Field></>}
  {step===2&&<><div className="form-row"><Field label={rtl?"القسم *":"Department *"}><select value={form.departmentId} onChange={e=>update("departmentId",e.target.value)}><option value="">{rtl?"اختر القسم":"Select department"}</option>{data?.departments.map(d=><option value={d.id} key={d.id}>{rtl?d.name_ar:d.name_en}</option>)}</select></Field><Field label={rtl?"المسمى الوظيفي *":"Job title *"}><select value={form.jobTitleId} onChange={e=>update("jobTitleId",e.target.value)}><option value="">{rtl?"اختر المسمى":"Select job title"}</option>{data?.jobTitles.filter(j=>!form.departmentId||String(j.department_id)===String(form.departmentId)).map(j=><option value={j.id} key={j.id}>{rtl?j.name_ar:j.name_en}</option>)}</select></Field></div><Field label={rtl?"المدير المباشر":"Direct manager"}><select value={form.managerId} onChange={e=>update("managerId",e.target.value)}><option value="">{rtl?"بدون مدير مباشر":"No direct manager"}</option>{data?.employees.map(e=><option value={e.id} key={e.id}>{rtl?e.name_ar:e.name_en}</option>)}</select></Field><div className="form-row"><Field label={rtl?"تاريخ بداية العمل *":"Employment start date *"}><input type="date" value={form.startDate} onChange={e=>update("startDate",e.target.value)}/></Field><Field label={rtl?"حالة التوظيف":"Employment status"}><select value={form.employmentStatus} onChange={e=>update("employmentStatus",e.target.value)}><option value="active">Active</option><option value="probation">Probation</option><option value="notice_period">Notice period</option><option value="suspended">Suspended</option></select></Field></div><div className="form-row"><Field label={rtl?"الدولة":"Country"}><select value={form.country} onChange={e=>{update("country",e.target.value);update("salaryCurrency",e.target.value==="Egypt"?"EGP":"SAR");}}><option>Saudi Arabia</option><option>Egypt</option></select></Field><Field label={rtl?"موقع العمل":"Work location"}><input value={form.workLocation} onChange={e=>update("workLocation",e.target.value)}/></Field></div><div className="form-row"><Field label={rtl?"الراتب":"Salary"}><input type="number" min="0" value={form.salary} onChange={e=>update("salary",e.target.value)}/></Field><Field label={rtl?"العملة":"Currency"}><select value={form.salaryCurrency} onChange={e=>update("salaryCurrency",e.target.value)}><option>SAR</option><option>EGP</option></select></Field></div><Field label={rtl?"نوع التوظيف":"Employment type"}><select value={form.employmentType} onChange={e=>update("employmentType",e.target.value)}><option value="full_time">Full time</option><option value="part_time">Part time</option><option value="contract">Contract</option></select></Field></>}
  {step===3&&<><Field label={rtl?"نوع جدول الحضور":"Attendance schedule type"}><select value={form.scheduleType} onChange={e=>update("scheduleType",e.target.value)}><option value="fixed">{rtl?"جدول ثابت":"Fixed schedule"}</option><option value="shift">{rtl?"ورديات":"Shift schedule"}</option></select></Field><div className="form-row"><Field label={rtl?"وقت الحضور":"Check-in time"}><input type="time" value={form.checkInTime} onChange={e=>update("checkInTime",e.target.value)}/></Field><Field label={rtl?"وقت الانصراف":"Check-out time"}><input type="time" value={form.checkOutTime} onChange={e=>update("checkOutTime",e.target.value)}/></Field></div><div className="form-row"><Field label={rtl?"فترة السماح بالدقائق":"Grace period (minutes)"}><input type="number" value={form.graceMinutes} onChange={e=>update("graceMinutes",e.target.value)}/></Field><Field label={rtl?"ساعات العمل المطلوبة":"Required daily hours"}><input type="number" step="0.5" value={form.requiredDailyMinutes/60} onChange={e=>update("requiredDailyMinutes",Number(e.target.value)*60)}/></Field></div><Field label={rtl?"أيام العمل":"Working days"}><div className="day-selector">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map((d,i)=><label key={d}><input type="checkbox" defaultChecked={i<5}/><span>{d}</span></label>)}</div></Field><div className="info-card"><CalendarDays size={20}/><div><b>{rtl?"رصيد الإجازات":"Leave balance"}</b><p>{rtl?"سيُنشأ الرصيد تلقائياً وفق سياسة الدولة ومدة الخدمة بعد إنشاء الموظف.":"Balances will be generated automatically from country and service-length policies."}</p></div></div></>}
  {step===4&&<div className="review-card"><div className="review-person"><span className="avatar blue">{(form.nameEn||"NE").split(" ").map((x:string)=>x[0]).join("").slice(0,2)}</span><div><h3>{rtl?form.nameAr:form.nameEn}</h3><p>{form.workEmail}</p></div><span className="status green"><i/>{rtl?"جاهز للإنشاء":"Ready"}</span></div><div className="review-grid"><Review label={rtl?"القسم":"Department"} value={data?.departments.find(d=>String(d.id)===String(form.departmentId))?.[rtl?"name_ar":"name_en"]}/><Review label={rtl?"المسمى":"Job title"} value={data?.jobTitles.find(j=>String(j.id)===String(form.jobTitleId))?.[rtl?"name_ar":"name_en"]}/><Review label={rtl?"الدولة":"Country"} value={form.country}/><Review label={rtl?"تاريخ البداية":"Start date"} value={form.startDate}/><Review label={rtl?"الجدول":"Schedule"} value={`${form.checkInTime} — ${form.checkOutTime}`}/><Review label={rtl?"الحالة":"Status"} value={form.employmentStatus}/></div><div className="account-note"><KeyRound size={18}/><div><b>{rtl?"سيتم إنشاء حساب مستخدم مرتبط":"A linked user account will be created"}</b><small>{rtl?"الدور المبدئي: موظف — ويمكن تغييره لاحقاً.":"Initial role: Employee — it can be changed later."}</small></div></div></div>}</div>
  <div className="drawer-footer"><button className="ghost" onClick={close}>{rtl?"حفظ كمسودة":"Save draft"}</button><span/><button className="outline" onClick={()=>step===1?close():setStep(step-1)}>{step===1?(rtl?"إلغاء":"Cancel"):(rtl?"السابق":"Back")}</button>{step<4?<button className="primary" onClick={next}>{rtl?"التالي":"Continue"}<ChevronRight size={16}/></button>:<button className="primary" disabled={saving} onClick={()=>void finish()}>{saving?(rtl?"جارٍ الإنشاء...":"Creating..."):(rtl?"إنشاء الموظف":"Create employee")}<Check size={16}/></button>}</div></aside></div>;
}

function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function Review({label,value}:{label:string;value:any}){return <span><small>{label}</small><b>{value||"—"}</b></span>}

export function HolidayDrawer({rtl,close,submit}:{rtl:boolean;close:()=>void;submit:(form:Form)=>Promise<void>}){
  const [form,setForm]=useState<Form>({nameEn:"",nameAr:"",holidayDate:"",country:"Both",days:1,notes:""}); const [saving,setSaving]=useState(false),[error,setError]=useState("");
  const save=async()=>{if(!form.nameEn||!form.nameAr||!form.holidayDate){setError(rtl?"الاسم والتاريخ حقول مطلوبة":"Names and date are required");return;}try{setSaving(true);await submit(form);}catch(e){setError(e instanceof Error?e.message:"Unable to save holiday");setSaving(false);}};
  return <div className="modal-layer"><button className="modal-scrim" onClick={close}/><aside className="drawer"><div className="drawer-head"><div><span className="eyebrow">{rtl?"تقويم الشركة":"COMPANY CALENDAR"}</span><h2>{rtl?"إضافة عطلة رسمية":"Add official holiday"}</h2><p>{rtl?"ستدخل العطلة تلقائياً في حساب الحضور.":"The holiday will be included in attendance calculations."}</p></div><button className="icon-btn" onClick={close}><X size={20}/></button></div><div className="form-body">{error&&<div className="form-error">{error}</div>}<Field label={rtl?"الاسم بالعربية *":"Arabic name *"}><input value={form.nameAr} onChange={e=>setForm({...form,nameAr:e.target.value})}/></Field><Field label={rtl?"الاسم بالإنجليزية *":"English name *"}><input value={form.nameEn} onChange={e=>setForm({...form,nameEn:e.target.value})}/></Field><div className="form-row"><Field label={rtl?"التاريخ *":"Date *"}><input type="date" value={form.holidayDate} onChange={e=>setForm({...form,holidayDate:e.target.value})}/></Field><Field label={rtl?"عدد الأيام":"Number of days"}><input type="number" min="0.5" step="0.5" value={form.days} onChange={e=>setForm({...form,days:Number(e.target.value)})}/></Field></div><Field label={rtl?"تطبق على":"Applies to"}><select value={form.country} onChange={e=>setForm({...form,country:e.target.value})}><option>Both</option><option>Saudi Arabia</option><option>Egypt</option></select></Field><Field label={rtl?"ملاحظات":"Notes"}><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field></div><div className="drawer-footer"><span/><button className="outline" onClick={close}>{rtl?"إلغاء":"Cancel"}</button><button className="primary" disabled={saving} onClick={()=>void save()}>{saving?(rtl?"جارٍ الحفظ...":"Saving..."):(rtl?"حفظ العطلة":"Save holiday")}<Check size={16}/></button></div></aside></div>;
}
