"use client";
import {useCallback,useEffect,useState} from "react";
import {AlertTriangle,BookOpenCheck,CheckCircle2,ChevronRight,GraduationCap,Plus,RefreshCw,Search,ShieldCheck,Users,X} from "lucide-react";
import "./learning-workspace.css";

type Value=ReturnType<typeof JSON.parse>;type Row=Record<string,Value>;
const learningApi=async(payload?:Row):Promise<Row>=>{const response=await fetch("/api/learning",payload?{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}:{cache:"no-store"}),data=await response.json().catch(()=>({})) as Row;if(!response.ok)throw new Error(data.error||`Request failed (${response.status})`);return data};
const optionsApi=async():Promise<Row>=>{const response=await fetch("/api/talent/options",{cache:"no-store"}),data=await response.json().catch(()=>({})) as Row;if(!response.ok)throw new Error(data.error||"Unable to load options");return data};
const num=(value:unknown,rtl:boolean)=>new Intl.NumberFormat(rtl?"ar-EG":"en-US").format(Number(value)||0);
const dt=(value:unknown,rtl:boolean)=>value?new Intl.DateTimeFormat(rtl?"ar-EG":"en-US",{year:"numeric",month:"short",day:"numeric"}).format(new Date(`${String(value).slice(0,10)}T00:00:00`)):"—";
const courseType=(value:string,rtl:boolean)=>({internal:rtl?"تدريب داخلي":"Internal",external:rtl?"تدريب خارجي":"External",online:rtl?"تعلم إلكتروني":"Online"}[value]||value);
const trainingStatus=(value:string,rtl:boolean)=>({assigned:rtl?"تم التكليف":"Assigned",in_progress:rtl?"قيد التنفيذ":"In Progress",completed:rtl?"مكتمل":"Completed",failed:rtl?"لم يجتز":"Failed",cancelled:rtl?"ملغي":"Cancelled"}[value]||value);

export function LearningWorkspace({rtl,notify}:{rtl:boolean;notify:(message:string)=>void}){
 const [data,setData]=useState<Row>({courses:[],enrollments:[]}),[options,setOptions]=useState<Row>({employees:[]}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[query,setQuery]=useState(""),[courseOpen,setCourseOpen]=useState(false),[enrollOpen,setEnrollOpen]=useState(false),[referenceDate]=useState(()=>new Date());
 const load=useCallback(async()=>{setLoading(true);setError("");try{const [next,opts]=await Promise.all([learningApi(),optionsApi()]);setData(next);setOptions(opts)}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setLoading(false)}},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 const run=async(payload:Row,message:string)=>{setSaving(true);setError("");try{await learningApi(payload);notify(message);await load()}catch(reason){setError(reason instanceof Error?reason.message:String(reason));throw reason}finally{setSaving(false)}};
 const courses:Row[]=data.courses??[],enrollments:Row[]=data.enrollments??[],today=referenceDate.toISOString().slice(0,10),soon=new Date(referenceDate.getTime()+60*86400000).toISOString().slice(0,10),active=enrollments.filter(item=>["assigned","in_progress"].includes(item.status)),completed=enrollments.filter(item=>item.status==="completed"),overdue=active.filter(item=>item.due_date&&item.due_date<today),mandatoryPending=active.filter(item=>Number(item.mandatory)===1),expiring=enrollments.filter(item=>item.certificate_expiry&&item.certificate_expiry>=today&&item.certificate_expiry<=soon),completionRate=enrollments.length?Math.round(completed.length*100/enrollments.length):0,canManage=["Super Admin","HR Manager"].includes(String(data.actor?.roleName)),needle=query.trim().toLowerCase();
 const shownCourses=courses.filter(course=>!needle||[course.title,course.provider,course.course_type].some(value=>String(value||"").toLowerCase().includes(needle))),shownEnrollments=enrollments.filter(item=>!needle||[item.employee_name,item.employee_name_ar,item.employee_code,item.department_name,item.department_name_ar,item.course_title,item.status].some(value=>String(value||"").toLowerCase().includes(needle)));
 const kpis=[{label:rtl?"برامج تدريبية نشطة":"Active Programs",value:courses.filter(item=>item.status==="active").length,icon:GraduationCap,tone:"blue"},{label:rtl?"موظفون في تدريب حالي":"Employees in Training",value:new Set(active.map(item=>Number(item.employee_id))).size,icon:Users,tone:"violet"},{label:rtl?"تدريب إلزامي معلق":"Mandatory Training Pending",value:mandatoryPending.length,icon:ShieldCheck,tone:"amber"},{label:rtl?"تكليفات متأخرة":"Overdue Assignments",value:overdue.length,icon:AlertTriangle,tone:"rose"},{label:rtl?"نسبة إتمام التدريب":"Training Completion Rate",value:`${num(completionRate,rtl)}%`,icon:CheckCircle2,tone:"green"}];
 if(loading)return <div className="learning-loading"><RefreshCw/>{rtl?"جارٍ تحميل بيانات التدريب...":"Loading learning data..."}</div>;
 return <section className="learning-page">{error&&<div className="error-banner" role="alert">{error}<button onClick={()=>setError("")}><X size={16}/></button></div>}<header className="learning-heading"><div><span>{rtl?"التعلم والتطوير":"LEARNING & DEVELOPMENT"}</span><h1>{rtl?"مركز التدريب والتطوير":"Learning & Development Center"}</h1><p>{rtl?"رؤية موحدة للدورات، التزام الموظفين، نسب الإنجاز والشهادات.":"A unified view of programs, employee compliance, completion, and certificates."}</p></div><div><button className="outline" onClick={()=>void load()}><RefreshCw size={16}/>{rtl?"تحديث":"Refresh"}</button>{canManage&&<button className="outline" onClick={()=>setEnrollOpen(true)}><Users size={16}/>{rtl?"تكليف موظف بتدريب":"Assign Training"}</button>}{canManage&&<button className="primary" onClick={()=>setCourseOpen(true)}><Plus size={16}/>{rtl?"إضافة برنامج تدريبي":"Create Program"}</button>}</div></header><div className="learning-kpis">{kpis.map(item=>{const Icon=item.icon;return <article className={`learning-kpi ${item.tone}`} key={item.label}><span><Icon/></span><div><b>{typeof item.value==="number"?num(item.value,rtl):item.value}</b><small>{item.label}</small></div></article>})}</div>{(overdue.length>0||mandatoryPending.length>0||expiring.length>0)&&<section className="learning-attention"><header><AlertTriangle/><div><h2>{rtl?"يحتاج متابعة":"Needs Attention"}</h2><p>{rtl?"أهم عناصر التدريب التي تتطلب إجراءً الآن.":"Training items requiring action now."}</p></div></header><div><span><b>{num(overdue.length,rtl)}</b>{rtl?"تكليف متأخر":"Overdue"}</span><span><b>{num(mandatoryPending.length,rtl)}</b>{rtl?"إلزامي غير مكتمل":"Mandatory Pending"}</span><span><b>{num(expiring.length,rtl)}</b>{rtl?"شهادات تنتهي خلال ٦٠ يومًا":"Certificates Expiring"}</span></div></section>}<div className="learning-toolbar"><div><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder={rtl?"ابحث بالدورة أو الموظف أو القسم...":"Search program, employee, or department..."}/></div><span>{num(shownEnrollments.length,rtl)} {rtl?"سجل تدريب":"training records"}</span></div><LearningCourses rtl={rtl} courses={shownCourses}/><LearningEnrollments rtl={rtl} rows={shownEnrollments} today={today} saving={saving} run={run}/>{courseOpen&&<CourseModal rtl={rtl} saving={saving} close={()=>setCourseOpen(false)} submit={async form=>{await run({action:"create_course",...form},rtl?"تم إنشاء البرنامج التدريبي":"Training program created");setCourseOpen(false)}}/>}{enrollOpen&&<EnrollmentModal rtl={rtl} saving={saving} courses={courses.filter(item=>item.status==="active")} employees={options.employees??[]} close={()=>setEnrollOpen(false)} submit={async form=>{await run({action:"enroll",...form},rtl?"تم تكليف الموظف بالتدريب":"Employee assigned to training");setEnrollOpen(false)}}/>}</section>
}

function LearningCourses({rtl,courses}:{rtl:boolean;courses:Row[]}){return <section className="learning-panel"><header><div><h2>{rtl?"البرامج التدريبية":"Training Programs"}</h2><p>{rtl?"حالة كل برنامج، عدد المكلفين ونسبة الإتمام.":"Program status, assigned learners, and completion."}</p></div><span>{num(courses.length,rtl)}</span></header>{courses.length?<div className="learning-table-wrap"><table className="learning-table courses"><thead><tr><th>{rtl?"البرنامج":"Program"}</th><th>{rtl?"الجهة المقدمة":"Provider"}</th><th>{rtl?"التصنيف":"Delivery"}</th><th>{rtl?"الفترة":"Period"}</th><th>{rtl?"المكلفون":"Assigned"}</th><th>{rtl?"قيد التنفيذ":"In Progress"}</th><th>{rtl?"متأخر":"Overdue"}</th><th>{rtl?"الإنجاز":"Completion"}</th><th>{rtl?"الحالة":"Status"}</th></tr></thead><tbody>{courses.map(course=><tr key={course.id}><td><b>{course.title}</b>{Number(course.mandatory)===1&&<small className="mandatory-label">{rtl?"إلزامي":"Mandatory"}</small>}</td><td>{course.provider||"—"}</td><td>{courseType(course.course_type,rtl)}</td><td>{dt(course.start_date,rtl)}<small>{dt(course.end_date,rtl)}</small></td><td>{num(course.enrollment_count,rtl)}</td><td>{num(course.in_progress_count,rtl)}</td><td><span className={Number(course.overdue_count)>0?"learning-overdue":""}>{num(course.overdue_count,rtl)}</span></td><td><div className="learning-progress"><i><span style={{width:`${Math.min(100,Number(course.completion_rate)||0)}%`}}/></i><b>{num(course.completion_rate,rtl)}%</b></div></td><td><span className={`learning-status ${course.status}`}>{course.status==="active"?(rtl?"نشط":"Active"):(rtl?"مغلق":"Closed")}</span></td></tr>)}</tbody></table></div>:<LearningEmpty rtl={rtl}/>}</section>}

function LearningEnrollments({rtl,rows,today,saving,run}:{rtl:boolean;rows:Row[];today:string;saving:boolean;run:(payload:Row,message:string)=>Promise<void>}){return <section className="learning-panel"><header><div><h2>{rtl?"متابعة تدريب الموظفين":"Employee Training Tracker"}</h2><p>{rtl?"اعرف من بدأ، ومن تأخر، ومن أتم التدريب والشهادة المرتبطة به.":"Track starts, overdue assignments, completions, and certificate validity."}</p></div><span>{num(rows.length,rtl)}</span></header>{rows.length?<div className="learning-table-wrap"><table className="learning-table enrollments"><thead><tr><th>{rtl?"الموظف":"Employee"}</th><th>{rtl?"القسم":"Department"}</th><th>{rtl?"البرنامج":"Program"}</th><th>{rtl?"تاريخ الاستحقاق":"Due Date"}</th><th>{rtl?"الحالة":"Status"}</th><th>{rtl?"النتيجة":"Score"}</th><th>{rtl?"صلاحية الشهادة":"Certificate Expiry"}</th><th>{rtl?"الإجراء":"Action"}</th></tr></thead><tbody>{rows.map(row=>{const overdue=["assigned","in_progress"].includes(row.status)&&row.due_date&&row.due_date<today;return <tr className={overdue?"overdue-row":""} key={row.id}><td><b>{rtl?row.employee_name_ar:row.employee_name}</b><small>{row.employee_code}</small></td><td>{rtl?(row.department_name_ar||row.department_name):row.department_name||"—"}</td><td><b>{row.course_title}</b>{Number(row.mandatory)===1&&<small className="mandatory-label">{rtl?"إلزامي":"Mandatory"}</small>}</td><td>{dt(row.due_date,rtl)}{overdue&&<small className="overdue-text">{rtl?"متأخر":"Overdue"}</small>}</td><td><span className={`training-status ${row.status}`}>{trainingStatus(row.status,rtl)}</span></td><td>{row.score??"—"}</td><td>{dt(row.certificate_expiry,rtl)}</td><td><div className="learning-actions">{row.status==="assigned"&&<button disabled={saving} onClick={()=>void run({action:"update_enrollment",enrollmentId:row.id,status:"in_progress"},rtl?"تم بدء التدريب":"Training started")}>{rtl?"بدء التدريب":"Start"}<ChevronRight/></button>}{["assigned","in_progress"].includes(row.status)&&<button className="complete" disabled={saving} onClick={()=>void run({action:"update_enrollment",enrollmentId:row.id,status:"completed",completionDate:today},rtl?"تم اعتماد إتمام التدريب":"Training completion approved")}>{rtl?"اعتماد الإتمام":"Complete"}<CheckCircle2/></button>}</div></td></tr>})}</tbody></table></div>:<LearningEmpty rtl={rtl}/>}</section>}

function CourseModal({rtl,saving,close,submit}:{rtl:boolean;saving:boolean;close:()=>void;submit:(form:Row)=>Promise<void>}){const [form,setForm]=useState<Row>({courseType:"internal",mandatory:false});return <div className="learning-modal-layer"><button className="learning-scrim" onClick={close} aria-label={rtl?"إغلاق":"Close"}/><form className="learning-modal" onSubmit={event=>{event.preventDefault();void submit(form)}}><header><div><span>{rtl?"برنامج تدريبي جديد":"NEW TRAINING PROGRAM"}</span><h2>{rtl?"إضافة برنامج تدريبي":"Create Training Program"}</h2><p>{rtl?"عرّف محتوى التدريب ومدته ومتطلبات صلاحيته.":"Define delivery, dates, and certificate validity."}</p></div><button type="button" onClick={close}><X/></button></header><div className="learning-modal-body"><label className="wide"><span>{rtl?"اسم البرنامج":"Program Name"}</span><input required value={form.title||""} onChange={event=>setForm({...form,title:event.target.value})}/></label><label><span>{rtl?"الجهة المقدمة":"Provider"}</span><input value={form.provider||""} onChange={event=>setForm({...form,provider:event.target.value})}/></label><label><span>{rtl?"طريقة التقديم":"Delivery Method"}</span><select value={form.courseType} onChange={event=>setForm({...form,courseType:event.target.value})}><option value="internal">{courseType("internal",rtl)}</option><option value="external">{courseType("external",rtl)}</option><option value="online">{courseType("online",rtl)}</option></select></label><label><span>{rtl?"تاريخ البداية":"Start Date"}</span><input type="date" value={form.startDate||""} onChange={event=>setForm({...form,startDate:event.target.value})}/></label><label><span>{rtl?"تاريخ النهاية":"End Date"}</span><input type="date" value={form.endDate||""} onChange={event=>setForm({...form,endDate:event.target.value})}/></label><label><span>{rtl?"صلاحية الشهادة بالأشهر":"Certificate Validity (Months)"}</span><input type="number" min="1" value={form.validityMonths||""} onChange={event=>setForm({...form,validityMonths:Number(event.target.value)})}/></label><label className="learning-check"><input type="checkbox" checked={Boolean(form.mandatory)} onChange={event=>setForm({...form,mandatory:event.target.checked})}/><span>{rtl?"برنامج إلزامي":"Mandatory program"}</span></label><label className="wide"><span>{rtl?"وصف البرنامج ومخرجاته":"Description & Outcomes"}</span><textarea rows={4} value={form.description||""} onChange={event=>setForm({...form,description:event.target.value})}/></label></div><footer><button type="button" className="outline" onClick={close}>{rtl?"إلغاء":"Cancel"}</button><button className="primary" disabled={saving}>{rtl?"إنشاء البرنامج":"Create Program"}</button></footer></form></div>}

function EnrollmentModal({rtl,saving,courses,employees,close,submit}:{rtl:boolean;saving:boolean;courses:Row[];employees:Row[];close:()=>void;submit:(form:Row)=>Promise<void>}){const [form,setForm]=useState<Row>({});const selected=courses.find(course=>Number(course.id)===Number(form.courseId));return <div className="learning-modal-layer"><button className="learning-scrim" onClick={close} aria-label={rtl?"إغلاق":"Close"}/><form className="learning-modal compact" onSubmit={event=>{event.preventDefault();void submit({courseId:Number(form.courseId),employeeId:Number(form.employeeId),dueDate:form.dueDate})}}><header><div><span>{rtl?"تكليف تدريبي":"TRAINING ASSIGNMENT"}</span><h2>{rtl?"تكليف موظف ببرنامج تدريبي":"Assign Employee to Training"}</h2><p>{rtl?"اختر البرنامج والموظف وحدد الموعد المطلوب للإتمام.":"Select the program, employee, and completion deadline."}</p></div><button type="button" onClick={close}><X/></button></header><div className="learning-modal-body"><label className="wide"><span>{rtl?"البرنامج التدريبي":"Training Program"}</span><select required value={form.courseId||""} onChange={event=>{const course=courses.find(item=>Number(item.id)===Number(event.target.value));setForm({...form,courseId:event.target.value,dueDate:course?.end_date||form.dueDate})}}><option value="">—</option>{courses.map(course=><option value={course.id} key={course.id}>{course.title}{Number(course.mandatory)===1?` · ${rtl?"إلزامي":"Mandatory"}`:""}</option>)}</select></label><label className="wide"><span>{rtl?"الموظف":"Employee"}</span><select required value={form.employeeId||""} onChange={event=>setForm({...form,employeeId:event.target.value})}><option value="">—</option>{employees.map(employee=><option value={employee.id} key={employee.id}>{rtl?employee.name_ar:employee.name_en} · {employee.employee_code}</option>)}</select></label><label className="wide"><span>{rtl?"موعد الإتمام":"Due Date"}</span><input required type="date" value={form.dueDate||selected?.end_date||""} onChange={event=>setForm({...form,dueDate:event.target.value})}/></label></div><footer><button type="button" className="outline" onClick={close}>{rtl?"إلغاء":"Cancel"}</button><button className="primary" disabled={saving}>{rtl?"تأكيد التكليف":"Assign Training"}</button></footer></form></div>}

function LearningEmpty({rtl}:{rtl:boolean}){return <div className="learning-empty"><BookOpenCheck/><b>{rtl?"لا توجد بيانات تدريبية":"No training data"}</b><span>{rtl?"ستظهر البرامج وسجلات الموظفين هنا.":"Programs and employee records will appear here."}</span></div>}
