import type { Seniority } from './policy.ts';

/** Shared vocabulary for the default blueprints: [English, Arabic, seniority, English description, Arabic description]. */
export type TitleDef = readonly [string, string, Seniority, string, string];

export const UNITS: Record<string, readonly [string, string]> = {
  management: ['Executive Management', 'الإدارة التنفيذية'], engineering: ['Software Engineering', 'هندسة البرمجيات'], product: ['Product & Design', 'المنتج والتصميم'],
  it: ['IT', 'تقنية المعلومات'], hr: ['Human Resources', 'الموارد البشرية'], finance: ['Finance', 'المالية'], sales: ['Sales', 'المبيعات'], marketing: ['Marketing', 'التسويق'],
  customer: ['Customer Success & Support', 'نجاح العملاء والدعم'], operations: ['Operations', 'العمليات'], admin: ['Administration', 'الشؤون الإدارية'], legal: ['Legal & Compliance', 'الشؤون القانونية والامتثال'],
  procurement: ['Procurement', 'المشتريات'], delivery: ['Delivery & Projects', 'التنفيذ والمشاريع'], stores: ['Stores & Branches', 'المتاجر والفروع'], warehouse: ['Warehouse & Inventory', 'المخازن والمخزون'],
  ecommerce: ['E-commerce', 'التجارة الإلكترونية'], fulfillment: ['Fulfillment', 'التجهيز والشحن'], creative: ['Creative', 'الإبداع'], accounts: ['Client Services', 'خدمة العملاء التجارية'],
  media: ['Media & Performance', 'الوسائط والأداء'], projects: ['Project Management', 'إدارة المشاريع'], technical: ['Engineering & Technical Office', 'المكتب الفني والهندسة'], site: ['Site Operations', 'عمليات المواقع'],
  hse: ['Health, Safety & Environment', 'الصحة والسلامة والبيئة'], production: ['Production', 'الإنتاج'], quality: ['Quality', 'الجودة'], maintenance: ['Maintenance', 'الصيانة'], supply: ['Supply Chain', 'سلسلة الإمداد'],
  kitchen: ['Kitchen', 'المطبخ'], service: ['Front of House', 'خدمة الصالة'], rooms: ['Rooms & Front Office', 'الغرف والاستقبال'], fleet: ['Fleet & Transport', 'الأسطول والنقل'], clinical: ['Clinical Services', 'الخدمات الطبية'],
  nursing: ['Nursing', 'التمريض'], diagnostics: ['Laboratory & Diagnostics', 'المختبر والتشخيص'], pharmacy: ['Pharmacy', 'الصيدلية'], consulting: ['Consulting Practice', 'الاستشارات'], trading: ['Trading', 'التجارة'],
  // teams
  backend: ['Backend Team', 'فريق الخلفية'], frontend: ['Frontend Team', 'فريق الواجهات'], mobile: ['Mobile Team', 'فريق الجوال'], qa: ['Quality Assurance', 'ضمان الجودة'], devops: ['DevOps / SRE', 'العمليات التقنية (DevOps)'],
  data: ['Data & AI', 'البيانات والذكاء الاصطناعي'], security: ['Security', 'الأمن السيبراني'], design: ['Design', 'التصميم'], recruitment: ['Recruitment', 'الاستقطاب'], payroll: ['Payroll & Benefits', 'الرواتب والمزايا'],
  accounting: ['Accounting', 'المحاسبة'], digital: ['Digital Marketing', 'التسويق الرقمي'], content: ['Content', 'المحتوى'], inside: ['Inside Sales', 'المبيعات الداخلية'], field: ['Field Sales', 'المبيعات الميدانية'],
  support: ['Support', 'الدعم'], infra: ['Infrastructure', 'البنية التحتية'], helpdesk: ['Helpdesk', 'مكتب المساعدة'], civil: ['Civil Works', 'الأعمال المدنية'], mep: ['MEP Works', 'الأعمال الكهروميكانيكية'],
  line: ['Production Lines', 'خطوط الإنتاج'], hotline: ['Hot Kitchen', 'المطبخ الساخن'], cold: ['Cold Kitchen & Pastry', 'المطبخ البارد والحلويات'], housekeeping: ['Housekeeping', 'التدبير الفندقي'],
  dispatch: ['Dispatch', 'التوجيه'], drivers: ['Drivers', 'السائقون'], doctors: ['Physicians', 'الأطباء'], nurses: ['Nurses', 'الممرضون'], buying: ['Buying', 'الشراء'],
};

export const TITLES: Record<string, TitleDef> = {
  // executive
  ceo: ['CEO', 'الرئيس التنفيذي', 'executive', 'Sets strategy and is accountable for the whole company.', 'يضع الاستراتيجية ويتحمل مسؤولية الشركة بالكامل.'],
  coo: ['COO', 'رئيس العمليات', 'executive', 'Runs day-to-day operations across departments.', 'يدير العمليات اليومية عبر الإدارات.'],
  gm: ['General Manager', 'المدير العام', 'executive', 'Leads the business and its daily operations.', 'يقود النشاط وعملياته اليومية.'],
  cfo: ['CFO', 'المدير المالي التنفيذي', 'executive', 'Owns financial strategy, reporting and control.', 'يتولى الاستراتيجية المالية والتقارير والرقابة.'],
  managing_partner: ['Managing Partner', 'الشريك الإداري', 'executive', 'Leads the firm and its key client relationships.', 'يقود المكتب وعلاقات العملاء الرئيسية.'],
  medical_director: ['Medical Director', 'المدير الطبي', 'executive', 'Accountable for clinical quality and safety.', 'مسؤول عن الجودة والسلامة الطبية.'],
  // engineering
  cto: ['CTO / Head of Engineering', 'رئيس التقنية / رئيس الهندسة', 'director', 'Owns technology direction and the engineering organization.', 'يقود التوجه التقني ومنظومة الهندسة.'],
  eng_mgr: ['Engineering Manager', 'مدير هندسة البرمجيات', 'manager', 'Manages engineers, delivery and team health.', 'يدير المهندسين والتسليم وصحة الفرق.'],
  tech_lead: ['Tech Lead', 'قائد فني', 'lead', 'Guides technical design and code quality for a team.', 'يوجّه التصميم التقني وجودة الكود لفريق.'],
  sr_backend: ['Senior Backend Developer', 'مطور خلفية أول', 'senior', 'Designs and builds services and APIs.', 'يصمم وينفذ الخدمات وواجهات البرمجة.'],
  backend: ['Backend Developer', 'مطور خلفية', 'mid', 'Builds and maintains server-side features.', 'ينفذ ويصون ميزات الخادم.'],
  sr_frontend: ['Senior Frontend Developer', 'مطور واجهات أول', 'senior', 'Leads complex user-interface work.', 'يقود أعمال الواجهات المعقدة.'],
  frontend: ['Frontend Developer', 'مطور واجهات', 'mid', 'Builds the web user interface.', 'ينفذ واجهة المستخدم للويب.'],
  mobile_dev: ['Mobile Developer', 'مطور تطبيقات جوال', 'mid', 'Builds iOS and Android apps.', 'ينفذ تطبيقات iOS وAndroid.'],
  qa_lead: ['QA Lead', 'قائد ضمان الجودة', 'lead', 'Defines the test strategy and leads testers.', 'يحدد استراتيجية الاختبار ويقود المختبرين.'],
  qa: ['QA Engineer', 'مهندس ضمان الجودة', 'mid', 'Tests features and automates checks.', 'يختبر الميزات ويؤتمت الفحوصات.'],
  devops: ['DevOps Engineer', 'مهندس DevOps', 'mid', 'Builds pipelines and runs environments.', 'يبني خطوط النشر ويدير البيئات.'],
  sre: ['Site Reliability Engineer', 'مهندس موثوقية الأنظمة', 'senior', 'Keeps production reliable and observable.', 'يحافظ على موثوقية الإنتاج وإمكانية مراقبته.'],
  security_eng: ['Security Engineer', 'مهندس أمن المعلومات', 'senior', 'Secures applications and infrastructure.', 'يؤمّن التطبيقات والبنية التحتية.'],
  data_eng: ['Data Engineer', 'مهندس بيانات', 'mid', 'Builds data pipelines and models.', 'يبني خطوط البيانات ونماذجها.'],
  ml_eng: ['ML Engineer', 'مهندس تعلم آلة', 'senior', 'Builds and ships machine-learning features.', 'يبني ويطلق ميزات تعلم الآلة.'],
  // product & design
  pm: ['Product Manager', 'مدير منتج', 'manager', 'Owns the product roadmap and outcomes.', 'يملك خارطة المنتج ونتائجه.'],
  po: ['Product Owner', 'مالك منتج', 'mid', 'Prioritizes the backlog for a team.', 'يرتب أولويات العمل لفريق.'],
  uiux: ['UI/UX Designer', 'مصمم واجهات وتجربة مستخدم', 'mid', 'Designs user flows and interfaces.', 'يصمم مسارات المستخدم والواجهات.'],
  ba: ['Business Analyst', 'محلل أعمال', 'mid', 'Turns business needs into requirements.', 'يحوّل احتياجات العمل إلى متطلبات.'],
  design_lead: ['Design Lead', 'قائد التصميم', 'lead', 'Leads design quality and the design team.', 'يقود جودة التصميم وفريقه.'],
  // IT
  it_mgr: ['IT Manager', 'مدير تقنية المعلومات', 'manager', 'Manages internal systems, support and IT security.', 'يدير الأنظمة الداخلية والدعم وأمن المعلومات.'],
  sysadmin: ['System Administrator', 'مسؤول أنظمة', 'mid', 'Administers servers, accounts and backups.', 'يدير الخوادم والحسابات والنسخ الاحتياطي.'],
  network_eng: ['Network Engineer', 'مهندس شبكات', 'mid', 'Designs and maintains the network.', 'يصمم الشبكة ويصونها.'],
  it_support: ['IT Support', 'دعم فني', 'junior', 'Helps staff with devices and software.', 'يساعد الموظفين في الأجهزة والبرامج.'],
  security_analyst: ['Security Analyst', 'محلل أمن معلومات', 'mid', 'Monitors threats and enforces policies.', 'يراقب التهديدات ويطبق السياسات.'],
  // HR
  hr_mgr: ['HR Manager', 'مدير الموارد البشرية', 'manager', 'Leads people operations and policy.', 'يقود عمليات وسياسات شؤون الموظفين.'],
  hr_spec: ['HR Specialist', 'أخصائي موارد بشرية', 'mid', 'Handles employee records, onboarding and relations.', 'يتولى ملفات الموظفين والمباشرة وعلاقات العمل.'],
  recruiter: ['Recruiter', 'أخصائي استقطاب', 'mid', 'Sources and hires candidates.', 'يبحث عن المرشحين ويوظفهم.'],
  payroll_spec: ['Payroll Specialist', 'أخصائي رواتب', 'mid', 'Prepares payroll and benefits.', 'يعد الرواتب والمزايا.'],
  training_spec: ['Training Specialist', 'أخصائي تدريب', 'mid', 'Plans and delivers staff training.', 'يخطط للتدريب وينفذه.'],
  // finance
  fin_mgr: ['Finance Manager', 'مدير مالي', 'manager', 'Leads accounting, budgeting and reporting.', 'يقود المحاسبة والموازنات والتقارير.'],
  chief_accountant: ['Chief Accountant', 'رئيس حسابات', 'lead', 'Oversees books, closing and statutory reporting.', 'يشرف على الدفاتر والإقفال والتقارير النظامية.'],
  accountant: ['Accountant', 'محاسب', 'mid', 'Records transactions and prepares reports.', 'يسجل القيود ويعد التقارير.'],
  ap_ar: ['Accounts Payable / Receivable Clerk', 'موظف حسابات دائنة ومدينة', 'junior', 'Processes invoices and collections.', 'يعالج الفواتير والتحصيل.'],
  fin_analyst: ['Financial Analyst', 'محلل مالي', 'mid', 'Analyzes performance and builds forecasts.', 'يحلل الأداء ويعد التوقعات.'],
  // sales
  sales_mgr: ['Sales Manager', 'مدير مبيعات', 'manager', 'Leads the sales team and targets.', 'يقود فريق المبيعات وأهدافه.'],
  sales_exec: ['Sales Executive', 'مسؤول مبيعات', 'mid', 'Wins and grows customer accounts.', 'يكسب العملاء وينمّي حساباتهم.'],
  account_mgr: ['Account Manager', 'مدير حسابات', 'senior', 'Owns relationships with key customers.', 'يملك العلاقة مع العملاء الرئيسيين.'],
  bd_mgr: ['Business Development Manager', 'مدير تطوير الأعمال', 'manager', 'Finds partnerships and new markets.', 'يبحث عن الشراكات والأسواق الجديدة.'],
  presales: ['Presales Engineer', 'مهندس ما قبل البيع', 'senior', 'Supports sales with technical solutions.', 'يدعم المبيعات بحلول تقنية.'],
  // marketing
  mkt_mgr: ['Marketing Manager', 'مدير تسويق', 'manager', 'Leads marketing strategy and campaigns.', 'يقود الاستراتيجية والحملات التسويقية.'],
  digital_mkt: ['Digital Marketing Specialist', 'أخصائي تسويق رقمي', 'mid', 'Runs online campaigns and analytics.', 'يدير الحملات الرقمية والتحليلات.'],
  content: ['Content Creator', 'صانع محتوى', 'mid', 'Produces written, visual and video content.', 'ينتج محتوى مكتوبًا ومرئيًا.'],
  seo: ['SEO Specialist', 'أخصائي محركات البحث', 'mid', 'Improves organic search visibility.', 'يحسّن ظهور الموقع في نتائج البحث.'],
  graphic: ['Graphic Designer', 'مصمم جرافيك', 'mid', 'Creates visual designs and brand assets.', 'ينشئ التصاميم والهوية البصرية.'],
  social: ['Social Media Specialist', 'أخصائي وسائل التواصل', 'mid', 'Manages social channels and community.', 'يدير قنوات التواصل والمجتمع.'],
  // customer
  cs_mgr: ['Customer Success Manager', 'مدير نجاح العملاء', 'manager', 'Drives retention and customer outcomes.', 'يدعم احتفاظ العملاء ونتائجهم.'],
  cs_exec: ['Customer Success Executive', 'مسؤول نجاح العملاء', 'mid', 'Onboards and supports customer accounts.', 'يهيئ العملاء ويدعم حساباتهم.'],
  support_agent: ['Customer Support Agent', 'ممثل دعم العملاء', 'junior', 'Answers customer requests and issues.', 'يرد على طلبات العملاء ومشكلاتهم.'],
  // ops/admin
  ops_mgr: ['Operations Manager', 'مدير عمليات', 'manager', 'Runs daily operations and process quality.', 'يدير العمليات اليومية وجودة الإجراءات.'],
  ops_coord: ['Operations Coordinator', 'منسق عمليات', 'junior', 'Coordinates schedules, orders and follow-ups.', 'ينسق الجداول والطلبات والمتابعات.'],
  office_mgr: ['Office Manager', 'مدير مكتب', 'manager', 'Runs the office, facilities and admin support.', 'يدير المكتب والمرافق والدعم الإداري.'],
  admin_assistant: ['Administrative Assistant', 'مساعد إداري', 'entry', 'Provides clerical and scheduling support.', 'يقدم الدعم الكتابي والتنسيق.'],
  receptionist: ['Receptionist', 'موظف استقبال', 'entry', 'Welcomes visitors and handles calls.', 'يستقبل الزوار ويتعامل مع المكالمات.'],
  legal_counsel: ['Legal Counsel', 'مستشار قانوني', 'senior', 'Advises on contracts and compliance.', 'يقدم المشورة في العقود والامتثال.'],
  compliance_officer: ['Compliance Officer', 'مسؤول امتثال', 'mid', 'Monitors regulatory compliance.', 'يتابع الامتثال للأنظمة.'],
  procurement_mgr: ['Procurement Manager', 'مدير مشتريات', 'manager', 'Leads sourcing and supplier management.', 'يقود التوريد وإدارة الموردين.'],
  purchaser: ['Purchasing Officer', 'مسؤول مشتريات', 'mid', 'Places orders and negotiates with suppliers.', 'ينفذ الطلبات ويتفاوض مع الموردين.'],
  // project delivery / IT services
  delivery_mgr: ['Delivery Manager', 'مدير تسليم', 'manager', 'Owns delivery across client projects.', 'يملك التسليم عبر مشاريع العملاء.'],
  project_mgr: ['Project Manager', 'مدير مشروع', 'manager', 'Plans and delivers projects on time and budget.', 'يخطط المشاريع وينفذها في وقتها وميزانيتها.'],
  solution_architect: ['Solution Architect', 'مهندس حلول', 'senior', 'Designs end-to-end technical solutions.', 'يصمم الحلول التقنية المتكاملة.'],
  consultant: ['Consultant', 'مستشار', 'mid', 'Delivers advisory work for clients.', 'ينفذ أعمالًا استشارية للعملاء.'],
  sr_consultant: ['Senior Consultant', 'مستشار أول', 'senior', 'Leads engagements and mentors consultants.', 'يقود المهام ويوجّه المستشارين.'],
  analyst: ['Analyst', 'محلل', 'junior', 'Researches and prepares analysis for engagements.', 'يبحث ويعد التحليلات للمهام.'],
  // retail / e-commerce
  store_mgr: ['Store Manager', 'مدير متجر', 'manager', 'Runs a store: sales, staff and stock.', 'يدير المتجر: المبيعات والفريق والمخزون.'],
  asst_store_mgr: ['Assistant Store Manager', 'مساعد مدير متجر', 'lead', 'Supports the store manager and covers shifts.', 'يساند مدير المتجر ويغطي الورديات.'],
  sales_assoc: ['Sales Associate', 'بائع', 'entry', 'Serves customers on the shop floor.', 'يخدم العملاء في صالة البيع.'],
  cashier: ['Cashier', 'أمين صندوق', 'entry', 'Handles payments and the till.', 'يتولى المدفوعات والصندوق.'],
  merchandiser: ['Visual Merchandiser', 'منسق عرض بصري', 'mid', 'Plans displays and store layout.', 'يخطط العرض وتنسيق المتجر.'],
  buyer: ['Buyer', 'مشتري بضائع', 'senior', 'Selects and negotiates product ranges.', 'يختار الأصناف ويتفاوض عليها.'],
  inventory_clerk: ['Inventory Clerk', 'أمين مخزون', 'junior', 'Counts, receives and records stock.', 'يجرد ويستلم ويسجل المخزون.'],
  ecom_mgr: ['E-commerce Manager', 'مدير تجارة إلكترونية', 'manager', 'Owns the online store and its growth.', 'يملك المتجر الإلكتروني ونموه.'],
  catalog_spec: ['Catalog Specialist', 'أخصائي كتالوج', 'mid', 'Maintains product listings and content.', 'يصون بيانات المنتجات ومحتواها.'],
  category_mgr: ['Category Manager', 'مدير فئة', 'senior', 'Owns assortment and margin of a category.', 'يملك تشكيلة الفئة وهامشها.'],
  performance_mkt: ['Performance Marketer', 'أخصائي إعلانات الأداء', 'mid', 'Buys and optimizes paid media.', 'يشتري الإعلانات المدفوعة ويحسّنها.'],
  fulfillment_mgr: ['Fulfillment Manager', 'مدير التجهيز', 'manager', 'Runs picking, packing and dispatch.', 'يدير الانتقاء والتغليف والشحن.'],
  picker: ['Picker / Packer', 'عامل تجهيز طلبات', 'entry', 'Picks and packs customer orders.', 'ينتقي الطلبات ويغلفها.'],
  // agency
  creative_dir: ['Creative Director', 'مدير إبداعي', 'director', 'Leads creative concepts and quality.', 'يقود الأفكار الإبداعية وجودتها.'],
  strategist: ['Brand Strategist', 'استراتيجي علامات', 'senior', 'Builds strategy behind campaigns.', 'يبني الاستراتيجية خلف الحملات.'],
  copywriter: ['Copywriter', 'كاتب إعلانات', 'mid', 'Writes campaign and brand copy.', 'يكتب نصوص الحملات والعلامة.'],
  motion: ['Motion Designer', 'مصمم موشن', 'mid', 'Creates animation and video graphics.', 'ينتج الرسوم المتحركة وجرافيك الفيديو.'],
  media_buyer: ['Media Buyer', 'مشتري وسائط', 'mid', 'Plans and buys advertising space.', 'يخطط للمساحات الإعلانية ويشتريها.'],
  client_dir: ['Client Services Director', 'مدير خدمة العملاء التجارية', 'director', 'Leads client relationships and retention.', 'يقود علاقات العملاء واستبقاءهم.'],
  // construction
  project_director: ['Project Director', 'مدير مشاريع تنفيذي', 'director', 'Accountable for the project portfolio.', 'مسؤول عن محفظة المشاريع.'],
  site_engineer: ['Site Engineer', 'مهندس موقع', 'mid', 'Supervises works on site against drawings.', 'يشرف على الأعمال بالموقع وفق المخططات.'],
  civil_engineer: ['Civil Engineer', 'مهندس مدني', 'mid', 'Designs and checks structural and civil works.', 'يصمم الأعمال المدنية والإنشائية ويراجعها.'],
  mep_engineer: ['MEP Engineer', 'مهندس كهروميكانيك', 'mid', 'Coordinates mechanical, electrical and plumbing works.', 'ينسق الأعمال الميكانيكية والكهربائية والصحية.'],
  qs: ['Quantity Surveyor', 'مهندس كميات', 'mid', 'Measures quantities, costs and payments.', 'يحصر الكميات والتكاليف والمستخلصات.'],
  planner: ['Project Planner', 'مخطط مشاريع', 'mid', 'Builds and tracks project schedules.', 'يعد الجداول الزمنية ويتابعها.'],
  site_supervisor: ['Site Supervisor', 'مشرف موقع', 'lead', 'Directs crews and daily site work.', 'يوجّه الفرق والعمل اليومي بالموقع.'],
  foreman: ['Foreman', 'مراقب عمال', 'lead', 'Leads a trade crew.', 'يقود طاقم حرفة.'],
  cad: ['CAD Technician', 'فني رسم هندسي', 'junior', 'Prepares drawings and as-builts.', 'يعد المخططات والمخططات التنفيذية.'],
  hse_officer: ['HSE Officer', 'مسؤول سلامة وصحة وبيئة', 'mid', 'Enforces safety and environmental rules.', 'يطبق قواعد السلامة والبيئة.'],
  skilled_worker: ['Skilled Worker', 'عامل ماهر', 'entry', 'Performs trade work on site.', 'ينفذ أعمال الحرفة بالموقع.'],
  // manufacturing
  plant_mgr: ['Plant Manager', 'مدير المصنع', 'director', 'Accountable for plant output, cost and safety.', 'مسؤول عن إنتاج المصنع وتكلفته وسلامته.'],
  production_mgr: ['Production Manager', 'مدير إنتاج', 'manager', 'Plans and runs production.', 'يخطط الإنتاج ويديره.'],
  production_sup: ['Production Supervisor', 'مشرف إنتاج', 'lead', 'Supervises a shift or line.', 'يشرف على وردية أو خط إنتاج.'],
  operator: ['Machine Operator', 'مشغل ماكينة', 'entry', 'Operates production machines.', 'يشغل ماكينات الإنتاج.'],
  process_eng: ['Process Engineer', 'مهندس عمليات', 'senior', 'Improves processes and yield.', 'يحسّن العمليات والإنتاجية.'],
  quality_mgr: ['Quality Manager', 'مدير جودة', 'manager', 'Owns the quality system and audits.', 'يملك نظام الجودة والمراجعات.'],
  qc_inspector: ['QC Inspector', 'مفتش مراقبة جودة', 'junior', 'Inspects products against standards.', 'يفحص المنتجات وفق المعايير.'],
  maint_mgr: ['Maintenance Manager', 'مدير صيانة', 'manager', 'Keeps equipment available and safe.', 'يحافظ على جاهزية المعدات وسلامتها.'],
  technician: ['Maintenance Technician', 'فني صيانة', 'mid', 'Repairs and services equipment.', 'يصلح المعدات ويصونها.'],
  supply_mgr: ['Supply Chain Manager', 'مدير سلسلة الإمداد', 'manager', 'Plans materials, suppliers and logistics.', 'يخطط المواد والموردين والخدمات اللوجستية.'],
  wh_mgr: ['Warehouse Manager', 'مدير مخازن', 'manager', 'Runs warehouse receiving, storage and dispatch.', 'يدير الاستلام والتخزين والصرف.'],
  wh_worker: ['Warehouse Worker', 'عامل مخزن', 'entry', 'Receives, stores and moves goods.', 'يستلم البضائع ويخزنها وينقلها.'],
  // hospitality
  restaurant_mgr: ['Restaurant Manager', 'مدير مطعم', 'manager', 'Runs service, staff and guest experience.', 'يدير الخدمة والفريق وتجربة الضيوف.'],
  head_chef: ['Head Chef', 'رئيس الطهاة', 'manager', 'Leads the kitchen, menu and food cost.', 'يقود المطبخ وقائمة الطعام وتكلفتها.'],
  sous_chef: ['Sous Chef', 'مساعد رئيس الطهاة', 'lead', 'Runs the line and supports the head chef.', 'يدير الخط ويساند رئيس الطهاة.'],
  cook: ['Cook', 'طاهٍ', 'mid', 'Prepares dishes to standard.', 'يحضّر الأطباق وفق المعيار.'],
  waiter: ['Waiter / Waitress', 'نادل', 'entry', 'Serves guests at the table.', 'يخدم الضيوف على الطاولات.'],
  host: ['Host / Hostess', 'مضيف استقبال', 'entry', 'Greets and seats guests.', 'يستقبل الضيوف ويجلسهم.'],
  kitchen_helper: ['Kitchen Helper', 'مساعد مطبخ', 'entry', 'Preps ingredients and keeps the kitchen clean.', 'يجهز المكونات ويحافظ على نظافة المطبخ.'],
  front_office_mgr: ['Front Office Manager', 'مدير مكتب الاستقبال', 'manager', 'Runs reception, bookings and guest requests.', 'يدير الاستقبال والحجوزات وطلبات النزلاء.'],
  housekeeping_mgr: ['Housekeeping Manager', 'مدير التدبير الفندقي', 'manager', 'Leads room cleaning and linen.', 'يقود نظافة الغرف والمفروشات.'],
  housekeeper: ['Room Attendant', 'عامل غرف', 'entry', 'Cleans and prepares guest rooms.', 'ينظف غرف النزلاء ويجهزها.'],
  // logistics
  fleet_mgr: ['Fleet Manager', 'مدير أسطول', 'manager', 'Manages vehicles, maintenance and drivers.', 'يدير المركبات وصيانتها والسائقين.'],
  dispatcher: ['Dispatcher', 'منسق توجيه', 'mid', 'Assigns jobs and routes in real time.', 'يوزع المهام والمسارات لحظيًا.'],
  driver: ['Driver', 'سائق', 'entry', 'Transports goods safely and on time.', 'ينقل البضائع بأمان وفي موعدها.'],
  customs_spec: ['Customs Clearance Specialist', 'أخصائي تخليص جمركي', 'mid', 'Handles customs documents and clearance.', 'يتولى مستندات التخليص الجمركي وإجراءاته.'],
  freight_coord: ['Freight Coordinator', 'منسق شحن', 'mid', 'Books and tracks shipments.', 'يحجز الشحنات ويتتبعها.'],
  // healthcare
  nursing_mgr: ['Nursing Manager', 'مدير التمريض', 'manager', 'Leads nursing staff and standards of care.', 'يقود طاقم التمريض ومعايير الرعاية.'],
  physician: ['Physician', 'طبيب', 'senior', 'Diagnoses and treats patients.', 'يشخّص المرضى ويعالجهم.'],
  nurse: ['Nurse', 'ممرض', 'mid', 'Provides bedside and clinic nursing care.', 'يقدم الرعاية التمريضية في العيادة والأجنحة.'],
  pharmacist: ['Pharmacist', 'صيدلي', 'mid', 'Dispenses medicines and advises patients.', 'يصرف الأدوية ويقدم المشورة.'],
  lab_tech: ['Laboratory Technician', 'فني مختبر', 'mid', 'Runs lab tests and records results.', 'يجري الفحوص المخبرية ويسجل نتائجها.'],
  radiographer: ['Radiographer', 'فني أشعة', 'mid', 'Performs imaging procedures.', 'ينفذ فحوص التصوير الطبي.'],
  records_clerk: ['Medical Records Clerk', 'موظف سجلات طبية', 'entry', 'Maintains patient records.', 'يصون ملفات المرضى.'],
  billing_spec: ['Medical Billing Specialist', 'أخصائي فوترة طبية', 'mid', 'Prepares claims and patient billing.', 'يعد المطالبات وفواتير المرضى.'],
  // trading
  trade_mgr: ['Trading Manager', 'مدير تجارة', 'manager', 'Leads buying, selling and margins.', 'يقود الشراء والبيع والهوامش.'],
  logistics_coord: ['Logistics Coordinator', 'منسق لوجستيات', 'mid', 'Coordinates shipments and deliveries.', 'ينسق الشحنات والتسليمات.'],
};
