import { createDatabase } from "../../../db/postgres";
import { apiFailure, canAccessEmployee, enforceRateLimit, enforceWriteOrigin, requireActor } from "../api-security";
import { audit, body, number, notifyEmployee, required, requireEmployeeScope, requireModule, text, transition } from "../../talent/talent-service";

type Json=Record<string,unknown>;
const stages:Record<string,string[]>={draft:["self_review"],self_review:["manager_review"],manager_review:["hr_review","completed"],hr_review:["completed"],completed:[]};
const cycleTypes=new Set(["monthly","quarterly","semiannual","annual"]),measurements=new Set(["percentage","number","rating","yes_no"]);
const clamp=(value:number,min:number,max:number)=>Math.min(max,Math.max(min,value));
const rating=(value:unknown)=>{const result=Number(value);if(!Number.isFinite(result)||result<1||result>5)throw new Response("Rating must be between 1 and 5",{status:400});return result;};
const normalizedResult=(measurement:string,target:string,actual:string)=>{if(measurement==="yes_no")return /^(yes|true|1|نعم)$/i.test(actual.trim())?100:0;const value=Number(actual);if(!Number.isFinite(value)||value<0)throw new Response("Actual result must be a valid positive number",{status:400});if(measurement==="rating")return clamp(value/5*100,0,100);if(measurement==="number"){const targetValue=Number(String(target).replace(/[^0-9.-]/g,""));if(!Number.isFinite(targetValue)||targetValue<=0)throw new Response("A numeric goal needs a numeric target",{status:400});return clamp(value/targetValue*100,0,100);}return clamp(value,0,100);};

export async function GET(request:Request){const db=createDatabase();try{const actor=await requireActor(request,db);await requireModule(db,actor,"performance","view");const url=new URL(request.url),employeeId=number(url.searchParams.get("employeeId"));if(employeeId)await requireEmployeeScope(db,actor,employeeId);const where=employeeId?"WHERE r.employee_id=?":actor.roleName==="Employee"?"WHERE r.employee_id=?":"",args=employeeId?[employeeId]:actor.roleName==="Employee"?[actor.employeeId]:[];const [cycles,reviews,goals,comments,scales]=await Promise.all([
  db.prepare("SELECT c.*,s.name AS rating_scale_name FROM performance_cycles c LEFT JOIN performance_rating_scales s ON s.id=c.rating_scale_id ORDER BY c.start_date DESC,c.id DESC LIMIT 200").all(),
  db.prepare(`SELECT r.*,c.name AS cycle_name,c.cycle_type,c.start_date,c.end_date,c.hr_review_required,e.employee_code,e.name_en AS employee_name,e.name_ar AS employee_name_ar,d.name_en AS department_name,d.name_ar AS department_name_ar,m.name_en AS manager_name,m.name_ar AS manager_name_ar FROM performance_reviews r JOIN performance_cycles c ON c.id=r.cycle_id JOIN employees e ON e.id=r.employee_id LEFT JOIN departments d ON d.id=e.department_id LEFT JOIN employees m ON m.id=r.manager_employee_id ${where} ORDER BY c.start_date DESC,r.id DESC LIMIT 1000`).bind(...args).all(),
  db.prepare(`SELECT g.* FROM performance_goals g JOIN performance_reviews r ON r.id=g.review_id ${where} ORDER BY g.review_id,g.id`).bind(...args).all(),
  db.prepare(`SELECT c.*,u.email AS author FROM performance_comments c JOIN performance_reviews r ON r.id=c.review_id LEFT JOIN users u ON u.id=c.author_user_id ${where} ORDER BY c.created_at`).bind(...args).all(),
  db.prepare("SELECT * FROM performance_rating_scales WHERE status='active' ORDER BY id").all(),
]);let visibleReviews=reviews.results as Record<string,unknown>[];if(!["Super Admin","HR Manager"].includes(actor.roleName)){const scoped=[] as Record<string,unknown>[];for(const review of visibleReviews)if(await canAccessEmployee(db,actor,Number(review.employee_id)))scoped.push(review);visibleReviews=scoped;}const visibleReviewIds=new Set(visibleReviews.map(review=>Number(review.id))),visibleCycleIds=new Set(visibleReviews.map(review=>Number(review.cycle_id))),visibleCycles=["Super Admin","HR Manager"].includes(actor.roleName)?cycles.results:(cycles.results as Record<string,unknown>[]).filter(cycle=>visibleCycleIds.has(Number(cycle.id))),visibleGoals=(goals.results as Record<string,unknown>[]).filter(goal=>visibleReviewIds.has(Number(goal.review_id))),visibleComments=(comments.results as Record<string,unknown>[]).filter(comment=>visibleReviewIds.has(Number(comment.review_id)));return Response.json({cycles:visibleCycles,reviews:visibleReviews,goals:visibleGoals,comments:visibleComments,ratingScales:scales.results,actor:{roleName:actor.roleName,employeeId:actor.employeeId}});}catch(error){return apiFailure(error,"Unable to load performance");}finally{await db.close();}}

export async function POST(request:Request){const db=createDatabase();try{enforceWriteOrigin(request);const actor=await requireActor(request,db);await enforceRateLimit(db,request,"performance-write",180,60,actor.id);const input=await body(request),action=required(input.action,"action");
  if(action==="create_cycle_with_employees"){
    await requireModule(db,actor,"performance","create");const name=required(input.name,"name"),cycleType=required(input.cycleType,"cycle type"),startDate=required(input.startDate,"start date"),endDate=required(input.endDate,"end date"),scope=text(input.scope)||"all";if(!cycleTypes.has(cycleType))throw new Response("Unsupported review cycle type",{status:400});if(endDate<startDate)throw new Response("End date must be on or after start date",{status:400});if(!["all","department","selected"].includes(scope))throw new Response("Unsupported employee scope",{status:400});
    const allEmployees=(await db.prepare("SELECT e.id,e.manager_id,e.department_id,CASE WHEN COALESCE(e.manager_id,d.manager_employee_id)=e.id THEN NULL ELSE COALESCE(e.manager_id,d.manager_employee_id) END AS review_manager_id FROM employees e LEFT JOIN departments d ON d.id=e.department_id WHERE e.employment_status IN ('active','probation','notice_period') ORDER BY e.id").all<{id:number;manager_id:number|null;department_id:number|null;review_manager_id:number|null}>()).results,departmentId=number(input.departmentId),requestedIds=new Set((Array.isArray(input.employeeIds)?input.employeeIds:[]).map(Number).filter(Boolean)),selected=scope==="all"?allEmployees:scope==="department"?allEmployees.filter(employee=>Number(employee.department_id)===departmentId):allEmployees.filter(employee=>requestedIds.has(Number(employee.id)));
    if(scope==="department"&&!departmentId)throw new Response("Department is required",{status:400});if(!selected.length)throw new Response("Choose at least one employee",{status:400});for(const employee of selected)await requireEmployeeScope(db,actor,Number(employee.id));const scopeValue=scope==="department"?`department:${departmentId}`:scope==="selected"?`employees:${selected.map(employee=>employee.id).join(",")}`:"all";
    const created=await db.transaction(async tx=>{const cycle=await tx.prepare("INSERT INTO performance_cycles(name,cycle_type,start_date,end_date,status,department_ids,rating_scale_id,hr_review_required,created_by_user_id,created_at,updated_at) VALUES (?,?,?,?,'active',?,?,1,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) RETURNING id").bind(name,cycleType,startDate,endDate,scopeValue,number(input.ratingScaleId)||null,actor.id).first<{id:number}>();const reviews=[] as {id:number;employeeId:number}[];for(const employee of selected){const review=await tx.prepare("INSERT INTO performance_reviews(cycle_id,employee_id,manager_employee_id,status,created_at,updated_at) VALUES (?,?,?,'draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) RETURNING id").bind(cycle!.id,employee.id,employee.review_manager_id||null).first<{id:number}>();reviews.push({id:Number(review!.id),employeeId:Number(employee.id)});}return {cycleId:Number(cycle!.id),reviews};});
    for(const review of created.reviews)await notifyEmployee(db,review.employeeId,{type:"performance",title:"performance_review_assigned",entityType:"performance_review",entityId:review.id,path:"performance",key:`performance:${review.id}:assigned`});await audit(db,actor,"create","performance","cycle",created.cycleId,{name,cycleType,startDate,endDate,scope,count:selected.length});return Response.json({ok:true,id:created.cycleId,count:selected.length},{status:201});
  }
  if(action==="create_cycle"){await requireModule(db,actor,"performance","create");const result=await db.prepare("INSERT INTO performance_cycles(name,cycle_type,start_date,end_date,status,department_ids,rating_scale_id,hr_review_required,created_by_user_id,created_at,updated_at) VALUES (?,?,?,?,'draft',?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) RETURNING id").bind(required(input.name,"name"),required(input.cycleType,"cycle type"),required(input.startDate,"start date"),required(input.endDate,"end date"),text(input.departmentIds),number(input.ratingScaleId)||null,input.hrReviewRequired===false?0:1,actor.id).first<{id:number}>();await audit(db,actor,"create","performance","cycle",result!.id,input);return Response.json({ok:true,id:result!.id},{status:201});}
  if(action==="activate_cycle"){await requireModule(db,actor,"performance","edit");const id=number(input.cycleId),cycle=await db.prepare("SELECT status FROM performance_cycles WHERE id=? FOR UPDATE").bind(id).first<{status:string}>();if(!cycle)throw new Response("Cycle not found",{status:404});if(cycle.status!=="draft")throw new Response("Only a draft cycle can be activated",{status:409});await db.prepare("UPDATE performance_cycles SET status='active',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(id).run();await audit(db,actor,"activate","performance","cycle",id,{status:"active"});return Response.json({ok:true});}
  if(action==="assign_review"){await requireModule(db,actor,"performance","create");const employeeId=number(input.employeeId);await requireEmployeeScope(db,actor,employeeId);const cycleId=number(input.cycleId),cycle=await db.prepare("SELECT id FROM performance_cycles WHERE id=? AND status='active'").bind(cycleId).first();if(!cycle)throw new Response("Active cycle not found",{status:404});const manager=await db.prepare("SELECT CASE WHEN COALESCE(e.manager_id,d.manager_employee_id)=e.id THEN NULL ELSE COALESCE(e.manager_id,d.manager_employee_id) END AS manager_id FROM employees e LEFT JOIN departments d ON d.id=e.department_id WHERE e.id=?").bind(employeeId).first<{manager_id:number|null}>();const row=await db.prepare("INSERT INTO performance_reviews(cycle_id,employee_id,manager_employee_id,status,created_at,updated_at) VALUES (?,?,?,'draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT(cycle_id,employee_id) DO NOTHING RETURNING id").bind(cycleId,employeeId,manager?.manager_id||null).first<{id:number}>();if(!row)throw new Response("Review already assigned",{status:409});await notifyEmployee(db,employeeId,{type:"performance",title:"performance_review_assigned",entityType:"performance_review",entityId:row.id,path:"performance",key:`performance:${row.id}:assigned`});await audit(db,actor,"assign","performance","review",row.id,{cycleId,employeeId});return Response.json({ok:true,id:row.id},{status:201});}
  if(action==="add_goal"){const reviewId=number(input.reviewId),review=await db.prepare("SELECT employee_id,status FROM performance_reviews WHERE id=?").bind(reviewId).first<{employee_id:number;status:string}>();if(!review)throw new Response("Review not found",{status:404});await requireEmployeeScope(db,actor,Number(review.employee_id));if(review.status!=="draft")throw new Response("Goals are locked",{status:409});const weight=Number(input.weight),measurementType=text(input.measurementType)||"percentage";if(!(weight>0&&weight<=100))throw new Response("Weight must be between 0 and 100",{status:400});if(!measurements.has(measurementType))throw new Response("Unsupported goal measurement",{status:400});const total=await db.prepare("SELECT COALESCE(SUM(weight),0)::float AS total FROM performance_goals WHERE review_id=?").bind(reviewId).first<{total:number}>();if(Number(total?.total)+weight>100.001)throw new Response("Total goal weight cannot exceed 100",{status:409});const row=await db.prepare("INSERT INTO performance_goals(review_id,title,description,target,measurement_type,weight,progress,created_by_user_id,created_at,updated_at) VALUES (?,?,?,?,?,?,0,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) RETURNING id").bind(reviewId,required(input.title,"title"),text(input.description)||null,required(input.target,"target"),measurementType,weight,actor.id).first<{id:number}>();await audit(db,actor,"create","performance","goal",row!.id,{reviewId,weight,measurementType});return Response.json({ok:true,id:row!.id},{status:201});}
  if(action==="delete_goal"){const goalId=number(input.goalId),goal=await db.prepare("SELECT g.review_id,r.employee_id,r.status FROM performance_goals g JOIN performance_reviews r ON r.id=g.review_id WHERE g.id=?").bind(goalId).first<{review_id:number;employee_id:number;status:string}>();if(!goal)throw new Response("Goal not found",{status:404});await requireEmployeeScope(db,actor,Number(goal.employee_id));if(goal.status!=="draft")throw new Response("Goals are locked",{status:409});await db.prepare("DELETE FROM performance_goALS WHERE id=?").bind(goalId).run();await audit(db,actor,"delete","performance","goal",goalId,{reviewId:goal.review_id});return Response.json({ok:true});}
  if(action==="submit_self"){
    const id=number(input.reviewId),row=await db.prepare("SELECT employee_id,status FROM performance_reviews WHERE id=? FOR UPDATE").bind(id).first<{employee_id:number;status:string}>();if(!row)throw new Response("Review not found",{status:404});if(actor.employeeId!==Number(row.employee_id)&&!["Super Admin","HR Manager"].includes(actor.roleName))throw new Response("Only the employee can submit this self-review",{status:403});transition(row.status,"self_review",stages,"review transition");const goals=(await db.prepare("SELECT id,target,measurement_type,weight FROM performance_goals WHERE review_id=? ORDER BY id").bind(id).all<{id:number;target:string;measurement_type:string;weight:number}>()).results,total=goals.reduce((sum,goal)=>sum+Number(goal.weight),0);if(Math.abs(total-100)>0.001)throw new Response("Goal weights must total exactly 100",{status:409});const supplied=Array.isArray(input.goals)?input.goals as Json[]:[];if(supplied.length&&supplied.length!==goals.length)throw new Response("Complete every goal before submitting",{status:409});const updates=[] as {goalId:number;actual:string;employeeRating:number;result:number}[];for(const goal of goals){const item=supplied.find(value=>number(value.goalId)===Number(goal.id));if(!item)continue;const actual=required(item.actualResult,"actual result"),employeeRating=rating(item.employeeRating),result=normalizedResult(goal.measurement_type||"percentage",goal.target,actual);updates.push({goalId:Number(goal.id),actual,employeeRating,result});}const reviewText=text(input.review)||null;await db.batch([...updates.map(item=>db.prepare("UPDATE performance_goals SET actual_result=?,employee_rating=?,result=?,progress=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(item.actual,item.employeeRating,item.result,item.result,item.goalId)),db.prepare("UPDATE performance_reviews SET self_review=?,self_rating=?,status='self_review',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(reviewText,updates.length?updates.reduce((sum,item)=>sum+item.employeeRating,0)/updates.length:Number(input.rating)||null,id),...(reviewText?[db.prepare("INSERT INTO performance_comments(review_id,author_user_id,stage,comment,created_at) VALUES (?,?,'self_review',?,CURRENT_TIMESTAMP)").bind(id,actor.id,reviewText)]:[])]);await audit(db,actor,"self_review","performance","review",id,{submitted:true});return Response.json({ok:true});
  }
  if(action==="manager_review"){
    const id=number(input.reviewId),row=await db.prepare("SELECT employee_id,manager_employee_id,status FROM performance_reviews WHERE id=? FOR UPDATE").bind(id).first<{employee_id:number;manager_employee_id:number|null;status:string}>();if(!row)throw new Response("Review not found",{status:404});if(actor.employeeId!==Number(row.manager_employee_id)&&!["Super Admin","HR Manager"].includes(actor.roleName))throw new Response("Manager scope required",{status:403});if(row.status!=="self_review")throw new Response("Self review must be submitted first",{status:409});const decision=text(input.decision)||"approve",comment=text(input.review),supplied=Array.isArray(input.goals)?input.goals as Json[]:[];
    if(decision==="return"){await db.batch([db.prepare("UPDATE performance_reviews SET manager_review=?,status='draft',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(comment||null,id),...(comment?[db.prepare("INSERT INTO performance_comments(review_id,author_user_id,stage,comment,created_at) VALUES (?,?,'manager_return',?,CURRENT_TIMESTAMP)").bind(id,actor.id,comment)]:[])]);await notifyEmployee(db,Number(row.employee_id),{type:"performance",title:"performance_review_returned",entityType:"performance_review",entityId:id,path:"performance",key:`performance:${id}:manager-return:${Date.now()}`});await audit(db,actor,"return","performance","review",id,{to:"employee"});return Response.json({ok:true,status:"draft"});}
    transition(row.status,"manager_review",stages,"review transition");const goals=(await db.prepare("SELECT id FROM performance_goals WHERE review_id=? ORDER BY id").bind(id).all<{id:number}>()).results;if(supplied.length&&supplied.length!==goals.length)throw new Response("Rate every goal before approving",{status:409});const updates=goals.map(goal=>{const item=supplied.find(value=>number(value.goalId)===Number(goal.id));return item?{goalId:Number(goal.id),managerRating:rating(item.managerRating)}:null;}).filter(Boolean) as {goalId:number;managerRating:number}[],overall=updates.length?updates.reduce((sum,item)=>sum+item.managerRating,0)/updates.length:Number(input.rating)||null;await db.batch([...updates.map(item=>db.prepare("UPDATE performance_goals SET manager_rating=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(item.managerRating,item.goalId)),db.prepare("UPDATE performance_reviews SET manager_review=?,manager_rating=?,status='manager_review',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(comment||null,overall,id),...(comment?[db.prepare("INSERT INTO performance_comments(review_id,author_user_id,stage,comment,created_at) VALUES (?,?,'manager_review',?,CURRENT_TIMESTAMP)").bind(id,actor.id,comment)]:[])]);await notifyEmployee(db,Number(row.employee_id),{type:"performance",title:"performance_manager_review_complete",entityType:"performance_review",entityId:id,path:"performance",key:`performance:${id}:manager`});await audit(db,actor,"manager_review","performance","review",id,{rating:overall});return Response.json({ok:true});
  }
  if(action==="hr_decision"&&text(input.decision)==="return"){await requireModule(db,actor,"performance","approve");const id=number(input.reviewId),row=await db.prepare("SELECT employee_id,status FROM performance_reviews WHERE id=? FOR UPDATE").bind(id).first<{employee_id:number;status:string}>();if(!row)throw new Response("Review not found",{status:404});if(!["manager_review","hr_review"].includes(row.status))throw new Response("Manager review must be completed first",{status:409});const comment=text(input.review);await db.batch([db.prepare("UPDATE performance_reviews SET hr_review=?,status='self_review',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(comment||null,id),...(comment?[db.prepare("INSERT INTO performance_comments(review_id,author_user_id,stage,comment,created_at) VALUES (?,?,'hr_return',?,CURRENT_TIMESTAMP)").bind(id,actor.id,comment)]:[])]);await audit(db,actor,"return","performance","review",id,{to:"manager"});return Response.json({ok:true,status:"self_review"});}
  if(action==="finalize"||action==="hr_decision"){
    await requireModule(db,actor,"performance","approve");const id=number(input.reviewId),row=await db.prepare("SELECT r.employee_id,r.cycle_id,r.status,c.hr_review_required FROM performance_reviews r JOIN performance_cycles c ON c.id=r.cycle_id WHERE r.id=? FOR UPDATE OF r").bind(id).first<{employee_id:number;cycle_id:number;status:string;hr_review_required:number}>();if(!row)throw new Response("Review not found",{status:404});if(row.status==="completed")throw new Response("Review already finalized",{status:409});if(row.status!=="manager_review"&&row.status!=="hr_review")throw new Response("Manager review must be completed first",{status:409});const goals=(await db.prepare("SELECT weight,result,manager_rating FROM performance_goals WHERE review_id=?").bind(id).all<{weight:number;result:number|null;manager_rating:number|null}>()).results;if(!goals.length)throw new Response("At least one goal is required",{status:409});const hasManagerRatings=goals.every(goal=>goal.manager_rating!=null);if(!hasManagerRatings&&goals.some(goal=>goal.result==null))throw new Response("All goal results are required",{status:409});const score=goals.reduce((sum,goal)=>sum+Number(goal.weight)*(hasManagerRatings?Number(goal.manager_rating)/5:Number(goal.result)/100),0),comment=text(input.review);await db.batch([db.prepare("UPDATE performance_reviews SET hr_review=?,hr_rating=?,final_score=?,status='completed',finalized_by_user_id=?,finalized_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status!='completed'").bind(comment||null,Number(input.rating)||null,score,actor.id,id),...(comment?[db.prepare("INSERT INTO performance_comments(review_id,author_user_id,stage,comment,created_at) VALUES (?,?,'hr_approval',?,CURRENT_TIMESTAMP)").bind(id,actor.id,comment)]:[])]);const remaining=await db.prepare("SELECT COUNT(*)::int AS count FROM performance_reviews WHERE cycle_id=? AND status!='completed'").bind(row.cycle_id).first<{count:number}>();if(Number(remaining?.count)===0)await db.prepare("UPDATE performance_cycles SET status='completed',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(row.cycle_id).run();await notifyEmployee(db,Number(row.employee_id),{type:"performance",title:"performance_review_finalized",message:String(score.toFixed(2)),entityType:"performance_review",entityId:id,path:"performance",key:`performance:${id}:finalized`});await audit(db,actor,"finalize","performance","review",id,{finalScore:score});return Response.json({ok:true,finalScore:score});
  }
  if(action==="set_goal_result"){const id=number(input.goalId),goal=await db.prepare("SELECT g.review_id,r.employee_id,r.status FROM performance_goals g JOIN performance_reviews r ON r.id=g.review_id WHERE g.id=?").bind(id).first<{review_id:number;employee_id:number;status:string}>();if(!goal)throw new Response("Goal not found",{status:404});await requireEmployeeScope(db,actor,Number(goal.employee_id));if(goal.status==="completed")throw new Response("Review finalized",{status:409});const result=Number(input.result);if(result<0||result>100)throw new Response("Result must be between 0 and 100",{status:400});await db.prepare("UPDATE performance_goals SET result=?,progress=?,actual_result=COALESCE(actual_result,?),updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(result,clamp(Number(input.progress)||result,0,100),String(result),id).run();return Response.json({ok:true});}
  throw new Response("Unsupported performance action",{status:400});
}catch(error){return apiFailure(error,"Performance action failed");}finally{await db.close();}}
