import { createDatabase } from "../../../db/postgres";
import { apiFailure, requireActor } from "../api-security";

type Row=Record<string,unknown>;
async function employeeScope(db:ReturnType<typeof createDatabase>,actor:{roleName:string;employeeId:number|null}){
  if(["Super Admin","HR Manager"].includes(actor.roleName))return null;
  if(actor.roleName==="Employee")return actor.employeeId?[actor.employeeId]:[];
  if(actor.roleName==="Department Manager"&&actor.employeeId){const rows=(await db.prepare("WITH RECURSIVE managed AS (SELECT id FROM departments WHERE manager_employee_id=? AND status!='deleted' UNION ALL SELECT d.id FROM departments d JOIN managed m ON d.parent_id=m.id WHERE d.status!='deleted') SELECT e.id FROM employees e WHERE e.department_id IN (SELECT id FROM managed) AND e.employment_status!='deleted'").bind(actor.employeeId).all()).results;return rows.map(row=>Number(row.id));}
  return [];
}
export async function GET(request:Request){const db=createDatabase();try{
  const actor=await requireActor(request,db),ids=await employeeScope(db,actor),today=new Date().toISOString().slice(0,10),month=today.slice(0,7),scoped=ids===null?"":ids.length?` AND e.id IN (${ids.map(()=>"?").join(",")})`:" AND 1=0",bind=ids??[],approvalStatus=actor.roleName==="Department Manager"?"'pending_manager'":["Super Admin","HR Manager"].includes(actor.roleName)?"'pending_hr'":"'__none__'";
  const [workforce,attendance,leave,absences,exceptions,docs,missing,accountActions,approvalStats,oldest,holiday,events]=await Promise.all([
    db.prepare(`SELECT COUNT(*)::integer AS active FROM employees e WHERE e.employment_status IN ('active','probation','notice_period')${scoped}`).bind(...bind).first<Row>(),
    db.prepare(`SELECT COUNT(*) FILTER (WHERE da.status IN ('present','late','remote'))::integer AS present,COUNT(*) FILTER (WHERE da.late_minutes>0)::integer AS late,COUNT(*) FILTER (WHERE da.attendance_type='remote')::integer AS remote,COUNT(*) FILTER (WHERE da.actual_in IS NOT NULL AND da.actual_out IS NULL)::integer AS missing_checkout FROM daily_attendance da JOIN employees e ON e.id=da.employee_id WHERE da.work_date=?${scoped}`).bind(today,...bind).first<Row>(),
    db.prepare(`SELECT COUNT(DISTINCT q.employee_id)::integer AS on_leave FROM requests q JOIN employees e ON e.id=q.employee_id WHERE q.leave_type_id IS NOT NULL AND q.status IN ('hr_approved','approved') AND q.from_date<=? AND q.to_date>=?${scoped}`).bind(today,today,...bind).first<Row>(),
    db.prepare(`SELECT COUNT(*)::integer AS count FROM employees e WHERE e.employment_status IN ('active','probation','notice_period')${scoped} AND EXTRACT(DOW FROM CURRENT_DATE)::integer::text=ANY(string_to_array(COALESCE(e.work_days,'0,1,2,3,4'),',')) AND NOT EXISTS (SELECT 1 FROM holidays h WHERE h.status='active' AND h.country IN (e.country,'Both','KSA & Egypt') AND (h.holiday_date=CURRENT_DATE::text OR (h.recurrence_type='annual' AND substring(h.holiday_date,6,5)=to_char(CURRENT_DATE,'MM-DD')))) AND NOT EXISTS (SELECT 1 FROM requests q WHERE q.employee_id=e.id AND q.leave_type_id IS NOT NULL AND q.status IN ('hr_approved','approved') AND q.from_date<=CURRENT_DATE::text AND q.to_date>=CURRENT_DATE::text) AND NOT EXISTS (SELECT 1 FROM daily_attendance da WHERE da.employee_id=e.id AND da.work_date=CURRENT_DATE::text AND (da.actual_in IS NOT NULL OR da.status IN ('present','late','remote')))`).bind(...bind).first<Row>(),
    db.prepare(`SELECT COUNT(*) FILTER (WHERE x.status IN ('open','correction_requested','pending_manager','pending_hr'))::integer AS open,COUNT(*) FILTER (WHERE x.exception_type='missing_check_out' AND x.status IN ('open','correction_requested','pending_manager','pending_hr'))::integer AS missing_checkout FROM attendance_exceptions x JOIN employees e ON e.id=x.employee_id WHERE 1=1${scoped}`).bind(...bind).first<Row>(),
    db.prepare(`SELECT COUNT(*) FILTER (WHERE d.status='active' AND d.expiry_date<CURRENT_DATE::text)::integer AS expired,COUNT(*) FILTER (WHERE d.status='active' AND d.expiry_date BETWEEN CURRENT_DATE::text AND (CURRENT_DATE+30)::text)::integer AS expiring FROM documents d JOIN employees e ON e.id=d.employee_id WHERE 1=1${scoped}`).bind(...bind).first<Row>(),
    db.prepare(`SELECT COUNT(*)::integer AS count FROM employees e JOIN document_categories c ON c.required_document=1 AND c.status='active' AND (c.country IS NULL OR c.country=e.country) AND (c.employment_type IS NULL OR c.employment_type=e.employment_type) WHERE e.employment_status IN ('active','probation','notice_period')${scoped} AND NOT EXISTS (SELECT 1 FROM documents d WHERE d.employee_id=e.id AND d.category=c.code AND d.status='active')`).bind(...bind).first<Row>(),
    db.prepare(`SELECT COUNT(*)::integer AS count FROM users u JOIN employees e ON e.id=u.employee_id WHERE u.status='active' AND u.must_change_password=1${scoped}`).bind(...bind).first<Row>(),
    db.prepare(`SELECT COUNT(*) FILTER (WHERE q.status=${approvalStatus})::integer AS needs_me,COUNT(*) FILTER (WHERE q.status IN ('pending_manager','pending_hr') AND q.status<>${approvalStatus})::integer AS waiting_others,COUNT(*) FILTER (WHERE q.status IN ('hr_approved','approved') AND q.updated_at::text LIKE ?)::integer AS approved_month,COUNT(*) FILTER (WHERE q.status LIKE '%rejected%' AND q.updated_at::text LIKE ?)::integer AS rejected_month FROM requests q JOIN employees e ON e.id=q.employee_id WHERE 1=1${scoped}`).bind(`${month}%`,`${month}%`,...bind).first<Row>(),
    db.prepare(`SELECT q.id,q.request_code,q.created_at,e.id AS employee_id,e.name_en,e.name_ar FROM requests q JOIN employees e ON e.id=q.employee_id WHERE q.status=${approvalStatus}${scoped} ORDER BY q.created_at LIMIT 1`).bind(...bind).first<Row>(),
    db.prepare("SELECT name_en,name_ar,holiday_date FROM holidays WHERE status='active' AND holiday_date>=? ORDER BY holiday_date LIMIT 1").bind(today).first<Row>(),
    db.prepare(`SELECT 'leave' AS type,q.id::text AS id,q.from_date AS event_date,e.id AS employee_id,e.name_en,e.name_ar FROM requests q JOIN employees e ON e.id=q.employee_id WHERE q.leave_type_id IS NOT NULL AND q.status IN ('hr_approved','approved') AND q.from_date>?${scoped} ORDER BY event_date LIMIT 8`).bind(today,...bind).all(),
  ]);
  const [performance,recruitment,lifecycle,assetActions,learning]=await Promise.all([
    db.prepare(`SELECT COUNT(*) FILTER(WHERE r.status!='completed')::int AS incomplete,COUNT(*) FILTER(WHERE r.status!='completed' AND c.end_date<CURRENT_DATE::text)::int AS overdue FROM performance_reviews r JOIN performance_cycles c ON c.id=r.cycle_id JOIN employees e ON e.id=r.employee_id WHERE 1=1${scoped}`).bind(...bind).first<Row>(),
    db.prepare(`SELECT COUNT(*) FILTER(WHERE j.status='open')::int AS open_jobs,COUNT(c.id) FILTER(WHERE c.stage IN ('screening','interview','final_interview','offer'))::int AS candidates_action FROM job_openings j LEFT JOIN candidates c ON c.job_id=j.id ${actor.roleName==="Department Manager"?"WHERE j.hiring_manager_employee_id=?":""}`).bind(...(actor.roleName==="Department Manager"?[actor.employeeId]:[])).first<Row>(),
    db.prepare(`SELECT COUNT(DISTINCT l.id) FILTER(WHERE l.lifecycle_type='onboarding' AND l.status='in_progress')::int AS onboarding,COUNT(DISTINCT l.id) FILTER(WHERE l.lifecycle_type='offboarding' AND l.status='in_progress')::int AS offboarding,COUNT(t.id) FILTER(WHERE t.status!='completed' AND t.due_date<CURRENT_DATE::text)::int AS overdue_tasks FROM employee_lifecycles l JOIN employees e ON e.id=l.employee_id LEFT JOIN lifecycle_tasks t ON t.lifecycle_id=l.id WHERE 1=1${scoped}`).bind(...bind).first<Row>(),
    db.prepare(`SELECT COUNT(*)::int AS unreturned FROM asset_assignments x JOIN employees e ON e.id=x.employee_id JOIN employee_lifecycles l ON l.employee_id=e.id AND l.lifecycle_type='offboarding' AND l.status='in_progress' WHERE x.returned_at IS NULL${scoped}`).bind(...bind).first<Row>(),
    db.prepare(`SELECT COUNT(*) FILTER(WHERE c.mandatory=1 AND x.status IN ('assigned','in_progress') AND x.due_date<CURRENT_DATE::text)::int AS mandatory_overdue,COUNT(*) FILTER(WHERE x.status='completed' AND x.certificate_expiry BETWEEN CURRENT_DATE::text AND (CURRENT_DATE+30)::text)::int AS expiring_certifications FROM training_enrollments x JOIN training_courses c ON c.id=x.course_id JOIN employees e ON e.id=x.employee_id WHERE 1=1${scoped}`).bind(...bind).first<Row>(),
  ]);
  const talent={performance:{incomplete:Number(performance?.incomplete),overdue:Number(performance?.overdue)},recruitment:{openJobs:Number(recruitment?.open_jobs),candidatesAction:Number(recruitment?.candidates_action)},lifecycle:{onboarding:Number(lifecycle?.onboarding),offboarding:Number(lifecycle?.offboarding),overdueTasks:Number(lifecycle?.overdue_tasks)},assets:{unreturned:Number(assetActions?.unreturned)},learning:{mandatoryOverdue:Number(learning?.mandatory_overdue),expiringCertifications:Number(learning?.expiring_certifications)}};
  const needs=[{kind:"approvals",count:Number(approvalStats?.needs_me),target:"approvals"},{kind:"attendance",count:Number(exceptions?.open),target:"attendance"},{kind:"expired_documents",count:Number(docs?.expired),target:"employees?records=expired"},{kind:"expiring_documents",count:Number(docs?.expiring),target:"employees?records=expiring"},{kind:"missing_documents",count:Number(missing?.count),target:"employees?records=missing"},{kind:"password_change",count:Number(accountActions?.count),target:"users"},{kind:"performance_incomplete",count:talent.performance.incomplete,target:"performance"},{kind:"performance_overdue",count:talent.performance.overdue,target:"performance"},{kind:"open_jobs",count:talent.recruitment.openJobs,target:"recruitment"},{kind:"candidates_action",count:talent.recruitment.candidatesAction,target:"recruitment"},{kind:"new_hires_onboarding",count:talent.lifecycle.onboarding,target:"lifecycle"},{kind:"employees_offboarding",count:talent.lifecycle.offboarding,target:"lifecycle"},{kind:"onboarding_overdue",count:talent.lifecycle.overdueTasks,target:"lifecycle"},{kind:"unreturned_assets",count:talent.assets.unreturned,target:"assets"},{kind:"training_overdue",count:talent.learning.mandatoryOverdue,target:"learning"},{kind:"certifications_expiring",count:talent.learning.expiringCertifications,target:"learning"}].filter(item=>item.count>0);
  return Response.json({needs,workforce:{active:Number(workforce?.active),present:Number(attendance?.present),late:Number(attendance?.late),remote:Number(attendance?.remote),onLeave:Number(leave?.on_leave),absentCandidates:Number(absences?.count),missingCheckout:Math.max(Number(attendance?.missing_checkout),Number(exceptions?.missing_checkout)),needsReview:Number(exceptions?.open)},approvals:{needsMyApproval:Number(approvalStats?.needs_me),waitingForOthers:Number(approvalStats?.waiting_others),approvedThisMonth:Number(approvalStats?.approved_month),rejectedThisMonth:Number(approvalStats?.rejected_month),oldest},records:{expired:Number(docs?.expired),expiring:Number(docs?.expiring),missing:Number(missing?.count)},talent,upcoming:{holiday,events:events.results}},{headers:{"cache-control":"no-store"}});
}catch(error){return apiFailure(error,"Unable to load dashboard");}finally{await db.close();}}
