import { createDatabase } from "../../../db/postgres";
import { apiFailure, requireActor, requirePermission } from "../api-security";

type Row=Record<string,unknown>;
const csv=(rows:Row[],columns:{key:string;label:string}[])=>[columns.map(column=>column.label),...rows.map(row=>columns.map(column=>row[column.key]??""))].map(values=>values.map(value=>{const text=String(value);return /[",\r\n]/.test(text)?`"${text.replaceAll('"','""')}"`:text;}).join(",")).join("\r\n");
async function scopeIds(db:ReturnType<typeof createDatabase>,actor:{roleName:string;employeeId:number|null}){if(["Super Admin","HR Manager"].includes(actor.roleName))return null;if(actor.roleName==="Employee")return actor.employeeId?[actor.employeeId]:[];if(actor.roleName==="Department Manager"&&actor.employeeId){const rows=(await db.prepare("WITH RECURSIVE managed AS (SELECT id FROM departments WHERE manager_employee_id=? AND status!='deleted' UNION ALL SELECT d.id FROM departments d JOIN managed m ON d.parent_id=m.id WHERE d.status!='deleted') SELECT e.id FROM employees e WHERE e.department_id IN (SELECT id FROM managed) AND e.employment_status!='deleted'").bind(actor.employeeId).all()).results;return rows.map(row=>Number(row.id));}return [];}
export async function GET(request:Request){const db=createDatabase();try{
  const actor=await requireActor(request,db),url=new URL(request.url),type=url.searchParams.get("type")||"attendance",format=url.searchParams.get("format")||"json",ids=await scopeIds(db,actor),args:unknown[]=[],where:string[]=[];
  if(ids!==null){if(!ids.length)where.push("1=0");else{where.push(`e.id IN (${ids.map(()=>"?").join(",")})`);args.push(...ids);}}
  const from=url.searchParams.get("from"),to=url.searchParams.get("to"),employeeId=Number(url.searchParams.get("employeeId")),departmentId=Number(url.searchParams.get("departmentId")),status=url.searchParams.get("status");if(employeeId){where.push("e.id=?");args.push(employeeId);}if(departmentId){where.push("e.department_id=?");args.push(departmentId);}
  let query="",columns:{key:string;label:string}[]=[];
  if(type==="attendance"){if(from){where.push("da.work_date>=?");args.push(from);}if(to){where.push("da.work_date<=?");args.push(to);}if(status){where.push("da.status=?");args.push(status);}query=`SELECT e.employee_code,e.name_en AS employee_name,d.name_en AS department,da.work_date,da.scheduled_in,da.scheduled_out,da.actual_in,da.actual_out,da.worked_minutes,da.late_minutes,da.early_minutes,da.attendance_type,da.status,x.exception_type,x.status AS exception_state FROM daily_attendance da JOIN employees e ON e.id=da.employee_id LEFT JOIN departments d ON d.id=e.department_id LEFT JOIN LATERAL (SELECT exception_type,status FROM attendance_exceptions WHERE daily_attendance_id=da.id ORDER BY id DESC LIMIT 1) x ON true WHERE ${where.join(" AND ")||"1=1"} ORDER BY da.work_date DESC LIMIT 10000`;columns=["employee_code","employee_name","department","work_date","scheduled_in","scheduled_out","actual_in","actual_out","worked_minutes","late_minutes","early_minutes","attendance_type","status","exception_type","exception_state"].map(key=>({key,label:key}));}
  else if(type==="leave"){if(from){where.push("q.from_date>=?");args.push(from);}if(to){where.push("q.to_date<=?");args.push(to);}if(status){where.push("q.status=?");args.push(status);}query=`SELECT e.employee_code,e.name_en AS employee,q.request_code,lt.name_en AS leave_type,q.from_date,q.to_date,q.requested_days,q.created_at AS submitted,q.status AS final_status,q.current_stage FROM requests q JOIN employees e ON e.id=q.employee_id JOIN leave_types lt ON lt.id=q.leave_type_id WHERE ${where.join(" AND ")||"1=1"} ORDER BY q.created_at DESC LIMIT 10000`;columns=["employee_code","employee","request_code","leave_type","from_date","to_date","requested_days","submitted","final_status","current_stage"].map(key=>({key,label:key}));}
  else if(type==="employees"){query=`SELECT e.employee_code,e.name_en,e.name_ar,e.work_email,e.work_phone,d.name_en AS department,j.name_en AS job_title,e.start_date,e.end_date,e.employment_status,e.country,e.work_location,e.employment_type FROM employees e LEFT JOIN departments d ON d.id=e.department_id LEFT JOIN job_titles j ON j.id=e.job_title_id WHERE e.employment_status!='deleted' AND ${where.join(" AND ")||"1=1"} ORDER BY e.id LIMIT 10000`;columns=["employee_code","name_en","name_ar","work_email","work_phone","department","job_title","start_date","end_date","employment_status","country","work_location","employment_type"].map(key=>({key,label:key}));}
  else if(type==="documents"){if(!["Super Admin","HR Manager"].includes(actor.roleName))throw new Response("Documents report is restricted to HR",{status:403});query=`SELECT e.employee_code,e.name_en AS employee,c.name_en AS category,d.name,d.document_number,d.issue_date,d.expiry_date,d.status,CASE WHEN d.status='archived' THEN 'archived' WHEN d.expiry_date<CURRENT_DATE::text THEN 'expired' WHEN d.expiry_date<=(CURRENT_DATE+30)::text THEN 'expiring_soon' WHEN d.expiry_date IS NULL THEN 'no_expiry' ELSE 'valid' END AS state,d.created_at AS uploaded_at FROM documents d JOIN employees e ON e.id=d.employee_id JOIN document_categories c ON c.code=d.category WHERE ${where.join(" AND ")||"1=1"} ORDER BY d.expiry_date NULLS LAST LIMIT 10000`;columns=["employee_code","employee","category","name","document_number","issue_date","expiry_date","status","state","uploaded_at"].map(key=>({key,label:key}));}
  else if(type==="approvals"){if(from){where.push("a.created_at::date>=?::date");args.push(from);}if(to){where.push("a.created_at::date<=?::date");args.push(to);}if(status){where.push("a.action=?");args.push(status);}query=`SELECT q.request_code,q.type,e.employee_code,e.name_en AS employee,d.name_en AS department,a.stage,a.action,a.reason,a.created_at,u.email AS approver FROM approvals a JOIN requests q ON q.id=a.request_id JOIN employees e ON e.id=q.employee_id LEFT JOIN departments d ON d.id=e.department_id LEFT JOIN users u ON u.id=a.actor_user_id WHERE ${where.join(" AND ")||"1=1"} ORDER BY a.created_at DESC LIMIT 10000`;columns=["request_code","type","employee_code","employee","department","stage","action","reason","created_at","approver"].map(key=>({key,label:key}));}
  else if(type==="performance"){await requirePermission(db,actor,"performance","export");if(status){where.push("r.status=?");args.push(status);}query=`SELECT e.employee_code,e.name_en AS employee,d.name_en AS department,c.name AS cycle,c.cycle_type,r.final_score,r.status,r.finalized_at FROM performance_reviews r JOIN performance_cycles c ON c.id=r.cycle_id JOIN employees e ON e.id=r.employee_id LEFT JOIN departments d ON d.id=e.department_id WHERE ${where.join(" AND ")||"1=1"} ORDER BY c.start_date DESC,e.name_en LIMIT 10000`;columns=["employee_code","employee","department","cycle","cycle_type","final_score","status","finalized_at"].map(key=>({key,label:key}));}
  else if(type==="recruitment"){await requirePermission(db,actor,"recruitment","export");const recruitmentWhere:string[]=[];const recruitmentArgs:unknown[]=[];if(actor.roleName==="Department Manager"){recruitmentWhere.push("j.hiring_manager_employee_id=?");recruitmentArgs.push(actor.employeeId);}if(status){recruitmentWhere.push("COALESCE(s.stage_key,a.status)=?");recruitmentArgs.push(status);}query=`SELECT j.title AS job,j.status AS job_status,j.openings_count,COUNT(a.id) OVER(PARTITION BY j.id)::int AS applications,c.name AS candidate,c.email,COALESCE(s.stage_key,a.status) AS candidate_stage,a.source,a.status AS outcome FROM job_openings j LEFT JOIN candidate_applications a ON a.job_id=j.id LEFT JOIN candidates c ON c.id=a.candidate_id LEFT JOIN recruitment_stages s ON s.id=a.current_stage_id WHERE ${recruitmentWhere.join(" AND ")||"1=1"} ORDER BY j.id DESC,a.id DESC LIMIT 10000`;args.splice(0,args.length,...recruitmentArgs);columns=["job","job_status","openings_count","applications","candidate","email","candidate_stage","source","outcome"].map(key=>({key,label:key}));}
  else if(type==="onboarding"||type==="offboarding"){await requirePermission(db,actor,type,"export");where.push("l.lifecycle_type=?");args.push(type);if(status){where.push("l.status=?");args.push(status);}query=`SELECT e.employee_code,e.name_en AS employee,d.name_en AS department,l.lifecycle_type,l.reason_type,l.last_working_date,l.status,COUNT(t.id)::int AS tasks,COUNT(t.id) FILTER(WHERE t.status='completed')::int AS completed_tasks,COUNT(t.id) FILTER(WHERE t.status!='completed' AND t.due_date<CURRENT_DATE::text)::int AS overdue_tasks,CASE WHEN COUNT(t.id)=0 THEN 0 ELSE ROUND(100.0*COUNT(t.id) FILTER(WHERE t.status='completed')/COUNT(t.id))::int END AS progress FROM employee_lifecycles l JOIN employees e ON e.id=l.employee_id LEFT JOIN departments d ON d.id=e.department_id LEFT JOIN lifecycle_tasks t ON t.lifecycle_id=l.id WHERE ${where.join(" AND ")} GROUP BY e.id,d.id,l.id ORDER BY l.id DESC LIMIT 10000`;columns=["employee_code","employee","department","lifecycle_type","reason_type","last_working_date","status","tasks","completed_tasks","overdue_tasks","progress"].map(key=>({key,label:key}));}
  else if(type==="assets"){await requirePermission(db,actor,"assets","export");if(status){where.push("a.status=?");args.push(status);}query=`SELECT a.asset_code,a.category,a.name,a.brand_model,a.serial_number,a.status,a.asset_condition,e.employee_code,e.name_en AS assigned_employee,x.assigned_at,x.returned_at FROM assets a LEFT JOIN LATERAL(SELECT * FROM asset_assignments z WHERE z.asset_id=a.id ORDER BY z.assigned_at DESC,z.id DESC LIMIT 1)x ON true LEFT JOIN employees e ON e.id=x.employee_id WHERE ${where.join(" AND ")||"1=1"} ORDER BY a.id DESC LIMIT 10000`;columns=["asset_code","category","name","brand_model","serial_number","status","asset_condition","employee_code","assigned_employee","assigned_at","returned_at"].map(key=>({key,label:key}));}
  else if(type==="learning"){await requirePermission(db,actor,"learning","export");if(status){where.push("x.status=?");args.push(status);}query=`SELECT e.employee_code,e.name_en AS employee,d.name_en AS department,c.title AS course,c.provider,c.course_type,c.mandatory,x.status,x.due_date,x.completion_date,x.score,x.certificate_expiry FROM training_enrollments x JOIN training_courses c ON c.id=x.course_id JOIN employees e ON e.id=x.employee_id LEFT JOIN departments d ON d.id=e.department_id WHERE ${where.join(" AND ")||"1=1"} ORDER BY x.id DESC LIMIT 10000`;columns=["employee_code","employee","department","course","provider","course_type","mandatory","status","due_date","completion_date","score","certificate_expiry"].map(key=>({key,label:key}));}
  else throw new Response("Unsupported report type",{status:400});
  const rows=(await db.prepare(query).bind(...args).all()).results as Row[];if(format==="csv")return new Response(`\uFEFF${csv(rows,columns)}`,{headers:{"content-type":"text/csv; charset=utf-8","content-disposition":`attachment; filename="sanad-${type}.csv"`,"cache-control":"private, no-store","x-content-type-options":"nosniff"}});return Response.json({type,columns,rows,limited:rows.length===10000},{headers:{"cache-control":"no-store"}});
}catch(error){return apiFailure(error,"Unable to generate report");}finally{await db.close();}}
