import { withDatabase } from "../route-helpers";
import { enforceRateLimit, enforceWriteOrigin, requireActor } from "../api-security";
import { audit, body, notifyEmployee, number, required, requireEmployeeScope, requireModule, text } from "../../talent/talent-service";

export async function GET(request:Request){
  return withDatabase("Unable to load assets", async db => {const actor=await requireActor(request,db);await requireModule(db,actor,"assets","view");const url=new URL(request.url),employeeId=number(url.searchParams.get("employeeId"));if(employeeId)await requireEmployeeScope(db,actor,employeeId);if(actor.roleName==="Employee"&&!employeeId)throw new Response("Employee scope required",{status:403});const scoped=employeeId||actor.roleName==="Employee",id=employeeId||actor.employeeId;const assets=await db.prepare(`SELECT a.*,x.id AS assignment_id,x.employee_id,x.assigned_at,x.assigned_condition,x.returned_at,e.employee_code,e.name_en AS employee_name,e.name_ar AS employee_name_ar FROM assets a LEFT JOIN LATERAL (SELECT * FROM asset_assignments z WHERE z.asset_id=a.id ORDER BY z.assigned_at DESC,z.id DESC LIMIT 1) x ON true LEFT JOIN employees e ON e.id=x.employee_id ${scoped?"WHERE x.employee_id=?":""} ORDER BY a.id DESC LIMIT 2000`).bind(...(scoped?[id]:[])).all();const history=await db.prepare(`SELECT x.*,a.asset_code,a.name AS asset_name,e.employee_code,e.name_en AS employee_name,e.name_ar AS employee_name_ar FROM asset_assignments x JOIN assets a ON a.id=x.asset_id JOIN employees e ON e.id=x.employee_id ${scoped?"WHERE x.employee_id=?":""} ORDER BY x.assigned_at DESC LIMIT 5000`).bind(...(scoped?[id]:[])).all();return Response.json({assets:assets.results,history:history.results});});
}
export async function POST(request:Request){
  return withDatabase("Asset action failed", async db => {enforceWriteOrigin(request);const actor=await requireActor(request,db);await enforceRateLimit(db,request,"assets-write",180,60,actor.id);const input=await body(request),action=required(input.action,"action");
  if(action==="create"){
    await requireModule(db,actor,"assets","create");
    const employeeId=number(input.employeeId),condition=text(input.condition)||"good";
    if(employeeId){await requireModule(db,actor,"assets","edit");await requireEmployeeScope(db,actor,employeeId);}
    if(await db.prepare("SELECT id FROM assets WHERE lower(asset_code)=lower(?)").bind(required(input.assetCode,"asset code")).first())throw new Response("An asset with this code already exists",{status:409});
    const result=await db.transaction(async tx=>{
      const asset=await tx.prepare("INSERT INTO assets(asset_code,category,name,brand_model,serial_number,status,asset_condition,reference_date,notes,created_by_user_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) RETURNING id").bind(required(input.assetCode,"asset code"),required(input.category,"category"),required(input.name,"name"),text(input.brandModel)||null,text(input.serialNumber)||null,employeeId?"assigned":"available",condition,text(input.referenceDate)||null,text(input.notes)||null,actor.id).first<{id:number}>();
      let assignmentId=0;
      if(employeeId){const assignment=await tx.prepare("INSERT INTO asset_assignments(asset_id,employee_id,assigned_by_user_id,assigned_at,assigned_condition,assigned_notes,created_at) VALUES (?,?,?,CURRENT_TIMESTAMP,?,?,CURRENT_TIMESTAMP) RETURNING id").bind(asset!.id,employeeId,actor.id,condition,text(input.notes)||null).first<{id:number}>();assignmentId=assignment!.id;}
      return {assetId:asset!.id,assignmentId};
    });
    await audit(db,actor,"create","assets","asset",result.assetId,{assetCode:text(input.assetCode),category:text(input.category),employeeId:employeeId||null});
    if(employeeId){await notifyEmployee(db,employeeId,{type:"assets",title:"asset_assigned",entityType:"asset",entityId:result.assetId,path:"assets",key:`asset:${result.assetId}:assignment:${result.assignmentId}`});await audit(db,actor,"assign","assets","asset",result.assetId,{employeeId,assignmentId:result.assignmentId});}
    return Response.json({ok:true,id:result.assetId,assignmentId:result.assignmentId||null},{status:201});
  }
  if(action==="assign"){await requireModule(db,actor,"assets","edit");const assetId=number(input.assetId),employeeId=number(input.employeeId);await requireEmployeeScope(db,actor,employeeId);const assignment=await db.transaction(async tx=>{const asset=await tx.prepare("SELECT status FROM assets WHERE id=? FOR UPDATE").bind(assetId).first<{status:string}>();if(!asset)throw new Response("Asset not found",{status:404});if(asset.status!=="available")throw new Response("Asset is not available",{status:409});const row=await tx.prepare("INSERT INTO asset_assignments(asset_id,employee_id,assigned_by_user_id,assigned_at,assigned_condition,assigned_notes,created_at) VALUES (?,?,?,CURRENT_TIMESTAMP,?,?,CURRENT_TIMESTAMP) RETURNING id").bind(assetId,employeeId,actor.id,text(input.condition)||"good",text(input.notes)||null).first<{id:number}>();await tx.prepare("UPDATE assets SET status='assigned',asset_condition=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(text(input.condition)||"good",assetId).run();return row!.id;});await notifyEmployee(db,employeeId,{type:"assets",title:"asset_assigned",entityType:"asset",entityId:assetId,path:"assets",key:`asset:${assetId}:assignment:${assignment}`});await audit(db,actor,"assign","assets","asset",assetId,{employeeId,assignmentId:assignment});return Response.json({ok:true,assignmentId:assignment});}
  if(action==="return"){await requireModule(db,actor,"assets","edit");const assetId=number(input.assetId),result=await db.transaction(async tx=>{const asset=await tx.prepare("SELECT status FROM assets WHERE id=? FOR UPDATE").bind(assetId).first<{status:string}>();if(!asset)throw new Response("Asset not found",{status:404});const assignment=await tx.prepare("SELECT id,employee_id FROM asset_assignments WHERE asset_id=? AND returned_at IS NULL FOR UPDATE").bind(assetId).first<{id:number;employee_id:number}>();if(!assignment)throw new Response("Asset has no active assignment",{status:409});await tx.prepare("UPDATE asset_assignments SET returned_at=CURRENT_TIMESTAMP,returned_by_user_id=?,return_condition=?,return_notes=? WHERE id=? AND returned_at IS NULL").bind(actor.id,text(input.condition)||"good",text(input.notes)||null,assignment.id).run();const next=text(input.nextStatus)||"available";if(!["available","maintenance","lost","retired"].includes(next))throw new Response("Invalid returned asset status",{status:400});await tx.prepare("UPDATE assets SET status=?,asset_condition=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(next,text(input.condition)||"good",assetId).run();return assignment;});await notifyEmployee(db,result.employee_id,{type:"assets",title:"asset_returned",entityType:"asset",entityId:assetId,path:"assets",key:`asset:${assetId}:returned:${result.id}`});await audit(db,actor,"return","assets","asset",assetId,{employeeId:result.employee_id,assignmentId:result.id});return Response.json({ok:true});}
  if(action==="status"){await requireModule(db,actor,"assets","edit");const id=number(input.assetId),status=required(input.status,"status");if(!["available","maintenance","lost","retired"].includes(status))throw new Response("Invalid asset status",{status:400});const active=await db.prepare("SELECT id FROM asset_assignments WHERE asset_id=? AND returned_at IS NULL").bind(id).first();if(active)throw new Response("Return the asset before changing its status",{status:409});await db.prepare("UPDATE assets SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(status,id).run();await audit(db,actor,"status_change","assets","asset",id,{status});return Response.json({ok:true});}
  throw new Response("Unsupported asset action",{status:400});
});
}
